<?php $filter = $this->frm_search;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>

<div >
<div class="menureport">
	<ul>
		<li class="preview"><a title="Preview" href="#" onclick="preview();"></a></li>
		<li class="print"><a href="#" title="Print" onclick="doPrint();" ></a></li>
		<li class="excel"><a href="#"  title="Export"  onclick="exportExcel();"></a></li>

</div>
<!-- export library -->
	 <script type="text/javascript" src="<?php echo $this->baseUrl();?>/tableexport/tableExport.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/tableexport/jquery.base64.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/tableexport/html2canvas.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/tableexport/jspdf/libs/sprintf.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/tableexport/jspdf/jspdf.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/tableexport/jspdf/libs/base64.js"></script> 
<script type="text/javascript">
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    hideDialog();
}
function preview()
{ 
  var disp_setting="toolbar=no,status=no,resizable=no,location=no,directories=yes,menubar=no,"; 
      disp_setting+="scrollbars=no,width=1100, height=700, left=100, top=25"; 
  var content_vlue = document.getElementById("divPrint").innerHTML; 
  
  var docprint=window.open("","",disp_setting); 
   docprint.document.open(); 
   docprint.document.write('<html><head>'); 
   docprint.document.write('</head><div style=" font-size:16px !important; margin:0px; font-family:Verdana;"><style>table th {font-size:14px !important;} table td{font-size:12px !important;}</style><center>');          
   docprint.document.write(content_vlue);          
   docprint.document.write('</center></div></html>'); 
   docprint.document.close(); 
   docprint.focus(); 
}
function exportExcel(){
	$('#exportExcel').tableExport({type:'excel',escape:'false'});
}
</script>
