<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$brach_name =  $this->branch;
$formFilter = $this->formFilter;
?>
<title>Product List Report</title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("PURCHES_LIST");?>
				</div>
						<div class="btn-group pull-right">
							 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
							   Actions <i class="fa fa-angle-down"></i>
							 </button>
							<ul class="dropdown-menu" role="menu">
								<li>
									<a href="#" onclick="doPrint();">
										<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;<?php echo $tr->translate("PRINT");?>
									</a>
								</li>
							</ul>
						</div>
			</div>
            <div class="portlet-body form frmfilter">
				<form method="post" action="<?php echo $formFilter->getAction(); ?>">
					<div class="form-group" style="padding-top: 6px;">
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('text_search');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('purchase_status');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('start_date');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('end_date');?></label>
						<label class="control-label col-md-2">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
						</label>
					</div>			
				</form>
			<div id="divPrint">	
			<style>
				.style{
					line-height: 20px;font-size: 9px !important;
					font-family: 'Khmer OS Battambang';
				}
				ul{margin: 0;padding:0;}
				table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
				th{padding: 0px;}
				table thead tr th{
					line-height:30px;
					background:#ccc;
					font-size:15px;
					padding:3px;
				}
				table tr td{
					line-height:20px;
					padding:5px;
					font-size:12px;
				}
				ul.pur_info li{line-height:18px; 
						font-weight: normal !important;}
				ul.pur_info li strong{font-weight: bold;}
			   .hover:hover{background: #ccc;}
			</style>
			<table style="font-family: 'Khmer OS Content'; width:100%;">
				<tbody>
				<tr>
					<td align="center">
						<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
							<tbody>
							<tr style="margin-bottom:10px;"> 
								<td width="20%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logo/<?php echo $this->title_reprot["logo"]?>"></td>
								<td width="60%" valign="top" style="line-height:30px">
									<ul>
										<li style="text-align:center; font-size:20px; font-family:'Khmer OS Muol Light'"><?php echo $this->title_reprot["title_report_kh"]?></li>
										<li style="text-align:center; font-size:18px; font-family:serif,header-font; font-weight:600;"><?php echo $this->title_reprot["title_report_en"]?></li>
										<li style="text-align:center; font-size:20px; margin-top:25px; font-family:serif,header-font; font-weight:600;"><?php echo $tr->translate("RPT_RECEIVE_STOCK");?></li>
									</ul>
								</td>
								<td width="20%" style="text-align:center; font-size: 11px;white-space: nowrap;">
								</td>
							</tr> 
						</tbody></table>
					</td>
				</tr>
				<tr>
					<table  border="1"  class="collape tablesorter" style="border-collapse:collapse;border:1px solid #000; font-family: 'Khmer OS Battambang';" width="100%" cellspacing="0">
						<thead>
							<tr>
								<th class="tdheader"><?php echo  $tr->translate("NUM");?></th>
								<th class="tdheader"><?php echo  $tr->translate("INVOICE_NO");?></th>
								<th class="tdheader"><?php echo  $tr->translate("INVOICE_DATE");?></th>
								<th class="tdheader"><?php echo  $tr->translate("RECEIVE_DATE_FROM_STOCK");?></th>
								<th class="tdheader"><?php echo  $tr->translate("DN_NO");?></th>
								<th class="tdheader"><?php echo  $tr->translate("TOTAL_AMOUNT");?></th>
								<th class="tdheader"><?php echo  $tr->translate("PAID");?></th>
								<th class="tdheader"><?php echo  $tr->translate("BALANCE");?></th>
								<th class="tdheader"><?php echo  $tr->translate("USER");?></th>
							</tr>
						</thead>
						<tbody>
							<?php 
							if(!empty($this->rs)){
								foreach ($this->rs as $key=>$rs){
									
							?>
								<tr class="normal">
									<td class="items-no"><?php echo $key+1;?></td>
									<td class="items"><?php echo $rs["invoice_no"];?></td>
									<td class="items"><?php echo $rs["invoice_date"];?></td>
									<td class="items"><?php echo $rs["invoice_date_from_stock"];?></td>
									<td class="items"><?php echo $rs["dn_number"];?></td>
									<td class="items">&nbsp;$<span style="float:right;"><?php echo $rs["total"];?></span></td>
									<td class="items">&nbsp;$<span style="float:right;"><?php echo $rs["paid"];?></span></td>
									<td class="items">&nbsp;$<span style="float:right;"><?php echo $rs["balance"];?></span></td>
									<td class="items"><?php echo $rs["user_name"];?></td>
								</tr>
							<?php }}?>
						</tbody>
					</table>
				</tr>
			</tbody>
		</table>	
			    </div>
		   </div>
		</div>  
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=document.getElementById('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
}
</script>
