<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("REQUEST_TRANSFER_CHECK");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("REQUEST_TRANSFER_CHECK");?>
				</div>
						<!--<div class="btn-group pull-right">
							 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
							   Actions <i class="fa fa-angle-down"></i>
							 </button>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a href="#" onclick="doPrint();">
											<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
										</a>
									</li>
								</ul>
					</div>-->
			</div>
            <div class="portlet-body form frmfilter">
					<div style="clear:both;"></div>	
	<div style=" min-height:25cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	 <?php $url_submit = $this->url(array('module'=>'sales','controller'=>'invoiceapprove','action'=>'approved'));?>
	<form id="form_sample_2" action="<?php //echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post">		   
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 20px;font-size: 9px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px;}
		th{padding: 5px;}
		ul.pur_info li{line-height:18px; 
				font-weight: normal !important;}
		ul.pur_info li strong{font-weight: bold;}
       .hover:hover{background: #ccc;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody>
						<tr>
		                	<td width="20%" valign="middle"><img src="<?php echo $this->baseUrl();?>/images/logo/<?php echo $this->title_reprot["logo"]?>"></td>
								<td width="60%" valign="top" style="line-height:30px">
									<ul>
										<li style="text-align:center; font-size:20px; font-family:'Khmer OS Muol Light'"><?php echo $this->title_reprot["title_report_kh"]?></li>
										<li style="text-align:center; font-size:18px; font-family:serif,header-font; font-weight:600;"><?php echo $this->title_reprot["title_report_en"]?></li>
										<li style="text-align:center; font-size:18px; margin-top:25px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("REQUEST_TRANSFER_CHECK");?></li>
									</ul>
								</td>
								<td width="20%"></td>
		                </tr> 
		                <tr>
		                	<td colspan="3" valign="top">
		                		<table width="100%" cellpadding="0" cellspacing="0" >
		                			<tbody>
		                			<tr>
		                				<td style="font-size: 11px;">
		                				    <span style="white-space: nowrap;"><?php //echo $tr->translate("ADDRESS_COMPANY");?></span>
		                					<br><?php //echo $tr->translate("TEL_COMPANY");?> 
		                				</td>
		                				
		                				<td width="65%"></td>
		                			</tr>
		                			
				                </tbody>
								</table>
				              </td>
						</tr>
							  
							<tr>
								<td valign="bottom">
									<table  width="100%" cellpadding="0" cellspacing="0" >
										<tr style="font-size: 12px;">
											<td> <?php echo $tr->translate("REQUEST_LOCATION")?></td>
											<td>:</td>
											<td><?php echo $this->rs['re_from'];?></td>
										
										</tr>
										<tr style="font-size: 12px;">
										<td> <?php echo $tr->translate("REQUEST_TO")?></td>
										<td>:</td>
										<td><?php echo $this->rs['re_to'];?></td>
									</tr>
									</table>
								</td>
								<td></td>
							  <td>
									<table  width="100%" cellpadding="0" cellspacing="0" >
									<tr style="font-size: 12px;">
										<td> <?php echo $tr->translate("TRANSFER_NUM")?></td>
										<td>:</td>
										<td style="text-align:right;"><?php echo $this->rs['tran_no'];?></td>
									</tr>
									<tr style="font-size: 12px;">
										<td> <?php echo $tr->translate("TRANSFER_DATE")?></td>
										<td>:</td>
										<td style="text-align:right;"><?php echo date("M-d-Y",strtotime($this->rs['re_date']));?></td>
									</tr>
									
								</table>
							  </td>
				           </tr>   
		            </tbody></table>
		        </td>
		    </tr>
		    <tr>
		    	<td id="exportExcel"><br />
		            <table  class="collape tablesorter" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0" border="1">
		                 <tbody>
		                 <tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; font-size:13px !important; padding:1px 0px; white-space: nowrap; ">
		                    <th class="tdheader">&nbsp;<?php echo $tr->translate("NUM");?></th>
							<th class="tdheader"><?php echo $tr->translate("ITEM_CODE");?></th>
							<th class="tdheader"><?php echo $tr->translate("ITEM_NAME");?></th>
							<th class="tdheader">&nbsp;<?php echo $tr->translate("QTY");?></th>
							<th class="tdheader"><?php echo $tr->translate("MEASURE");?></th>
							<th class="tdheader"><?php echo $tr->translate("NOTE");?></th>
		                <?php $num=1; 
		               
		                if(!empty($this->rs_detail))foreach ($this->rs_detail AS $index => $rs){?>
						<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_code"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_name"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["qty"],2);?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["measure"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["remark"];?></td>
						</tr>
						   <?php 
                    }?>
                   
					
		            </tbody>
		           </table>
		              <br>
		            
					
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div><!-- end print -->
		 <table align="center" width="100%" >
							   <tbody>
							   <tr style="font-size: 11px;">
									<td style="white-space: nowrap;"><?php echo $tr->translate("REASON")?>: </td>
							        <td valign="bottom" style="text-align:center;white-space: nowrap;"><textarea name="remark" id="remark" class="form-control" rows="3" cols="80" placeHolder="Check Comment Here"><?php echo $this->rs["reason"]?></textarea></td>
									<td width="5%"><td>
									<td style="white-space: nowrap;"><?php echo $tr->translate("REJECT_FROM_APPROVE")?>: </td>
							        <td valign="bottom" style="text-align:center;white-space: nowrap;"><textarea name="remark_app" id="remark_app" class="form-control" rows="3" cols="80" placeHolder="Approve Comment Here"><?php echo $this->rs["approve_reason"]?></textarea></td>
							   </tr>
							   <tr >
									<td style=""></td>
									<td></td>
									<td></td>
									<td></td>
									<td></td>
									<td style="white-space: nowrap; padding-top:10px;">
										<select name="approved_name" id="approved_name" class="form-control select2me">
											<option value="1"><?php echo $tr->translate("CHECKED")?></option>
											<option value="2"><?php echo $tr->translate("REJECT")?></option>
										</select><input type="hidden" name="id" id="id" value="<?php echo $this->product[0]['id'];?>" />
										<input type="hidden" name="branch_id" id="branch_id" value="<?php echo $this->product[0]['branch_id'];?>" />
									
							        </td>
							   </tr>
							</tbody>
						</table>
		
		<div class="form-group">
			<div  class="col-md-12 col-md-offset-3 col-md-8">
				<label class="col-md-3 control-label"><a href="<?php echo $this->baseUrl();?>/product/transfer/requestcheck/" ><button style="width:90%;" type="button" class="btn red btn-lg"><i class="fa fa-times"></i> <?php echo $tr->translate("GO_BACK")?></button></a></label>
				<div class="col-md-3 control-label"><button type="submit" name="print" value="print" class="btn blue btn-block btn-lg" ><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button></div>
		        <!--<div class="col-md-3 control-label"><button type="submit" name="saveprint" value="saveprint" class="btn blue btn-block btn-lg" ><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?></button></div>-->
			</div>
		</div>
		</form>	
		
		
		
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>

$(document).ready(function() { 
   
  calculateBalance();
 }); 

 
function calculateBalance(){
	deposit= $("#deposit").val();
	net_total = $('#net_total').val();
	balance = parseFloat(net_total)-parseFloat(deposit);
	if(balance<0){
		balance=0;
		$("#deposit").val(net_total);
	}
	$("#balance").val(balance);
}
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=document.getElementById('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    //hideDialog();
}

</script>
