<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$url_submit =  $this->url(array('module'=>'product','controller'=>'adjust','action'=>'add'));
$url_cancel =  $this->url(array('module'=>'product','controller'=>'transfer','action'=>'requestlist'),null,true);
$url_getcurrentitem =  $this->url(array('module'=>'product','controller'=>'adjust-stock','action'=>'get-current-quantity'));
$url_getProduct =  $this->url(array('module'=>'product','controller'=>'adjust','action'=>'get-product'));
$formFilter = $this->formFilter;
//print_r($this->rs_detail);
?>

<title><?php echo $tr->translate("TRANSFER_STOCK");?></title>
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>-->
<br/>
<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("EDIT_NEW_TRANSFER");?>
			</div>
			<div class="caption" style="float:right">
					<?php $formList = new Application_Form_Frmlist(); //echo $formList->showAddBuntton($url_new);?>
			</div>
			<div class="tools">
				<a href="<?php echo $url_cancel;?>"><button type="button" name="calcel" class="btn red"><?php echo $tr->translate("GO_BACK");?></button></a>
			</div>
		</div>
		<div class="portlet-body form">
			<form class="form-horizontal" method="post" action="" >
				<div class="form-body">	
					<div class="form-group">
						<label class="col-md-2 control-label"><?php echo $tr->translate("TRANSFER_NUM");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('tran_num');?>
						</div>
						<label class="col-md-2 control-label"><?php echo $tr->translate("TRANSFER_DATE");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('tran_date');?>
						</div>
						
					</div>
					<div class="form-group">
						<label class="col-md-2 control-label"><?php echo $tr->translate("REQUET_TO_FROM");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('from_loc');?>
						</div>
						<label class="col-md-2 control-label"><span id="lb_br"></span><?php echo $tr->translate("REQUET_TO_BRANCH");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('to_loc');?>
						</div>							
							
					</div>
					<div class="form-group">
						
						<label class="col-md-2 control-label"><?php echo $tr->translate("REMARK");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('remark');?>
						</div>	
					
						
						<label class="col-md-2 control-label"><?php echo $tr->translate("STATUS");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('status');?>
						</div>
					</div>
					<div class="form-group">
							<div class="col-md-2">
								<button type="button" class="btn red delete" style="width:100%;">
								<i class="fa fa-barcode"></i>
								<span><?php echo $tr->translate("SCAN");?></span>
								</button>
							</div>
							<div class="col-md-8">
								<select data-placeholder="Select..." class="form-control select2me" id="add_item" name="add_item" Onchange="addNew();"  style="width:100% ;margin:0 auto;">
											<?php echo $this->items; ?>
								</select>
							</div>
							<div class="col-md-2">
								<button type="button" class="btn red delete" style="width:100%;">
								<i class="fa fa-barcode"></i>
								<span><?php echo $tr->translate("SCAN");?></span>
								</button>
							</div>
						</div>
													
					<div class="portlet box blue">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-cogs"></i><?php echo $tr->translate("PRODUCT_LIST");?>
							</div>
						</div>	
							<div class="portlet-body">
								<div class="table-responsive">
									<table class="table table-bordered">
										<thead>
											<tr>
												<th><?php echo $tr->translate("NUM");?></th>
												<th><?php echo $tr->translate("ITEM_NAME");?></th>
												<th><?php echo $tr->translate("QTY_TRANSFER");?></th>
												<th><?php echo $tr->translate("MEASURE");?></th>
												<th><?php echo $tr->translate("REMARK");?></th>
												<th><?php echo $tr->translate("ACTION");?></th>
											</tr>
										</thead>
										<tbody id="tr_location" style="font-size:12px;">
										</tbody>
									</table>
								</div>
								<input type="hidden" name="identity" id="identity" value="<?php //echo $identity;?>" >
							</div>
					</div>
					<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("REJECT_FROM_CHECK");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<textarea name="remark" id="remark" class="form-control" rows="3" cols="80" placeHolder="Check Comment Here"><?php echo $this->rs_detail[0]["reason"]?></textarea>
								</div>
							</div>
							
							<label class="control-label col-md-2"><?php echo $tr->translate("REJECT_FROM_APPROVE");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<textarea name="remark" id="remark" class="form-control" rows="3" cols="80" placeHolder="Approve Comment Here"><?php echo $this->rs_detail[0]["approve_reason"]?></textarea>
								</div>
							</div>
						</div>
					<div class="form-group" style="padding-top: 6px;">
						<div  class="col-md-12 col-md-offset-4 col-md-8">
							<a href="<?php echo $this->baseUrl();?>/product/transfer/requestlist"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
							<button type="submit" name="save_close" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
							<button type="submit" name="btnsavenew" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
									
						</div>
					</div>
				</div>
			</form>
		</div>
</div>
<script type="text/javascript">

jQuery(document).ready(function(){
	//addRow();
	oldRow();
});
function oldRow(){
	<?php if(!empty($this->rs_detail)){
			foreach( $this->rs_detail as $rs){
				
	?>
			index++;
			template='<tr id="row_location_'+index+'">';
			template+='<td>'+index+'</td>';
			template+='<td style="white-space: nowrap;"><?php echo $rs["item_name"];?><input type="hidden" id="pro_id_'+index+'" name="pro_id_'+index+'" value="<?php echo $rs["pro_id"]?>" </td>';
			template+='<td><input type="text" id="qty_tran_'+index+'" name="qty_tran_'+index+'" value="<?php echo $rs['qty']?>" class="form-control"><input type="hidden" name="qty_'+index+'" id="qty_'+index+'" value="<?php echo $rs['qty']?>" /></td>'; 
			template+='<td><label id="lb_measure_'+index+'"><?php echo $rs["measure"]?></label></td>';
			template+='<td><input type="text" id="remark_'+index+'" name="remark_'+index+'" class="form-control"></td>';
			template+='<td><button type="button" onClick="deleteRecord('+index+',1)" name="save_close" class="btn default"><?php echo $tr->translate("DELETE");?></button></td>';
			template+='</tr>';
			$('#tr_location').append(template);
			if($('#identity').val()!="") {
				var identity = $('#identity').val();
				$('#identity').val(identity+','+index);
			} else {$('#identity').val(index);}
	<?php }}?>
}
var index=0;
function addNew(){
	id = $("#pro_name").val();
	index++;
	$.ajax({
        url: "<?php echo $url_getProduct;?>",
        type: "post",
        data: {'id':id},
        success: function(val){
            //alert(data);
			for(i=1; i<index; i++){
				new_item=parseInt(id);
				items = parseInt($("#pro_id_"+i).val());
				if(new_item==items){		
					newqty = parseInt($("#qty_tran_"+i).val());
					newqty = newqty+1;
					$("#qty_tran_"+i).val(newqty);
					checkQTY(i);
					return false;
					
				}
			}
			 data = $.parseJSON(val);
			template='<tr id="row_location_'+index+'">';
			template+='<td>'+index+'</td>';
			template+='<td style="white-space: nowrap;">'+data.item_name+" "+data.brand+" "+data.size+" "+data.color+'<input type="hidden" id="pro_id_'+index+'" name="pro_id_'+index+'" value="'+data.id+'" </td>';
			template+='<td><input type="text" id="qty_tran_'+index+'" name="qty_tran_'+index+'" value="1" class="form-control"><input type="hidden" name="qty_'+index+'" id="qty_'+index+'" value="'+data.qty+'" /></td>'; 
			template+='<td><input type="text" id="remark_'+index+'" name="remark_'+index+'" class="form-control"></td>';
			template+='<td><button type="button" onClick="deleteRecord('+index+',1)" name="save_close" class="btn default"><?php echo $tr->translate("DELETE");?></button></td>';
			template+='</tr>';
			$('#tr_location').append(template);
			if($('#identity').val()!="") {
				var identity = $('#identity').val();
				$('#identity').val(identity+','+index);
			} else {$('#identity').val(index);}
        },
        error:function(){
           // alert("Please Product Name And Location");
            $("#result").html('There is error while submit');
        }
    });
}
	
	function checkQTY(index){
		qty = parseFloat($('#qty_'+index).val());
		qty_tran = parseFloat($('#qty_tran_'+index).val());
		translate = "This Product is remain "+qty+" Only";
		if(qty_tran>qty){
			alert("This Product is remain "+qty+" Only");
			$('#qty_tran_'+index).val(qty)
		}
	}
	function transferType(){
		var type= $('#type').val();
		if(type==1){
			document.getElementById('lb_br').innerHTML = "From ";
		}else if(type==2){
			document.getElementById('lb_br').innerHTML = "To ";
		}
	}

function deleteRecord(index,type) {
		if(type==1){
			var identity = $('#identity').val();
			var arrays = identity.split(',');
		}else{
			var identity = $('#identity_price').val();
			var arrays = identity.split(',');
		}
		
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		
		if(type==1){
			$('#identity').val(strings);
			$("#row_location_"+index).remove();
		}else{
			$('#identity_price').val(strings);
			$("#row_price_"+index).remove();
		}
	}


function ShowPopupProduct(index){
	item_id = $("#item_id_"+ index).val();
	record_id = index;
	if(item_id==-1){
		ShowDialog(true);
	}
}

function AddLocation(index){
	var location_id= $("#location_id_"+index).val();
	var item_id = $("#item_id_"+ index).val();
	if(location_id==-1){
		     record_id = index;
		     AddNewLocation(true);
	  }	
	else{
		$.ajax({
		        url: "<?php echo $url_getcurrentitem;?>",
		        type: "post",
		        data: {'item_id':item_id, 'location_id':location_id},
		        success: function(data){
		            //alert(data);
		            val = $.parseJSON(data);
		            $("#qty_before_"+ index).val(val.qty);
		        },
		        error:function(){
		           // alert("Please Product Name And Location");
		            $("#result").html('There is error while submit');
		        }
		    });
		}
}
<?php $url_add_new =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-new')); ?>
function addProduct(){
	var pro_name = $("#txt_name").val();
	var pro_code = $("#item_code").val();
	var category_id = $("#category_id").val();
	var brand_id = $("#brand_id").val();
	var remark = $("#remark_order").val();
	validate_text('#txt_name');
	validate_text('#item_code');
		$.ajax({
	        url: "<?php echo $url_add_new;?>",
	        type: "post",
	        data: {'pro_name':pro_name,'pro_code':pro_code,'category_id':category_id,'brand_id':brand_id,'remark':remark},
	        success: function(data){
	           val = $.parseJSON(data);
	           $('#item_id_'+record_id).append($('<option></option>').attr('value',val['pid']).attr("selected",true).text(pro_name)); 
	           $('#item_id_'+record_id).trigger("liszt:updated");
	            document.getElementById("frm1").reset();
	            HideDialog();
	        },
	        error:function(){
	            $("#result").html('There is error while submit');
	        }
	    });	
}
<?php $url_add_location =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-new-location')); ?>
function addNewLocation(){
	var location_name = $("#StockName").val();
	var ContactName   = $("#ContactName").val();
	var ContactNumber = $("#ContactNumber").val();
	var location_add  = $("#location_add").val();
	var remark_add    = $("#description").val();
	validate_text('#StockName');
	$.ajax({
        url: "<?php echo $url_add_location;?>",
        type: "post",
        data: {'location_name':location_name,'ContactName':ContactName,'ContactNumber':ContactNumber,'location_add':location_add,'remark_add':remark_add},
        success: function(data){
           val = $.parseJSON(data);
            $('#location_id_'+record_id).append($("<option></option>").attr("value",val['LocationId']).attr("selected",true).text(location_name)); 
            $('#location_id_'+record_id).trigger("liszt:updated");
            document.getElementById("frm-location").reset();
            HideDialoglocation();
        },
        error:function(){
            alert("faile insert");
            $("#result").html('There is error while submit');
        }
    });
}
</script>