<?php $url= $this->url(array('module'=>'report','controller'=>'index','action'=>'month'));?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Show List Menu</title>
</head>
<body id="top">
<div id="wraper" style="width:290px;">
		<div class="accordionButton" style="font-weight:normal;"><font face="Khmer Muol" size="2">Sale Report 2010</font></div>
		<div class="accordionContent" style="display: none;">
            	<ul>
            		<li><a href="<?php echo $url?>?y=10&m=1">January</a></li>
            		<li><a href="#">February</a></li>
            		<li><a href="#">March</a></li>
            		<li><a href="#">April</a></li>
            		<li><a href="#">May</a></li>
            		<li><a href="#">June</a></li>
            		<li><a href="#">July</a></li>
            		<li><a href="#">August</a></li>
            		<li><a href="#">September</a></li>
            		<li><a href="#">October</a></li>
            		<li><a href="#">November</a></li>
            		<li><a href="#">December</a></li>
            	</ul>        
        </div>
        
		<div class="accordionButton" style="font-weight:normal;">
        	<font face="Khmer Muol" size="2">Sale Report 2011</font></div>
		<div class="accordionContent" style="display: none;">
        	<ul>
            		<li><a href="#">January</a></li>
            		<li><a href="#">February</a></li>
            		<li><a href="#">March</a></li>
            		<li><a href="#">April</a></li>
            		<li><a href="#">May</a></li>
            		<li><a href="#">June</a></li>
            		<li><a href="#">July</a></li>
            		<li><a href="#">August</a></li>
            		<li><a href="#">September</a></li>
            		<li><a href="#">October</a></li>
            		<li><a href="#">November</a></li>
            		<li><a href="#">December</a></li>
            	</ul>                      
        </div>
        
		<div class="accordionButton" style="font-weight:normal;"><font face="Khmer Muol" size="2">Sale Report 2012</font></div>
		<div class="accordionContent" style="display: none;">
           <ul>
            		<li><a href="#">January</a></li>
            		<li><a href="#">February</a></li>
            		<li><a href="#">March</a></li>
            		<li><a href="#">April</a></li>
            		<li><a href="#">May</a></li>
            		<li><a href="#">June</a></li>
            		<li><a href="#">July</a></li>
            		<li><a href="#">August</a></li>
            		<li><a href="#">September</a></li>
            		<li><a href="#">October</a></li>
            		<li><a href="#">November</a></li>
            		<li><a href="#">December</a></li>
            	</ul>               
        </div>
        
        <div class="accordionButton" style="font-weight:normal;">
        	<font face="Khmer Muol" size="2">Sale Report 2013</font></div>
		<div class="accordionContent" style="display: none;">
        	<ul>
            		<li><a href="#">January</a></li>
            		<li><a href="#">February</a></li>
            		<li><a href="#">March</a></li>
            		<li><a href="#">April</a></li>
            		<li><a href="#">May</a></li>
            		<li><a href="#">June</a></li>
            		<li><a href="#">July</a></li>
            		<li><a href="#">August</a></li>
            		<li><a href="#">September</a></li>
            		<li><a href="#">October</a></li>
            		<li><a href="#">November</a></li>
            		<li><a href="#">December</a></li>
            	</ul>                        
        </div>
        
        <div class="accordionButton" style="font-weight:normal;">
        	<font face="Khmer Muol" size="2">Sale Report 2014</font></div>
		<div class="accordionContent" style="display: none;">
        	<ul>
            		<li><a href="#">January</a></li>
            		<li><a href="#">February</a></li>
            		<li><a href="#">March</a></li>
            		<li><a href="#">April</a></li>
            		<li><a href="#">May</a></li>
            		<li><a href="#">June</a></li>
            		<li><a href="#">July</a></li>
            		<li><a href="#">August</a></li>
            		<li><a href="#">September</a></li>
            		<li><a href="#">October</a></li>
            		<li><a href="#">November</a></li>
            		<li><a href="#">December</a></li>
            	</ul>                        
        </div>
        
         <div class="accordionButton" style="font-weight:normal;">
        	<font face="Khmer Muol" size="2">Sale Report 2015</font></div>
		<div class="accordionContent" style="display: none;">
        	<ul>
            		<li><a href="#">January</a></li>
            		<li><a href="#">February</a></li>
            		<li><a href="#">March</a></li>
            		<li><a href="#">April</a></li>
            		<li><a href="#">May</a></li>
            		<li><a href="#">June</a></li>
            		<li><a href="#">July</a></li>
            		<li><a href="#">August</a></li>
            		<li><a href="#">September</a></li>
            		<li><a href="#">October</a></li>
            		<li><a href="#">November</a></li>
            		<li><a href="#">December</a></li>
            	</ul>                         
        </div>
        
        <div class="accordionButton" style="font-weight:normal;">
        	<font face="Khmer Muol" size="2">Sale Report 2016</font></div>
		<div class="accordionContent" style="display: none;">
        	<ul>
            		<li><a href="#">January</a></li>
            		<li><a href="#">February</a></li>
            		<li><a href="#">March</a></li>
            		<li><a href="#">April</a></li>
            		<li><a href="#">May</a></li>
            		<li><a href="#">June</a></li>
            		<li><a href="#">July</a></li>
            		<li><a href="#">August</a></li>
            		<li><a href="#">September</a></li>
            		<li><a href="#">October</a></li>
            		<li><a href="#">November</a></li>
            		<li><a href="#">December</a></li>
            	</ul>                        
        </div>    
</div>
</div>
</body></html>