<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();
  $rpt_product_list=$this->url(array('module'=>'report','controller'=>'product','action'=>'rptproductlist'), null, true);
  $rpt_current=$this->url(array('module'=>'report','controller'=>'product','action'=>'rptcurrentstock'), null, true);
  $rpt_ajust=$this->url(array('module'=>'report','controller'=>'product','action'=>'rptadjuststock'), null, true);
  $rpt_transfer=$this->url(array('module'=>'report','controller'=>'product','action'=>'rpttransfer'), null, true);
  $rpt_request_transfer=$this->url(array('module'=>'report','controller'=>'product','action'=>'rptrequesttransfer'), null, true);
  $rpt_check_request_transfer=$this->url(array('module'=>'report','controller'=>'product','action'=>'rptcheckrequesttransfer'), null, true);
  $rpt_transfer_list=$this->url(array('module'=>'report','controller'=>'product','action'=>'rpttransferlist'), null, true);
  $rpt_receive_transfer=$this->url(array('module'=>'report','controller'=>'product','action'=>'rptreceivetransfer'), null, true);
  $rpt_product_warning=$this->url(array('module'=>'report','controller'=>'product','action'=>'rptproductwarning'), null, true);
  
  ?>
<div class="row">
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat blue-madison">
						<a class="more" href="<?php echo $rpt_product_list;?>">
						<div class="visual">
							<i class="fa fa-comments"></i>
						</div>
						<div class="details">
							<div class="number">
							</div>
							<div class="desc">
								<?php echo $tr->translate("RPT_PL");?>
							</div>
						</div>
						</a>
						<a class="more" href="<?php echo $rpt_product_list;?>">
						<?php echo $tr->translate("VIEW_MORE");?>  <i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat blue-madison">
						<a class="more" href="<?php echo $rpt_current;?>">
						<div class="visual">
							<i class="fa fa-bar-chart-o"></i>
						</div>
						<div class="details">
							<div class="number">
								 
							</div>
							<div class="desc">
								<?php echo $tr->translate("RPT_CL");?>
							</div>
						</div>
						</a>
						<a class="more" href="<?php echo $rpt_current;?>">
						<?php echo $tr->translate("VIEW_MORE");?> <i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat red-intense">
						<a class="more" href="<?php echo $rpt_product_warning;?>">
						<div class="visual">
							<i class="fa fa-bar-chart-o"></i>
						</div>
						<div class="details">
							<div class="number">
								 
							</div>
							<div class="desc">
								<?php echo $tr->translate("RPT_PRO_WARNING");?>
							</div>
						</div>
						</a>
						<a class="more" href="<?php echo $rpt_product_warning;?>">
						<?php echo $tr->translate("VIEW_MORE");?> <i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat green-haze">
						<a class="more" href="<?php echo $rpt_ajust;?>">
						<div class="visual">
							<i class="fa fa-shopping-cart"></i>
						</div>
						<div class="details">
							<div class="number">
							</div>
							<div class="desc">
								<?php echo $tr->translate("RPT_ADS");?> 
							</div>
						</div>
						</a>
						<a class="more" href="<?php echo $rpt_ajust;?>">
						<?php echo $tr->translate("VIEW_MORE");?> <i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
			</div>
		<!--	
			<hr />
			
			<div class="row">
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat blue-madison">
						<a class="more" href="<?php echo $rpt_request_transfer;?>">
						<div class="visual">
							<i class="fa fa-comments"></i>
						</div>
						<div class="details">
							<div class="number">
							</div>
							<div class="desc">
								 Request Transfer List Report
							</div>
						</div>
						</a>
						<a class="more" href="javascript:;">
						<?php echo $tr->translate("VIEW_MORE");?> <i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat red-intense">
						<a class="more" href="<?php echo $rpt_check_request_transfer;?>">
						<div class="visual">
							<i class="fa fa-bar-chart-o"></i>
						</div>
						<div class="details">
							<div class="number">
								 
							</div>
							<div class="desc">
								 Check Request Transfer Report
							</div>
						</div>
						</a>
						<a class="more" href="javascript:;">
						<?php echo $tr->translate("VIEW_MORE");?> <i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat green-haze">
						<a class="more" href="<?php echo $rpt_transfer_list;?>">
						<div class="visual">
							<i class="fa fa-shopping-cart"></i>
						</div>
						<div class="details">
							<div class="number">
							</div>
							<div class="desc">
								 Transfer Report
							</div>
						</div>
						</a>
						<a class="more" href="javascript:;">
						<?php echo $tr->translate("VIEW_MORE");?> <i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat purple-plum">
						<a class="more" href="<?php echo $rpt_receive_transfer;?>">
						<div class="visual">
							<i class="fa fa-globe"></i>
						</div>
						<div class="details">
							<div class="number">
								 
							</div>
							<div class="desc">
								 Receive Transfer Report
							</div>
						</div>
						</a>
						<a class="more" href="javascript:;">
						<?php echo $tr->translate("VIEW_MORE");?> <i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div> 
				-->
			</div>