<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$brach_name =  $this->branch;
$formFilter = $this->formFilter;
?>
<title>Product List Report</title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("PRODUCT_REPORT");?>
				</div>
						<div class="btn-group pull-right">
							 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
							   Actions <i class="fa fa-angle-down"></i>
							 </button>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a href="#" onclick="doPrint();">
											<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
										</a>
									</li>
									<li>
										<a href="javascript:;"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
									</li>
									
								</ul>
					</div>
			</div>
            <div class="portlet-body form frmfilter">
				<form method="post" action="<?php //echo $formFilter->getAction(); ?>">
					<div class="form-body">
							<div class="form-group">
								<div class="col-md-2">
									<?php echo $formFilter->getElement('avd_search');?>
								</div>
								<div class="col-md-2">
									<?php echo $formFilter->getElement('branch');?>
								</div>
								<div class="col-md-2">
									<?php echo $formFilter->getElement('start_date');?>
								</div>
								<div class="col-md-2">
									<?php echo $formFilter->getElement('end_date');?>
								</div>
								<div class="col-md-2">
									<?php echo $formFilter->getElement('check_stat');?>
								</div>
								<!--<div class="col-md-2">
									<?php echo $formFilter->getElement('status');?>
								</div>-->
								<div class="col-md-2">
									<button type="submit" class="btn green"><?php echo $tr->translate("SEARCH");?></button>
								</div>
							</div>
					</div>
				<div style="clear:both;"></div>
				
				</form> 
				</div>
				<br />	
				<br />	
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 20px;font-size: 9px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
		th{padding: 5px;}
		.hover:hover{background: #ccc;}
		.center{text-align:center;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody>
						<tr style="margin-bottom:10px;"> 
								<td width="20%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logo/<?php echo $this->title_reprot["logo"]?>"></td>
								<td width="60%" valign="top" style="line-height:30px">
									<ul>
										<li style="text-align:center; font-size:20px; font-family:'Khmer OS Muol Light'"><?php echo $this->title_reprot["title_report_kh"]?></li>
										<li style="text-align:center; font-size:18px; font-family:serif,header-font; font-weight:600;"><?php echo $this->title_reprot["title_report_en"]?></li>
										<li style="text-align:center; font-size:20px; margin-top:25px; font-family:serif,header-font; font-weight:600;"><?php echo $tr->translate("RPT_REQUEST_TRANSFER");?></li>
									</ul>
								</td>
								<td width="20%" style="text-align:center; font-size: 11px;white-space: nowrap;">
									<!--<div  style=" border:1px solid #000; border-radius:5px !important;line-height: 11px;padding: 5px 5px">
										<p>ក្រុមហ៊ុន កាណាខនគ្រីត </p><p>ផ្នែកបញ្ជាទិញ និងគ្រប់គ្រងតម្លៃ</p>
									</div>-->
								</td>
							</tr> 
		                <tr>
		                	<td colspan="3" valign="top">
		                		<table width="100%" cellpadding="0" cellspacing="0">
		                			<tbody><tr>
		                				<td style="font-size: 11px;">
		                				    <span style="white-space: nowrap;"><?php //echo $tr->translate("ADDRESS_COMPANY");?></span>
		                					<br><?php //echo $tr->translate("TEL_COMPANY");?> 
		                				</td>
		                				<td width="65%"></td>
		                			</tr>
				                </tbody></table>
				              </td>
				           </tr>   
		            </tbody></table>
		        </td>
		    </tr>
		    <tr>
		    	<td id="exportExcel">
		            <table class="collape tablesorter" id="table" border="1" &#8203;="" style="border-collapse:collapse;border:1px solid #000; font-size:10px;" width="100%" cellspacing="0">
		                 <tbody><tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; line-height: 20px; font-size:12px; padding:1px 0px; white-space: nowrap; ">
		                    <tr style="background:#ccc">
								<th class="tdheader"><?php echo  $tr->translate("NO");?></th>
								<th class="tdheader"><?php echo  $tr->translate("REQUEST_NO");?></th>
								<th class="tdheader"><?php echo  $tr->translate("REQUEST_LOCATION");?></th>
								<th class="tdheader"><?php echo  $tr->translate("REQUEST_TO");?></th>
								<th class="tdheader"><?php echo  $tr->translate("REQUEST_DATE");?></th>
								<th class="tdheader"><?php echo  $tr->translate("APP_STATUS");?></th>
								<th class="tdheader"><?php echo  $tr->translate("PEDDING");?></th>
								<!--<th class="tdheader"><?php echo  $tr->translate("STATUS");?></th>-->
								<th class="tdheader"><?php echo  $tr->translate("USER");?></th>
								<th class="tdheader"><?php echo  $tr->translate("ACTION");?></th>
							</tr>
		                </tr>
		                <?php $num=1; 
		                if(!empty($this->product))foreach ($this->product AS $key => $row){ ?>
						<tr class="odd gradeX">
								<td class="center"><?php echo $key+1;?></td>
									<td><?php echo $row["tran_no"]?></td>
									<td><?php echo $row["re_tran"]?></td>
									<td><?php echo $row["to_tran"]?></td>
									<td><?php echo $row["date_tran"]?></td>
									<td><?php echo $row["appr_status"]?></td>
									<td><?php echo $row["appr_pedding"]?></td>
									<!--<td class="center">
										<?php if($row["status"] == 1){?>
										<span class="label label-sm label-success"><?php echo $tr->translate("ACTIVE");?> </span>
										<?php }else{?>
										<span class="label label-sm label-danger"><?php echo $tr->translate("DEACTIVE");?> </span>
										<?php }?>
									</td>-->
									<td><?php echo $row["user"]?> </td>
									<td>
										<a href="<?php echo $this->baseUrl();?>/product/transfer/requestnote/id/<?php echo $row["id"]?>"><?php echo $tr->translate("PRINT");?></a>
									</td>
						</tr>
						  <?php }?> 
		                </tbody>
		           </table>
		            <br>
		             
		              <br>
		             <table align="center" width="100%" >
						   <tbody>
						   <tr style="font-size: 11px;">
						        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'">អនុម័តដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'">ត្រួតពិនិត្យដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'">រៀបចំដោយ</th>
						   </tr>
						    <tr style="font-size: 11px; height: 75px;">
						        <td valign="bottom" style="width:20%;text-align:center;  font-family:'Khmer MEF2'; white-space: nowrap;">ឈ្មោះ  /Name--------------------------</td>
						        <td></td>
						        <td valign="bottom" style="width:20%;text-align:center; font-family:'Khmer MEF2';white-space: nowrap;">ឈ្មោះ  /Name--------------------------</td>
						        <td></td>
						        <td valign="bottom" style="width:20%;text-align:center;font-family:'Khmer MEF2';white-space: nowrap;">ឈ្មោះ  /Name--------------------------</td>
						   </tr>
						   <tr style="font-size: 11px;">
						        <td style="width:20%;text-align:center;white-space: nowrap;">ថ្ងៃ  /Date:----------------------------------</td>
						        <td></td>
						        <td style="width:20%;text-align:center;white-space: nowrap;">ថ្ងៃ  /Date:----------------------------------</td>
						        <td></td>
						        <td style="width:20%;text-align:center;white-space: nowrap;">ថ្ងៃ  /Date:----------------------------------</td>
						   </tr>
						</tbody>
					</table>
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=document.getElementById('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    //hideDialog();
}


</script>
