<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$brach_name =  $this->branch;
$formFilter = $this->formFilter;
?>
<title>Product List Report</title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("RPT_PL");?>
				</div>
						<div class="btn-group pull-right">
							 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
							   <?php echo $tr->translate("ACTIONS");?> <i class="fa fa-angle-down"></i>
							 </button>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a href="#" onclick="doPrint();">
											<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;<?php echo $tr->translate("PRINT");?>
										</a>
									</li>
									<li>
										<a href="javascript:;"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
									</li>
									
								</ul>
					</div>
			</div>
            <div class="portlet-body form frmfilter">
				<form method="post" style="border-bottom: 1px solid #ccc;" action="<?php //echo $formFilter->getAction(); ?>">
					<div class="form-body">
							<div class="form-group">
								<label class="control-label col-md-3">
									<?php echo $formFilter->getElement('ad_search');?>
								</label>
								
								<label class="control-label col-md-3">
									<?php echo $formFilter->getElement('branch');?>
								</label>
								
								<label class="control-label col-md-3">
									<?php echo $formFilter->getElement('brand');?>
								</label>
								
								<label class="control-label col-md-3">
									<?php echo $formFilter->getElement('category');?>
								</label>
								
							</div>
							<div class="form-group">
								<label class="control-label col-md-3">
									<?php echo $formFilter->getElement('size');?>
								</label>
								
								<label class="control-label col-md-3">
									<?php echo $formFilter->getElement('color');?>
								</label>
								
								<label class="control-label col-md-3">
									<?php echo $formFilter->getElement('status');?>
								</label>
								<label class="control-label col-md-3  pull-right">
									<button type="submit" class="btn btn-primary col-md-12"><?php echo $tr->translate("SEARCH");?></button>
								</label>
							</div>
				</div><div style="clear:both;"></div>	
				</form> 
	<div style=" min-height:28cm; margin:25 0 0 0; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 20px;font-size: 9px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px;}
		th{padding: 5px;}
		.hover:hover{background: #ccc;}
		.center{text-align:center;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody>
						<tr style="margin-bottom:10px;"> 
							<td width="20%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logo/<?php echo $this->title_reprot["logo"]?>"></td>
							<td width="60%" valign="top" style="line-height:30px">
								<ul>
									<li style="text-align:center; font-size:20px; font-family:'Khmer OS Muol Light'"><?php echo $this->title_reprot["title_report_kh"]?></li>
									<li style="text-align:center; font-size:18px; font-family:serif,header-font; font-weight:600;"><?php echo $this->title_reprot["title_report_en"]?></li>
									<li style="text-align:center; font-size:20px; margin: 15px 0px 7px 0px; font-family:'Khmer OS Muol Light',serif,header-font; "><?php echo $tr->translate("RPT_PL");?></li>
								</ul>
							</td>
							<td width="20%" style="text-align:center; font-size: 11px;white-space: nowrap;">
							</td>
						</tr> 
		                
		            </tbody></table>
		        </td>
		    </tr>
		    <tr>
		    	<td id="exportExcel">
		            <table border="1" class="collape tablesorter" id="table" style="border-collapse:collapse;border:1px solid #000; font-size:10px;" width="100%" cellspacing="0">
		                <tbody>
							<tr style="background:#ccc ; font-size:13px !important;">
								<th class="tdheader">&nbsp;<?php echo $tr->translate("NUM");?></th>
								<th class="tdheader"><?php echo $tr->translate("ITEM_CODE");?></th>
								<th class="tdheader"><?php echo $tr->translate("ITEM_NAME");?></th>
								<th class="tdheader"><?php echo $tr->translate("BRAND");?></th>
								<th class="tdheader"><?php echo $tr->translate("CATEGORY");?></th>
								<th class="tdheader"><?php echo $tr->translate("MODEL");?></th>
								<th class="tdheader"><?php echo $tr->translate("MEASURE");?></th>
								<th class="tdheader"><?php echo $tr->translate("QTY");?></th>
							</tr>
		                <?php $num=1; 
		                $r_netotal = 0;$r_paid = 0; $r_balance = 0;
		                $d_netotal = 0;$d_paid = 0; $d_balance = 0;
		                $b_netotal = 0;$b_paid = 0; $b_balance = 0;
		                if(!empty($this->product))foreach ($this->product AS $index => $row){?>
						<tr class="odd gradeX" id="item_<?php echo $index; ?>">
								<td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1 ?></td>
								<td style="white-space: nowrap;">&nbsp;<?php echo $row["item_code"]?></td>
								<td style="white-space: nowrap;">&nbsp;<?php echo $row["item_name"]?></td>
									<!--<td style="width:5% !important"><?php //echo $row["barcode"]?></td>-->
									<!--<td style="width:8% !important"><?php //echo $row["serial_number"]?> </td>-->
								<td style="white-space: nowrap;">&nbsp;<?php echo $row["brand"]?></td>
								<td style="white-space: nowrap;" class="center"><?php echo $row["cat"]?></td>
								<td style="white-space: nowrap;" class="center"><?php echo $row["model"]?></td>
								<td style="white-space: nowrap;" class="center"><?php echo $row["measure"]?></td>
								<td style="white-space: nowrap;" class="center"><?php echo $row["qty"]?></td>
									<!-- <td class="center">
										<?php //if($row["status"] == 1){?>
										<span class="label label-sm label-success"><?php //echo $tr->translate("ACTIVE");?> </span>
										<?php //}else{?>
										<span class="label label-sm label-danger"><?php //echo $tr->translate("DEACTIVE");?> </span>
										<?php //}?>
									</td> -->
							</tr>
						  <?php }?> 
		                </tbody>
		           </table>
		            <br>
		             
		              <br>
		            <table align="center" width="100%" >
						   <tbody>
						   <tr style="font-size: 11px;">
						        <td style="width:20%;text-align:center;font-size:13px; font-family:'Khmer OS Muol Light'">អនុម័តដោយ</td>
						        <td></td>
								<td style="width:20%;text-align:center;font-size:13px; font-family:'Khmer OS Muol Light'">ត្រួតពិនិត្យដោយ</td>
								<td></td>
								<td style="width:20%;text-align:center;font-size:13px; font-family:'Khmer OS Muol Light'">រៀបចំដោយ</td>
						   
						   </tr>
						    <tr style="font-size: 11px; height: 55px;">
						        <td valign="bottom" style="width:20%;text-align:center; border-bottom:1px solid #000;  font-family:'Khmer MEF2'; white-space: nowrap;"></td>
						        <td></td>
						        <td valign="bottom" style="width:20%;text-align:center; border-bottom:1px solid #000; font-family:'Khmer MEF2';white-space: nowrap;"></td>
						        <td></td>
						        <td valign="bottom" style="width:20%;text-align:center; border-bottom:1px solid #000; font-family:'Khmer MEF2';white-space: nowrap;"></td>
						   </tr>

						</tbody>
					</table>
					
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=document.getElementById('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    //hideDialog();
}

/*var currentTime = new Date();
var month = currentTime.getMonth() + 1;
var day = currentTime.getDate();
var year = currentTime.getFullYear();
	var date =(year + "-" + month + "-" + day );

var start_date = $('#start_date').val();
var end_date =$('#end_date').val();

if(end_date!="" | start_date!=""){
    start_date = $('#start_date').val();
	end_date =$('#end_date').val();
	
}else{
	start_date = $('#start_date').val(date);
	end_date = $('#end_date').val(date);
}*/

<?php //$url_item_filter =  $this->url(array('module'=>'report','controller'=>'index','action'=>'get-item-filter')); ?>
/*function getProductFilter(){
	var location_id=$("#LocationId").val();
	var branch_id = $('#branch_id').val();
	var category_id = $('#category_id').val();
		$.ajax({
			url:"<?php //echo $url_item_filter;?>",
			type:"post",
			data:{'category_id':category_id,'branch_id':branch_id,'location_id':location_id},
			success: function(data){
				items = $.parseJSON(data);
				if(items){
					 $('#item').empty();
					 $('#item').val('').trigger("liszt:updated");
					 $('#item').append($("<option></option>").attr("value","").text("Please Select Item"));
					 for (var index = 1 ; index <= items.length; index++) {
							$('#item').append($("<option></option>").attr("value",items[index-1]['pro_id']).text(items[index-1]['item_code'] + items[index-1]['item_name'])); 
							$("select#item").find("option#items[index-1]['pro_id']").attr("selected", true);
					 }           
					$('#item').val('').trigger("liszt:updated");
				}else{
					 $('#item').empty();
					 $('#item').val('').trigger("liszt:updated");
						 $('#item').append($("<option></option>").attr("value","").text("No Items Result!"));
						 $('#item').val('').trigger("liszt:updated");
				}
			},
			error:function(){
			}
		});
	}*/
</script>
