<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$db = new Purchase_Model_DbTable_DbPriceCompare();
$total=0;
$vat=0;
?>
<title><?php echo $tr->translate("MAKE_PURCHASE");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("MAKE_PURCHASE");?>
				</div>
						<div class="btn-group pull-right">
							 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
							   Actions <i class="fa fa-angle-down"></i>
							 </button>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a href="#" onclick="doPrint();">
											<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
										</a>
									</li>
									<li>
										<a href="javascript:;"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
									</li>
									
								</ul>
					</div>
			</div>
            <div class="portlet-body form frmfilter">
					<div style="clear:both;"></div>	
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 20px;font-size: 9px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px;}
		th{padding: 5px;}
		ul.pur_info li{line-height:18px; 
				font-weight: normal !important;}
		ul.pur_info li strong{font-weight: bold;}
       .hover:hover{background: #ccc;}
	   .center{text-align:center;}
	</style>
	<form class="form-horizontal" id="a" enctype="multipart/form-data" method="post">
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody>
						<tr>
								<td width="20%" valign="middle"><img src="<?php echo $this->baseUrl();?>/images/logo/<?php echo $this->title_reprot["logo"]?>"></td>
								<td width="60%" valign="top" style="line-height:30px">
									<ul>
										<li style="text-align:center; font-size:20px; font-family:'Khmer OS Muol Light'"><?php echo $this->title_reprot["title_report_kh"]?></li>
										<li style="text-align:center; font-size:18px; font-family:serif,header-font; font-weight:600;"><?php echo $this->title_reprot["title_report_en"]?></li>
										<li style="text-align:center; font-size:18px; margin-top:25px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("MAKE_PURCHASE");?></li>
									</ul>
								</td>
								<td width="20%"></td>
							</tr> 
		                <tr>
		                	<td colspan="3" valign="top">
		                		<table width="100%" cellpadding="0" cellspacing="0" >
		                			<tbody>
		                			<tr>
		                				<td style="font-size: 11px;">
		                				    <span style="white-space: nowrap;"><?php //echo $tr->translate("ADDRESS_COMPANY");?></span>
		                					<br><?php //echo $tr->translate("TEL_COMPANY");?> 
		                				</td>
		                				<td ></td>
		                				<td width="65%"></td>
		                			</tr>
		                			<tr>
								<td width="20%" valign="bottom">
									<table width="100%" style="font-size: 12px; !important">
										<tr>
											<td style="text-align: left; white-space:nowrap;"><?php echo $tr->translate("PLAN");?> </td>
											<td style="text-align: right; white-space:nowrap;">:</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo $this->product[0]['plan'];?></td>
										</tr>
										<tr>
											<td style="text-align: left; white-space:nowrap;"><?php echo $tr->translate("NUMBER_REQUEST");?> </td>
											<td style="text-align: right; white-space:nowrap;">:</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo $this->product[0]['number_request'];?></td>
										</tr>
										
										<tr>
											<td style="text-align: left;white-space:nowrap;"><?php echo $tr->translate("DATE_REQUEST_WORK_SPACE");?> </td>
											<td style="text-align: right; white-space:nowrap;">:</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo date("d-M-Y",strtotime($this->product[0]['date_from_work_space']));?></td>
										</tr>
									</table>
								</td>
								<td width="60%" valign="bottom">
									
								</td>
								<td width="20%" style="text-align: right;font-size: 12px;">
									<table width="100%" style="font-size: 12px; !important">
										<tr>
											<td style="text-align: right; white-space:nowrap;"><?php echo $tr->translate("COMPARE_PRICE_CODE");?> :</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo $this->product[0]['c_code'];?> </td>
										</tr>
										<tr>
											<td style="text-align: right; white-space:nowrap;"><?php echo $tr->translate("BRANCH_NAME");?> :</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo $this->product[0]['branch'];?></td>
										</tr>
										<tr>
											<td style="text-align: right; white-space:nowrap;"><?php echo $tr->translate("REQUEST_NO");?> :</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo $this->product[0]['re_code'];?></td>
										</tr>
										<tr>
											<td style="text-align: right;white-space:nowrap;"><?php echo $tr->translate("REQUEST_DATE");?> :</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo date("d-M-Y",strtotime($this->product[0]['date_request']));?></td>
										</tr>
									</table>
									<!--<ul class='pur_info'>
			                					<li style="text-align: left;"><strong><?php echo $tr->translate("BRANCH_NAME");?> : </strong><?php echo $this->product[0]['branch'];?></li>
			                					<li style="text-align: right;"><strong><?php echo $tr->translate("REQUEST_NO");?> : </strong><?php echo $this->product[0]['re_code'];?></li>
			                					<li style="text-align: right;"><strong><?php echo $tr->translate("REQUEST_DATE");?> : </strong><?php echo date("d-M-Y",strtotime($this->product[0]['date_request']));?></li>
												<li style="text-align: left;"><strong><?php echo $tr->translate("PEDDING");?> : </strong><?php echo $this->product[0]['pedding'];?></li>
		                						<li style="text-align: left;"><strong><?php echo $tr->translate("PURCHASE_STATUS");?> : </strong><?php echo $this->product[0]['status'];?></li>
		                			</ul>-->
								</td>
							</tr> 
				                </tbody></table>
				              </td>
				           </tr>   
		            </tbody></table>
		        </td>
		    </tr>
		    <tr>
		    	<td id="exportExcel"><br />
		             <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
		                 <tbody>
						 <tr style="background:#ccc">
						 <th rowspan="3"  align="center" class="center"><?php echo $tr->translate("NUM");?></td>
							<th rowspan="3"  align="center" class="center"><?php echo $tr->translate("ITEM_DESCRIPTION");?></td>
							<th rowspan="3" class="center"><?php echo $tr->translate("QTY");?></th>
							<th rowspan="3" class="center"><?php echo $tr->translate("MEASURE");?></th>
							<?php foreach($this->su_id as $key => $rss){ $i = $key+1; ?>
							<th class="center" colspan="3">Quaotation <?php echo $db->integerToRoman($i);?> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;VAT (<?php if($rss["is_vat"]==1){ echo "10%";}else{echo 0;}?>)</th>
							<?php }?>
							<!--<th colspan="3" class="center"><?php echo $tr->translate("QUATATION_I");?></th>
							<th colspan="3" class="center"><?php echo $tr->translate("QUATATION_II");?></th>
							<th colspan="3" class="center"><?php echo $tr->translate("QUATATION_III");?></th>
							<th colspan="3"class="center"><?php echo $tr->translate("QUATATION_IV");?></th>-->
						</tr>
						<tr style="background:#ccc">
							<?php foreach($this->su_id as $key => $rss){ $i = $key+1; ?>
								<th colspan="3"  style=" line-height:17px;" class="center"><?php echo $rss["v_name"]?><br /><?php echo $rss["v_phone"]?></th>
							<?php }?>
						</tr>
						<tr style="background:#ccc">
							<?php foreach($this->su_id as $key => $rss){ $i = $key+1; ?>
								<th style="white-space:nowrap;">&nbsp;<?php echo $tr->translate("UNIT_PRICE_MEASURE");?></th>
								<th style="white-space:nowrap;">&nbsp;<?php echo $tr->translate("BRAND");?></th>
								<th style="white-space:nowrap;" class="center"><?php echo $tr->translate("PRODUCT_FROM");?></th>
							<?php }?>
						</tr>
		                <?php 
							$grand_total = 0;
							$total_vat =0;
							foreach($this->product as $key => $rs){$count=count($this->product); $i= $key+1; $index= $key+1;
						?>
						<tr style="line-height:3០px;">
							<td style="white-space:nowrap; width:3%" class="center"><?php echo $i;?></td>
							<td style="white-space:nowrap;">&nbsp;&nbsp;<?php echo $rs["item_name"];?></td>
							<td style="white-space:nowrap;">&nbsp;&nbsp;<?php echo number_format($rs["qty"],2);?></td>
							<td style="white-space:nowrap;">&nbsp;&nbsp;<?php echo $rs["measure"];?></td>
							<?php 
								$product = $db->getProCompare($this->id,$rs["id"]);
								foreach( $product as $key => $rss){ 
									if($rss["is_check"]==1){
										$check = 'checked="checked"';
										$color = "background:#f96;";
										$vat = (($rs["qty"] * $rss["price"])*  $rss["vat"])/100;
										$grand_total = $grand_total + ($rs["qty"] * $rss["price"])+$vat;
										$total = $total + ($rs["qty"] * $rss["price"]);
										$total_vat = $total_vat + $vat;
										
									}else{
										$check = '';
										$color="";
									}
									$j = $key+1;
							?>
								<!--<td style="white-space:nowrap;" class="center"><span style="padding:5px 15px; "><?php //echo $rss["price"]?></span><span style="margin-top:10px"><input type="checkbox"  value="1" <?php echo $check;?> name="checkbox_<?php echo $i?>_<?php echo $j;?>"/></span></td>-->
								<td style="white-space:nowrap; <?php echo $color;?>">&nbsp;&nbsp;$<span style="float:right;"><?php echo number_format($rss["price"],2); ?></span>&nbsp;&nbsp;</td>
								<td style="white-space:nowrap;">&nbsp;</td>
								<td style="white-space:nowrap;">&nbsp;</td>
							<?php 
							} ?>
						</tr>
							<?php } ?>
							
						<?php if($count<8){
							$loop = 8 - $count;
							for($i=1;$i<=$loop;$i++){
						?>
								<tr class='hover' style="border:1px solid #000;">
							   <td align="center">&nbsp;<?php echo $index+$i?></td>
							   <td style="white-space: nowrap;">&nbsp;</td>
							   <td style="white-space: nowrap;">&nbsp;</td>
							   <td style="white-space: nowrap;">&nbsp;</td>
							   <td>&nbsp;</td>
							   <td>&nbsp;</td>
							   <td>&nbsp;</td>
							   <td>&nbsp;</td>
							   <td align="center">&nbsp;</td>
							   <td style="white-space: nowrap;">&nbsp;</td>
							   <td style="white-space: nowrap;">&nbsp;</td>
							   <td style="white-space: nowrap;">&nbsp;</td>
							   <td>&nbsp;</td>
							   <td>&nbsp;</td>
							   <td>&nbsp;</td>
							   <td>&nbsp;</td>
							</tr>
						<?php 
								
							}
						}
						?>
						<tr>
							<td  colspan="12" style="text-align:right;border-top:1px solid #000;border-left:1px solid #fff;border-bottom:1px solid #fff;"></td>
							<td colspan="2" style="text-align:right;"><?php echo $tr->translate("TOTAL");?>&nbsp;&nbsp;</td>
							<td colspan="2">&nbsp;&nbsp;$<span style="float:right;"><?php echo number_format($total,2);?></span></td>
						</tr>
						
						<tr>
							<td  colspan="12" style="text-align:right;border-top:1px solid #000;border-left:1px solid #fff;border-bottom:1px solid #fff;"></td>
							<td colspan="2" style="text-align:right;"><?php echo $tr->translate("TAX");?>&nbsp;&nbsp;</td>
							<td colspan="2">&nbsp;&nbsp;$<span style="float:right;"><?php echo number_format($total_vat,2);?></span></td>
						</tr>
						<tr>
							<td  colspan="12" style="text-align:right;border-top:1px solid #000;border-left:1px solid #fff;border-bottom:1px solid #fff;"></td>
							<td colspan="2" style="text-align:right;"><?php echo $tr->translate("GRAND_TOTAL");?>&nbsp;&nbsp;</td>
							<td colspan="2">&nbsp;&nbsp;$<span style="float:right;"><?php echo number_format($grand_total,2);?></span></td>
						</tr>
		                </tbody>
		           </table>
				   <br />
				   
		    		</td>
		    	</tr>
				<tr>
					<td>
					<br />
						<div class="form-group">
							<div  class="col-md-12 col-md-offset-4 col-md-8">
								<a href="<?php echo $this->baseUrl();?>/purchase/makepurchase/"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
								<button type="submit" id="save_close" name="save_close" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<!--<button type="submit" name="save_print" class="btn btn-primary"><i class="fa fa-print"></i> <?php echo $tr->translate("SAVE_PRINT")?></button>-->
							</div>
						</div>
					</td>
				</tr>
			</tbody>
		</table>
		</form>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=document.getElementById('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
}
$(document).ready(function () {
    
});
</script>
