<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form_sale;
	$url_submit = $this->url(array('module'=>'purchase','controller'=>'payment','action'=>'add'));
	$url_cancel = $this->url(array('module'=>'purchase','controller'=>'payment','action'=>'index'));
	$url_new = $this->url(array('module'=>'purchase','controller'=>'payment','action'=>'add'));
?>
<title><?php echo $tr->translate("ADD_PAYMENT_ORDER_LETTER");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("ADD_PAYMENT_ORDER_LETTER")?>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="frm a" action="<?php echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post">
					<div class="form-body" style="background:#fbf9f9;">
						<div class="form-group">
							<label class="control-label col-md-2"><?php //echo $tr->translate("PAYMENT_METHOD");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									
								</div>
							</div>
							<label class="control-label col-md-2"> <?php echo $tr->translate("POL_NUMBER");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("payment_number");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("PAYMENT_METHOD");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<select name="payment_method" id="payment_method" onchange="checkControll();" class="form-control select2me">
										<option value="1">	<?php echo $tr->translate("PAYMENT_BY_SUPLLIER")?></option>
										<option value="2"><?php echo $tr->translate("PAYMENT_BY_INVOICE")?></option>
									</select>
								</div>
							</div>
							<label class="control-label col-md-2"> <?php echo $tr->translate("VENDOR_NAME");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("customer_id");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("INVOICE_NO");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('invoice_id');?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("EXSPENSE_DATE");?><span class="required">
							*</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right"><i class="fa fa-calendar"></i>
								<?php echo $form->getElement("expense_date");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("PAYMENT_TYPE");?><span class="required">
							*</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("payment_name");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("RECEIVER_NAME");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("holder_name"); ?>
								</div>
							</div>
							
							
						</div>
						<div class="form-group">
							
							
							<label class="control-label col-md-2"><?php echo $tr->translate("REMARK");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("remark");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("BANK_ACCOUNT_NUM");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("acc_name"); ?>
								</div>
							</div>
					    </div>
						
						<div class="portlet-body">
							<table class="table table-striped table-bordered table-hover" id="table_order" style="font-size:12px;">
								<tr height="33px">
									<th><?php //echo $tr->translate("DEL");?></th>
									<th><?php echo $tr->translate("NUM");?></th>
									<th style="white-space:nowrap;"><?php echo $tr->translate("INVOICE_NO");?></th>
									<th><?php echo $tr->translate("INVOICE_DATE");?></th>
									<th><?php echo $tr->translate("RECEIVE_INVOICE_FROM_STOCK_DATE");?></th>
									<th><?php echo $tr->translate("RECEIVE_INVOICE_DATE");?></th>
									<th><?php echo $tr->translate("GRAND_TOTAL");?></th>
									<th><?php echo $tr->translate("TOTAL_PAYMENT");?></th>
									<th><?php echo $tr->translate("BALANCE");?></th>
							</tr>
						 </table>
						 <div style="opacity: 0;">
						 <input type="text" required="required" id="identity" name="identity" />
						 </div>
					</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php //echo $tr->translate("PAYMENT_METHOD");?><span class="required">
								 </span>
							</label>
							<label class="control-label col-md-2">
							</label>
							<div class="col-md-2">
								<div class="input-icon right">
								</div>
							</div>
								<label class="control-label col-md-2"><?php echo $tr->translate("TOTAL");?><span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon left"><i class="fa">$</i>
								<input type="text" style="text-align:right;" class="form-control" readOnly="readOnly" name="total" id="total" />
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right"></div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("TAX");?>
							</label>
							<div class="col-md-4">
								<div class="input-icon left"><i class="fa">$</i>
									<input type="text" style="text-align:right;" readOnly="readOnly" class="form-control" name="total_vat" id="total_vat" />
									<?php echo $form->getElement("paid");?>
								</div>
							</div>	
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php //echo $tr->translate("ពន្ធ");?><span class="required">
							</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<?php //echo $form->getElement("total_tax");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("GRAND_TOTAL");?> 
							</label>
							<div class="col-md-4">
								<div class="input-icon left"><i class="fa">$</i>
								<?php echo $form->getElement("all_total");?>
								<?php echo $form->getElement("balance");?>
								</div>
							</div>
						</div>
						
						<div class="form-group">
							<div class="col-md-12 col-md-offset-4 col-md-8">
								<a href="<?php echo $this->baseUrl();?>/purchase/payment/"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("GO_BACK")?></button></a>
								<button type="submit" id="save_close" name="saveclose" class="btn btn-primary" ><i class="fa fa-close"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<!--<button type="submit" value="btnsavenew" name="btnsavenew" class="btn blue btn-block btn-lg"><i class="fa fa-save"></i> <?php //echo $tr->translate("SAVE_NEW")?> </button>-->
							</div>
						</div>
						
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<!-- end new product -->
<script>
$(document).ready(function () {
    
});
function paidtotal(type){//1=dollar,2=riel
	doRemain();
}
function checkpayment(){
	payment_id = $("#payment_name").val();
	//alert(payment_id);
	if(payment_id==2){
		$( "#holder_name" ).attr( "readOnly",false );
		$( "#acc_name" ).attr( "readOnly", true );
	}else if(payment_id==9){
		$( "#holder_name" ).attr( "readOnly",false );
		$( "#acc_name" ).attr( "readOnly", false );
	}else{
		$( "#holder_name" ).attr( "readOnly",true );
		$( "#acc_name" ).attr( "readOnly", true );
	}
}
function checkControll(){
	$("#table_order").html("");
	$('#balance').val(0);$('#all_total').val(0);
	$('#total').val(0);$('#total_vat').val(0);//$('#paid').val(0);
	payment_method = $("#payment_method").val();
	if(payment_method==1){
		$( "#invoice_id" ).attr( "readOnly", true );
		
		$( "#customer_id" ).attr( "readOnly", false );
	}else{
		$( "#customer_id" ).attr( "readOnly", true );
		$( "#invoice_id" ).attr( "readOnly", false );
    }
}
<?php $urlgetinvoice =  $this->url(array('module'=>'','controller'=>'ajax','action'=>'getinvoice')); ?>
function getInvoice(type){
	if(type==1){
		post_id=$("#customer_id").val();
		$( "#invoice_id" ).attr( "readonly", true );
		$( "#customer_id" ).attr( "readOnly", false );
	}else{
		post_id=$("#invoice_id").val();
		$( "#customer_id" ).attr( "readonly", true );
		$( "#invoice_id" ).attr( "readOnly", false );
	}
	$.ajax({
			url:"<?php echo $urlgetinvoice;?>",
			type:"post",
			data:{'post_id':post_id,'type_id':type},
			success: function(data){
				//alert(data);
				$("#table_order").html("");
				template='<tr height="33px">';
					template+='<th><?php echo $tr->translate("");?></th>';
					template+='<th><?php echo $tr->translate("NUM");?></th>';
					template+='<th><?php echo $tr->translate("INVOICE_NO");?></th>';
					template+='<th style="white-space:nowrap;"><?php echo $tr->translate("INVOICE_DATE");?></th>';
					template+='<th style="white-space:nowrap;"><?php echo $tr->translate("RECEIVE_INVOICE_FROM_STOCK_DATE");?></th>';
					template+='<th style="white-space:nowrap;"><?php echo $tr->translate("RECEIVE_INVOICE_DATE");?></th>';
					
					template+='<th><?php echo $tr->translate("TOTAL");?></th>';
					//template+='<th><?php echo $tr->translate("បញ្ចុះតម្លៃ");?></th>';
					template+='<th><?php echo $tr->translate("TAX");?></th>';
					template+='<th><?php echo $tr->translate("GRAND_TOTAL");?></th>';
				template+='</tr>';
				
				$('#identity').val("");
				data = $.parseJSON(data);
				
				
				for(i=0;i<data.length;i++){
					if(i==0){
						$("#customer_id").val(data[i].vendor_id);
						$("#customer_id").select2();
						getVendore(data[i].vendor_id)
					}
					stock_date='';
					stock_dat = data[i].receive_invoice_date;
					//alert(stock_dat);
					if(stock_dat!="" && stock_dat!="null" && stock_dat!=null){
						stock_date = formatDateToString(new Date(stock_dat));
					}
					index=i+1;
					template+='<tr style="height:30px;">';
			            //template+='<td ><img onClick="deleteRecord('+index+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
						 template+='<td style="vertical-align: middle;text-align: center;"><input type="checkbox" onClick="checkedRow('+index+')" name="checkbox_'+index+'" id="checkbox_'+index+'" /></td>';
						template+='<td >'+index+'</td>';
						template+='<td >'+data[i].invoice_no+'</td>';
						template+='<td >'+formatDateToString(new Date(data[i].invoice_date))+'<input type="hidden" value='+data[i].id+' id="invoice_no'+index+'" name="invoice_no'+index+'"/></td>';
						template+='<td >'+stock_date+'<input type="hidden" value='+data[i].sub_total+' id="total'+index+'" name="total'+index+'"/><input type="hidden" value='+data[i].total_vat+' id="total_vat'+index+'" name="total_vat'+index+'"/></td>';
						template+='<td >'+formatDateToString(new Date(data[i].invoice_controlling_date))+'<input type="hidden" value='+data[i].discount_after+' id="discount'+index+'" name="discount'+index+'"/></td>';
						template+='<td ><span style="margin-right:5px;">$</span>'+data[i].sub_total+'<input type="hidden" value='+data[i].grand_total_after+' id="subtotal'+index+'" name="subtotal'+index+'"/></td>';
						template+='<td ><span style="margin-right:5px;"></span>'+data[i].vat+'%<input type="hidden" name="vat'+index+'" value="'+data[i].vat+'" id="vat'+index+'" /><input type="hidden" value="0" id="paid_amount'+index+'" name="paid_amount'+index+'"/></td>';
						template+='<td ><span style="margin-right:5px;">$</span>'+data[i].grand_total_after+'<input type="hidden" value='+data[i].grand_total_after+' id="balance_after'+index+'" name="balance_after'+index+'"/></td>';
				    template+="</tr>";
					
					/*if($('#identity').val()!="") {
						var identity = $('#identity').val();
						$('#identity').val(identity+','+index);
					} else {$('#identity').val(index);}*/
				}
				$('#table_order').append(template);
				if(data.length>0){netTotal();}else{$('#balance').val(0);$('#total').val(0);$('#total_vat').val(0);$('#all_total').val(0);$('#paid').val(0); alert("No invoice to make payment");}
				
			},
			error:function(e){
				alert("error"+e);
			}
		});	
}

<?php $url_vendor =  $this->url(array('module'=>'','controller'=>'ajax','action'=>'getvendor')); ?>

function getVendore(id){
	$.ajax({
			url:"<?php echo $url_vendor;?>",
			type:"post",
			data:{'post_id':post_id},
			success: function(data){
				//alert(data);
				data = $.parseJSON(data);
				$("#holder_name").val(data.bank_name);
				$("#acc_name").val(data.bank_no);
			},
			error:function(e){
				alert("error"+e);
			}
		});	
}
function checkedRow(index){
	var ids =$('#identity').val();
		var arrays = ids.split(',');
		for(var i=0;i<arrays.length;i++) {//calculate record row
			if(arrays[i] == index) arrays.splice(i,1);
			if($('#checkbox_'+index).attr('checked')){
				if($("#identity").val()!="") {
					$("#identity").val(ids+','+index);
				}else { 
					$("#identity").val(index);
				}
				
			 }else{
				var strings = arrays.join(',');
				$('#identity').val(strings);
			}
		}
		
		netTotal();
}
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	$("#row_order_"+index).remove();
	netTotal();
}
function netTotal() {//use
	var subtotal=0;
	var paid = 0;
	total = 0;
	total_vat =0;
	discount=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	for(var n = 0; n < rowIDArray.length; n++) {
		//subtotal += Number($('#subtotal'+rowIDArray[n]).val());
		//paid +=Number($('#paid_amount'+rowIDArray[n]).val());
		//discount +=Number($('#discount'+rowIDArray[n]).val());
		subtotal += Number($('#balance_after'+rowIDArray[n]).val());
		total += Number($('#total'+rowIDArray[n]).val());
		total_vat += Number($('#total_vat'+rowIDArray[n]).val());
	}
	//var alltotal = Number(subtotal - discount).toFixed(2);
	$('#all_total').val(subtotal.toFixed(2));
	$('#total').val(total.toFixed(2));
	$('#total_vat').val(total_vat.toFixed(2));
	$('#paid').val(0);
	//$('#paid').val(0);
	doRemain();
}
function doRemain() {
	var all_total = Number($('#all_total').val());
	var paid = Number($('#paid').val());
	if(paid > all_total){
		var paid = $('#paid').val(all_total);
		 $('#remain').val(0);
   }else{
	   remain = all_total-paid;
	   $('#balance').val(remain.toFixed(2));
	}	
}
function getCustomerInfo(){
	v_id = $("#v_name").val();
	if(v_id==-1){
		$('#dialogvendor').modal('show');
	}
}

</script>	