<?php 					
	$url_new = $this->url(array('module'=>'purchase','controller'=>'index','action'=>'add',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
	//print_r($this->rs);
?>
<title><?php echo $tr->translate("MENU_PURCHASE_ADVANCE_INDEX");?></title>
<meta charset="utf-8" />
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("MENU_PURCHASE_ADVANCE_INDEX");?>
				</div>
				<!--<a href="<?php echo $url_new;?>" class="btn btn-sm green  pull-right">
					<i class="fa fa-plus"></i>&nbsp;<?php echo $tr->translate("ADD_NEW");?>
				</a>-->
			</div>
			<div class="portlet-body form frmfilter">
				<form method="post" action="<?php echo $formFilter->getAction(); ?>">
					<div class="form-group" style="padding-top: 6px;">
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('text_search');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('branch');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('suppliyer_id');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('po_pedding');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('start_date');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('end_date');?></label>
						<label class="control-label col-md-2">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
						</label>
					</div>			
				</form> 
				<div class="contain_form" style="clear: both;">
					<form name="list"><div style="overflow:scroll; max-height: 450px; overflow-x:hidden;" >
					<table class="collape tablesorter" id="table" width="100%">
						<thead>
							<tr>
								<th class="tdheader"><?php echo  $tr->translate("NUM");?></th>
								<th class="tdheader"><?php echo  $tr->translate("REQUEST_NO");?></th>
								<th class="tdheader"><?php echo  $tr->translate("REQUEST_DATE");?></th>
								<th class="tdheader"><?php echo  $tr->translate("PLAN");?></th>
								<th class="tdheader"><?php echo  $tr->translate("WAREHOUSE");?></th>
								<th class="tdheader"><?php echo  $tr->translate("PURCHASE_NO");?></th>
								<th class="tdheader"><?php echo  $tr->translate("PURCHASE_DATE");?></th>
								<th class="tdheader"><?php echo  $tr->translate("VENDOR_NAME");?></th>
								<!--<th class="tdheader"><?php //echo  $tr->translate("PAID");?></th>
								<th class="tdheader"><?php //echo  $tr->translate("BALANCE");?></th>-->
								<th class="tdheader"><?php echo  $tr->translate("APPROVED_STATUS");?></th>
								<th class="tdheader"><?php echo  $tr->translate("PENDING_STATUS");?></th>
								<!--<th class="tdheader"><?php //echo  $tr->translate("STATUS");?></th>-->
								<th class="tdheader"><?php echo  $tr->translate("USER");?></th>
								<th class="tdheader"><?php echo  $tr->translate("ACTION");?></th>
							</tr>
						</thead>
						<tbody>
							<?php 
							$id = "table";
							$stringPagination = '<script type="text/javascript">
										$(document).ready(function(){
											$("#'.$id.'").tablesorter();
											$("#'.$id.'").tablesorter().tablesorterPager({container: $("#pagination_'.$id.'"),size:15});
											$("#pagedisplay").focus(function(){ this.blur(); 
										   });
										});
								</script>
								<div id="pagination_'.$id.'" class="pager" >
											<form >
												<table  style="width: 200px;"><tr>
												<td><img src="'.BASE_URL.'/images/first.gif" class="first"/></td>
												<td><img src="'.BASE_URL.'/images/previous.gif" class="prev"/></td>
												<td><input type="text" class="pagedisplay"/></td>
												<td><img src="'.BASE_URL.'/images/next.gif" class="next"/></td>
												<td><img src="'.BASE_URL.'/images/last.gif" class="last"/></td>
												<td><select class="pagesize" >
													<option selected="selected"  value="10">10</option>
													<option value="20">20</option>
													<option value="30">30</option>
													<option value="40">40</option>
													<option value="50">50</option>
													<option value="60">60</option>
													<option value="70">70</option>
													<option value="80">80</option>
													<option value="90">90</option>
													<option value="100">100</option>
													</select>
												</td>
												</tr>
												</table>
											</form>
									</div>	';
							$footer="";
							if(!empty($this->rs)){
								foreach ($this->rs as $key=>$rs){
									
									$edit_status = '';
									$receive_status ="";
									
									if($rs["is_purchase_order"]==1 AND $rs["is_recieved"]==0){
										$receive_status='';
									}elseif($rs["is_purchase_order"]==1 AND $rs["is_completed"]==1){
										$receive_status ="style='pointer-events: none;cursor: default;color: #ccc;'";
									}
									if($rs["approved"]==1 OR $rs["approved"]==2){
										$edit_status ="style='pointer-events: none;cursor: default;color: #ccc;'";
									}
									
							?>
								<tr class="normal">
									<td class="items-no"><?php echo $key+1;?></td>
									<td class="items"><?php echo $rs["re_code"];?></td>
									<td class="items"><?php echo date('d-M-Y',strtotime($rs["date_request"]));?></td>
									<td class="items"><?php echo $rs["plan"];?></td>
									<td class="items"><?php echo $rs["branch_name"];?></td>
									<td class="items"><?php echo $rs["order_number"];?></td>
									<td class="items"><?php echo date('d-M-Y',strtotime($rs["date_order"]));?></td>
									<td class="items"><?php echo $rs["vendor_name"];?></td>
									<!--<td class="items"><?php //echo $rs["curr_name"];?>&nbsp;<?php //echo $rs["paid"];?></td>
									<td class="items"><?php //echo $rs["curr_name"];?>&nbsp;<?php //echo $rs["balance"];?></td>-->
									<td class="items"><?php echo $rs["purchase_status"];?></td>
									<td class="items"><?php echo $rs["pedding_status"];?></td>
									<td class="items"><?php echo $rs["user_name"];?></td>
									<td class="items-no" style="white-space: nowrap;">
										<!--<a <?php echo $edit_status; ?> href="<?php echo $this->baseUrl();?>/purchase/index/edit/id/<?php echo $rs["id"]?>"><?php echo  $tr->translate("EDIT");?></a> | 
										<a target="_blank" href="<?php echo $this->baseUrl();?>/purchase/index/purproductdetail/id/<?php echo $rs["id"]?>"><?php echo  $tr->translate("PRINT");?></a> | -->
										<a target="_blank" <?php echo $receive_status; ?> href="<?php echo $this->baseUrl();?>/purchase/receive/add/id/<?php echo $rs["id"]?>"><?php echo  $tr->translate("RECIEVE_PO");?></a>​ | 
										<a onclick="popup(<?php echo  $rs["id"];?>,<?php echo  $rs["re_id"];?>)" <?php echo $receive_status; ?> <?php //echo $receive_status; ?> href="#"><?php echo  $tr->translate("CLOSE_RECIEVE_PO");?></a>
									</td>
								</tr>
							<?php $counter='<strong style="float:right;padding:5px">Number of record(s): '.count($this->rs).'</strong>'; 
								$footer = '<div class="footer_list">'.$stringPagination.$counter.'</div>';
							}}?>
						</tbody>
					</table></div></form><?php echo $footer?>
						<?php //echo $this->list; ?>
			    </div>
		   </div>
		</div>
	</div>
</div>
<!--<?php //echo $this->baseUrl();?>/purchase/receive/add/id/<?php echo $rs["id"]?>-->

<div id="Product" class="modal fade" tabindex="-1" data-width="1200">
    <div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">   
				<div class="row">
					<div class="col-md-12">
						<div class="portlet box blue">
							<div class="portlet-title">
								<div class="caption">
									<i class="icon-home"></i><?php echo $tr->translate("CLOSE_RECIEVE_PO");?>
								</div>
								<div class="caption pull-right">
									<a href="<?php echo $url_new;?>" >
										 <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
									</a>
								</div>
							</div>
							<div class="portlet-body form">
								<form id="frmbrand" name="frmcustomer" class="form-horizontal" enctype="multipart/form-data" method="post">
								<table class="table table-striped table-bordered table-hover" id="table_order" style="font-size:12px;">
								</table>
								<input type="hidden" name="po_id" id="po_id" /> 
								<input type="hidden" name="re_id" id="re_id" /> 
								<div class="form-body">
									<div class="form-group">
										<div  class="col-md-12 col-md-offset-4 col-md-8">
											<button type="button" name="btnsavenew" onclick="submits();" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("CLOSE_RECIEVE_PO")?> </button>
										</div>
									</div>
								</div>
								</form>
							</div>
						</div>
					</div>
				</div>																												
			</div>
        </div>
    </div>
 </div>
 
 <script>
	$( document ).ready(function() {

	});
	function popup(id,re_id){
		//alert(id);
		$("#po_id").val(id);
		$("#re_id").val(re_id);
		item(id);
		$('#Product').modal();
	}
	<?php $url_submit =  $this->url(array('module'=>'','controller'=>'ajax','action'=>'closereceive')); ?>
	function submits(){
		id = $("#po_id").val();
		re_id = $("#re_id").val();
		$.ajax({
			url: "<?php echo $url_submit;?>",
			type: "post",
			data: {'id':id,"re_id":re_id},
			success: function(data){
				//alert(data);
				location.reload();
			},
			error:function(err){
				alert("faile insert");
			   
			}
		});
	}
	
	<?php $url_item =  $this->url(array('module'=>'','controller'=>'ajax','action'=>'get-purchase-item')); ?>
	function item(id){
		//alert(id);
		$('#table_order').html('');
		template='';
		index5=0;
		$.ajax({
			url: "<?php echo $url_item;?>",
			cache: false,
			type: "post",
			data: {'id':id},
			success: function(data){
				//alert(data);
				rs = $.parseJSON(data);
				template+='<tr id="row_order_'+index5+'" style="height:33px;">';
					template+='<th  width="1%"><?php echo $tr->translate("NUM");?></th>';
					template+='<th width="30%"><?php echo $tr->translate("ITEM_CODE");?></th>';
					template+='<th ><?php echo $tr->translate("ITEM_NAME");?></th>';
					template+='<th ><?php echo $tr->translate("QTY");?></th>';
					template+='<th  width="5%"><?php echo $tr->translate("MEASURE");?></th>';
					//template+='<td ></td>';
					template+="</tr>";
				for(i=0;i<=rs.length;i++){
					index5++;
					//alert(rs[i]);
					
					
					template+='<tr id="row_order_'+index5+'" style="height:33px;">';
					template+='<td  width="1%">'+index5+'</td>';
					template+='<td width="30%">'+rs[i].item_code+'</td>';
					template+='<td >'+rs[i].item_name+'</td>';
					template+='<td >'+rs[i].qty_after+'</td>';
					template+='<td  width="5%">'+rs[i].measure+'</td>';
					//template+='<td ></td>';
					template+="</tr>";
					$('#table_order').html(template);
					
				}
				
			},
			error:function(err){
				alert("faile insert");
			   
			}
		});
	}
</script>