<?php 					
	$url_new = $this->url(array('module'=>'purchase','controller'=>'payment','action'=>'add',));
	$print = $this->url(array('module'=>'purchase','controller'=>'payment','action'=>'print',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
	//print_r($this->rs);
?>
<meta charset="utf-8" />
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("MENU_RECEIVE_POL");?>
				</div>
				<!--<a href="<?php echo $url_new;?>" class="btn btn-sm green  pull-right">
					<i class="fa fa-plus"></i>&nbsp;<?php echo $tr->translate("ADD_NEW");?>
				</a>-->
			</div>
			<div class="portlet-body form">
				<form method="post" action="">
					<div class="form-group" style="padding-top: 6px;">
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('text_search');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('branch');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('suppliyer_id');?></label>
						<!--<label class="control-label col-md-2"><?php echo $formFilter->getElement('po_invoice_status');?></label>-->
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('start_date');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('end_date');?></label>
						<label class="control-label col-md-2">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
						</label>
					</div>	
				</form> 
					<div class="contain_form" style="clear: both;">
						<?php //echo $this->list; ?>
					</div>
					<div class="contain_form " style="clear: both;">
					<form name="list">
					<div class="table-responsive" >
					<table class="collape tablesorter" id="table" width="100%">
						<thead>
							<tr>
								<th class="tdheader"><?php echo  $tr->translate("NUM");?></th>
								<th style="white-space:nowrap;" class="tdheader"><?php echo  $tr->translate("POL_NUMBER");?></th>
								<th style="white-space:nowrap;" class="tdheader"><?php echo  $tr->translate("POL_DATE");?></th>
								<th style="white-space:nowrap;" class="tdheader"><?php echo  $tr->translate("BRANCH");?></th>
								<th style="white-space:nowrap;" class="tdheader"><?php echo  $tr->translate("SUPPLIER");?></th>
								<th style="white-space:nowrap;" class="tdheader"><?php echo  $tr->translate("PAYMENT_TYPE");?></th>
								<th style="white-space:nowrap;" class="tdheader"><?php echo  $tr->translate("TOTAL");?></th>
								<th style="white-space:nowrap;" class="tdheader"><?php echo  $tr->translate("TAX");?></th>
								<th style="white-space:nowrap;" class="tdheader"><?php echo  $tr->translate("GRAND_TOTAL");?></th>
								<th style="white-space:nowrap;" class="tdheader"><?php echo  $tr->translate("RECEIVER_NAME");?></th>
								<th style="white-space:nowrap;" class="tdheader"><?php echo  $tr->translate("BANK_ACCOUNT");?></th>
								<th style="white-space:nowrap;" class="tdheader"><?php echo  $tr->translate("USER");?></th>
								<th style="white-space:nowrap;" class="tdheader"><?php echo  $tr->translate("DATE_GET_POL");?></th>
								<th style="white-space:nowrap;" class="tdheader"><?php echo  $tr->translate("DATE_PAY_POL");?></th>
								<th style="white-space:nowrap;" class="tdheader"><?php echo  $tr->translate("ACTION");?></th>
							</tr>
						</thead>
						<tbody>
							<?php 
							$id = "table";
							$stringPagination = '<script type="text/javascript">
										$(document).ready(function(){
											$("#'.$id.'").tablesorter();
											$("#'.$id.'").tablesorter().tablesorterPager({container: $("#pagination_'.$id.'"),size:15});
											$("#pagedisplay").focus(function(){ this.blur(); 
										   });
										});
								</script>
								<div id="pagination_'.$id.'" class="pager" >
											<form >
												<table  style="width: 200px;"><tr>
												<td><img src="'.BASE_URL.'/images/first.gif" class="first"/></td>
												<td><img src="'.BASE_URL.'/images/previous.gif" class="prev"/></td>
												<td><input type="text" class="pagedisplay"/></td>
												<td><img src="'.BASE_URL.'/images/next.gif" class="next"/></td>
												<td><img src="'.BASE_URL.'/images/last.gif" class="last"/></td>
												<td><select class="pagesize" >
													<option selected="selected"  value="10">10</option>
													<option value="20">20</option>
													<option value="30">30</option>
													<option value="40">40</option>
													<option value="50">50</option>
													<option value="60">60</option>
													<option value="70">70</option>
													<option value="80">80</option>
													<option value="90">90</option>
													<option value="100">100</option>
													</select>
												</td>
												</tr>
												</table>
											</form>
									</div>	';
							$footer="";
							if(!empty($this->rs)){
								foreach ($this->rs as $key=>$rs){
									
							?>
								<tr class="normal">
									<td class="items-no"><?php echo $key+1;?></td>
									<td class="items"><?php echo $rs["pol_no"];?></td>
									<td style="white-space:nowrap;" class="items"><?php echo date('d-M-Y',strtotime($rs["expense_date"]));?></td>
									<td style="white-space:nowrap;" class="items"><?php echo $rs["branch_name"];?></td>
									<td style="" class="items"><?php echo $rs["customer_name"];?></td>
									<td style="white-space:nowrap;" class="items"><?php echo $rs["payment_name"];?></td>
									<td class="items"><span style="margin-right:5px;">$</span><?php echo number_format($rs["total"]-$rs["vat"],2);?></td>
									<td class="items"><span style="margin-right:5px;">$</span><?php echo number_format($rs["vat"],2);?></td>
									<td class="items"><span style="margin-right:5px;">$</span><?php echo number_format($rs["total"],2);?></td>
									<td style="" class="items"><?php echo $rs["withdraw_name"];?></td>
									<td style="white-space:nowrap;" class="items"><?php echo $rs["bank_acc"];?></td>
									<td style="white-space:nowrap;" class="items"><?php echo $rs["user_name"];?></td>
									<?php if($rs["is_get"]==1){?>
										<td style="white-space:nowrap;" class="items"><?php echo date("d-M-Y",strtotime($rs["get_date"]));?><input style="width:100%" class="date-picker" value="<?php echo $rs["get_date"];?>" type="hidden" name="date_get_<?php echo $key+1;?>" id="date_get_<?php echo $key+1;?>" /></td>
									<?php }else{?>
										<td style="white-space:nowrap;" class="items"><input style="width:100%" class="date-picker" type="text" name="date_get_<?php echo $key+1;?>" id="date_get_<?php echo $key+1;?>" /></td>
									<?php }?>
									<?php if($rs["is_paid"]==1){?>
										<td style="white-space:nowrap;" class="items"><?php echo date("d-M-Y",strtotime($rs["paid_date"]));?><input style="width:100%" value="<?php echo $rs["paid_date"];?>" class="date-picker" type="hidden" name="date_pay_<?php echo $key+1;?>" id="date_pay_<?php echo $key+1;?>" /></td>
									<?php }else{?>
										<td style="white-space:nowrap;" class="items"><input style="width:100%" class="date-picker" type="text" name="date_pay_<?php echo $key+1;?>" id="date_pay_<?php echo $key+1;?>" /></td>
									<?php }?>
									<?php if($rs["is_get"]==1){?>
									<td class="items-no" style="white-space: nowrap;">
										<?php echo  $tr->translate("PAYED");?>
									</td>
									<?php }else{?>
									<td class="items-no" style="white-space: nowrap;">
										<a target="_blank" onClick="polPay(<?php echo $key+1;?>,<?php echo $rs['id'];?>)"><?php echo  $tr->translate("PAY");?></a>
									</td>
									<?php }?>
								</tr>
							<?php $counter='<strong style="float:right;padding:5px">Number of record(s): '.count($this->rs).'</strong>'; 
								$footer = '<div class="footer_list">'.$stringPagination.$counter.'</div>';
							}}?>
						</tbody>
					</table>
					</div></form><?php echo $footer?>
						<?php //echo $this->list; ?>
			    </div>
		   </div>
		</div>
	</div>
</div>

<style>
.overlay {display: none;position: absolute;width: 100vw;height: 100vh;top: 0px;left: 0px;background: #FCFCFC;z-index: 1001;opacity: .95;}
.overlay-load {width: 350px;height: 100px;margin: auto;top: 0px;bottom: 0px;position: absolute;left: 0px;right: 0px;
          text-align: center;
          
           background-repeat: no-repeat;          
}
.overlay-msg{margin-bottom: 10px;bottom: 0px;font-style: italic;color: rgb(19, 19, 19);} 
</style>
<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
			<button class="btn btn-default btn-lg" ><i class="fa fa-spinner fa-spin"></i> Loading</button>
	    </div>
	</div>
</div>	
<script>
	<?php $url_ajax_add =  $this->url(array('module'=>'purchase','controller'=>'payment','action'=>'letpolpay')); ?>
	function loading(){
		document.getElementsByClassName("overlay")[0].style.display="block";
	} 
	function polPay(index,id){
		date_pay = $("#date_pay_"+index).val();
		date_get = $("#date_get_"+index).val();
		if(date_get!=""){
			loading();
			$.ajax({
				url:"<?php echo $url_ajax_add;?>",
				type:"post",
				data:{'id':id,'date_pay':date_pay,'date_get':date_get},
				success: function(data){
						document.getElementsByClassName("overlay")[0].style.display="none";
						window.location.reload(true);
					
				},
				error:function(){
				}
			});
		}else{
			alert("Please Receive POL Before Pay Invoice!");
		}
	}
</script>