<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$brach_name =  $this->branch;
$result = $this->stockin;
//print_r($result);
?>
<?php $formFilter = $this->formFilter; ?>
<title>Purchase Report</title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("STOCK_SUMMARY");?>
				</div>
						<div class="btn-group pull-right">
							 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
							   Actions <i class="fa fa-angle-down"></i>
							 </button>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a href="#" onclick="doPrint();">
											<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
										</a>
									</li>
									<li>
										<a href="javascript:;"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
									</li>
									
								</ul>
					</div>
			</div>
            <div class="portlet-body form frmfilter">
				<form method="post" action="<?php //echo $formFilter->getAction(); ?>">
					<div class="form-group" style="padding-top: 6px;">
						
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('ad_search');?></label>
						<label class="control-label col-md-2">
								<select data-placeholder="Select..." class="form-control select2me " style="text-align: left;" id="add_item" name="add_item" Onchange="getItemOrder();" >
								<?php echo $this->items; ?>
								</select>
						</label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('category');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('suppliyer_id');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('start_date');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('end_date');?></label>
						<label class="control-label col-md-2 pull-right">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
						</label>
					</div><div style="clear:both;"></div>	
				</form> 
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
		<style>
			.style{
				line-height: 20px;font-size: 9px !important;
				font-family: 'Khmer OS Battambang';
			}
			ul{margin: 0;padding:0;}
			table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
			th{padding: 5px;}
			.hover:hover{background: #ccc;}
			.tdborder td{
				border-left:1px solid #000;
				border-right:1px solid #000;
				
			}
		
		</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody><tr>
		                	<td width="20%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logo/<?php echo $this->title_reprot["logo"]?>"></td>
		                	<td width="60%" valign="top">
		                		<ul>
		                			<li style="text-align:center; font-size:13px; font-family:'Khmer MEF2'">របាយការណ៏សម្ភារៈចូលផ្នែក<?php //echo $result[0]["cattegory"]?></li>
		                			<li style="text-align:center; font-size:13px;"><?php echo date("d/m/Y",strtotime($this->start_date));?> ដល់ <?php echo date("d/m/Y",strtotime($this->end_date));?></li>
		                		</ul>
		                	</td>
		                    <td width="20%"></td>
		                </tr> 
		                <tr>
		                	<td colspan="3" valign="top">
		                		<table width="100%" cellpadding="0" cellspacing="0">
		                			<tbody><tr>
		                				<td style="font-size: 11px;">
		                				    <span style="white-space: nowrap;"><?php //echo $tr->translate("ADDRESS_COMPANY");?></span>
		                					<br><?php //echo $tr->translate("TEL_COMPANY");?> 
		                				</td>
		                				<td width="65%"></td>
		                			</tr>
				                </tbody></table>
				              </td>
				           </tr>   
						</tbody>
					</table>
		        </td>
		    </tr>
		    <tr>
		    	<td id="exportExcel">
		            <table  &#8203;="" style="border-collapse:collapse; font-size:10px;" width="100%" cellspacing="0">
		                 <tbody>
						  <?php $num=1; 
			               $total_qty = 0;
						   $total_price =0;
						   $total_amount = 0;
						   if(!empty($this->stockin))foreach ($this->stockin AS $index => $rs){
							   $total_qty =  $total_qty+ $rs["qty_receive"];
							  $total_price =  $total_price+$rs["price"];
							   $total_amount= $total_amount+$rs["sub_total_after"];
						   }
						  ?>
						 <tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:none;">
						   <td align="center" style="white-space: nowrap;text-align:center;">&nbsp;</td>
						   <td style="white-space: nowrap; text-align:center;">&nbsp;</td>
						   <td style="white-space: nowrap;text-align:center;">&nbsp;<?php echo $tr->translate("TOTAL");?></td>
						   <td style="white-space: nowrap;text-align:center;">&nbsp;<?php echo   $total_qty;?></td>
						   <td style="white-space: nowrap;text-align:center;">&nbsp;</td>
						   <td style="white-space: nowrap;text-align:center;">&nbsp;<?php //echo $rs["currency"]?><span style="float:right"><?php echo  $total_price;?></span></td>
						   <td style="white-space: nowrap;text-align:center;">&nbsp;<?php //echo $rs["currency"]?><span style="float:right"><?php echo $total_amount;?></span></td>
						   <td style="white-space: nowrap;text-align:center;">&nbsp;</td>
						   <td style="white-space: nowrap;text-align:center;">&nbsp;</td>
						   <td style="white-space: nowrap;text-align:center;">&nbsp;</td>
						   <td style="white-space: nowrap;text-align:center;">&nbsp;</td>
						   <td>&nbsp;<?php //echo number_format($rs["balance"],2);?></td>
						</tr>
						<tr bgcolor="#ccc" class="style tdborder" align="center" style="font-weight:bold; line-height: 20px;border:1px solid #000; font-size:12px; padding:1px 0px; white-space: nowrap; ">
		                    <td>&nbsp;<?php echo $tr->translate("DATE");?></td>
							<td><?php echo $tr->translate("CODE");?></td>
							<td>&nbsp;<?php echo $tr->translate("ITEM_NAME");?></td>
							<td>&nbsp;<?php echo $tr->translate("QTY");?></td>
							<td width="10%">&nbsp;<?php echo $tr->translate("PACKING");?></td>
							<td><?php echo $tr->translate("U/PRICE");?></td>
							<td><?php echo $tr->translate("AMOUNT");?></td>
							<td>&nbsp;<?php echo $tr->translate("PU_NO");?></td>
							<td>&nbsp;<?php echo $tr->translate("INVOICE_NO");?></td>
							<td>&nbsp;<?php echo $tr->translate("SUPPLIER");?></td>
							<td width="12%">&nbsp;<?php echo $tr->translate("PURCHASER");?></td>
							<td>&nbsp;<?php echo $tr->translate("REMARK");?></td>
		                </tr> 
		                <?php if(!empty($this->stockin))foreach ($this->stockin AS $index => $rs){?>
						<tr class='tdborder row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $rs["date_in"]?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_code"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_name"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["qty_receive"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["measure"];?></td>
						<td style="white-space: nowrap;">&nbsp;<?php echo $rs["currency"]?><span style="float:right;"><?php echo number_format($rs["price"],2);?></span></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["sub_total_after"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["order_number"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["recieve_number"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["supplier"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["purchaser"];?></td>
						   <td>&nbsp;<?php //echo number_format($rs["balance"],2);?></td>
						</tr>
						<?php 
							 
						}?>
		                </tbody>
		           </table>
		            
		              <br>
		              <table align="center" width="100%">
						   <tbody><tr style="font-size: 11px;">
						        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'">យល់ព្រមដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'">ត្រួតពិនិត្យដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'">រៀបចំដោយ</th>
						   </tr>
						</tbody>
					</table>	
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=document.getElementById('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
}
</script>
