<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$brach_name =  $this->branch;
$result = $this->stockin;
$db = new report_Model_DbStock();
//print_r($result);
?>
<?php $formFilter = $this->formFilter; ?>
<title> <?php echo $tr->translate("RPT_WORKING_STONE");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i> <?php echo $tr->translate("RPT_WORKING_STONE");?>
				</div>
						<div class="btn-group pull-right">
							 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
							   <?php echo $tr->translate("ACTIONS");?> <i class="fa fa-angle-down"></i>
							 </button>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a href="#" onclick="doPrint();">
											<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;<?php echo $tr->translate("PRINT");?>
										</a>
									</li>
									<li>
										<a href="javascript:;"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
									</li>
									
								</ul>
					</div>
			</div>
            <div class="portlet-body form frmfilter">
				<form method="post" action="<?php //echo $formFilter->getAction(); ?>">
					<div class="form-group" style="padding-top: 6px;">
						
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('ad_search');?></label>
						<label class="control-label col-md-2">
								<select data-placeholder="Select..." class="form-control select2me " style="text-align: left;" id="add_item" name="add_item" Onchange="getItemOrder();" >
								<?php echo $this->items; ?>
								</select>
						</label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('category');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('suppliyer_id');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('start_date');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('end_date');?></label>
						<label class="control-label col-md-2 pull-right">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
						</label>
					</div><div style="clear:both;"></div>	
				</form> 
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
		<style>
			.style{
					line-height: 20px;font-size: 9px !important;
					font-family: 'Khmer OS Battambang';
				}
				ul{margin: 0;padding:0;}
				table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
				th{padding: 0px;}
				table thead tr th{
					line-height:30px;
					background:#ccc;
					font-size:15px;
					padding:3px;
				}
				table tr td{
					line-height:20px;
					font-size:12px;
				}
				ul.pur_info li{line-height:18px; 
						font-weight: normal !important;}
				ul.pur_info li strong{font-weight: bold;}
			   .hover:hover{background: #ccc;}
		</style>
		
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody><tr>
		                	<td width="20%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logo/<?php echo $this->title_reprot["logo"]?>"></td>
		                	<td width="60%" valign="top">
								<ul>
									<li style="text-align:center; font-size:20px; font-family:'Khmer OS Muol Light'"><?php echo $this->title_reprot["title_report_kh"]?></li>
									<li style="text-align:center; font-size:18px; font-family:serif,header-font; font-weight:600;"><?php echo $this->title_reprot["title_report_en"]?></li>
		                			<li style="text-align:center; font-size:18px;margin: 10px 0px 0px 0px;font-family:'Khmer OS Muol Light',serif,header-font;"> <?php echo $tr->translate("RPT_WORKING_STONE");?></li>
									<li style="text-align:center; font-size:13px;"><?php echo date("d/m/Y",strtotime($this->start_date));?> ដល់ <?php echo date("d/m/Y",strtotime($this->end_date));?></li>
		                		</ul>
		                	</td>
		                    <td width="20%"></td>
		                </tr> 
		                <tr>
		                	<td colspan="3" valign="top">
		                		<table width="100%" cellpadding="0" cellspacing="0">
		                			<tbody><tr>
		                				<td style="font-size: 11px;">
		                				    <span style="white-space: nowrap;"><?php //echo $tr->translate("ADDRESS_COMPANY");?></span>
		                					<br><?php //echo $tr->translate("TEL_COMPANY");?> 
		                				</td>
		                				<td width="65%"></td>
		                			</tr>
				                </tbody></table>
				              </td>
				           </tr>   
						</tbody>
					</table>
		        </td>
		    </tr>
		</table>
		<div class="table-responsive">
		<table>
		    <tr>
		    	<td id="exportExcel">
		            <table  class="collape tablesorter" style="border-collapse:collapse;border:0px solid #000; font-size:12px;" width="100%" cellspacing="0" border="1">
		                 <tbody>
						  <?php $num=1; 
						   
						   $totl_su_qty=0;
						  ?>
						 <tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:none;">
						   <td align="center" style="white-space: nowrap;text-align:center;border: none;">&nbsp;</td>
						   <td style="white-space: nowrap;text-align:center;border: none;">&nbsp;</td>
						   <td style="white-space: nowrap;text-align:center;border: none;"></td>
						   <td style="white-space: nowrap;text-align:center;border: none;"></td>
						   <td colspan="5" style="white-space: nowrap;text-align:center;">Stone</td>
						   <td style="white-space: nowrap;text-align:center;border: none;"></td>
						   <td colspan="5" style="white-space: nowrap;text-align:center;"><?php if(!empty($this->stockin[0])){echo $this->stockin[0]["branch_name"];}else{}?></td>
						  
						  <td style="white-space: nowrap;text-align:center;border: none;">&nbsp;<?php //echo  $total_edning_qty;?></td>
						   <td style="white-space: nowrap;text-align:center;border: none;">&nbsp;<span style="float:right"><?php //echo $total_amount;?></span></td>
						</tr>
						<tr bgcolor="#ccc" class="style tdborder" align="center" style="font-weight:bold; line-height: 35px;border:1px solid #000; font-size:12px; padding:10px 0px; white-space: nowrap; height:35px;">
		                    
							<td class="tdheader">&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("DATE");?>&nbsp;&nbsp;&nbsp;</td>
							<td class="tdheader">&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;&nbsp;&nbsp;</td>
							<td class="tdheader">&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("ITEM_NAME");?>&nbsp;&nbsp;&nbsp;</td>
							<td class="tdheader">&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("SUPPLIER");?>&nbsp;&nbsp;&nbsp;</td>
							<td class="tdheader">&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("PLATE_NO");?>&nbsp;&nbsp;&nbsp;</td>
							<td class="tdheader">&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("REFERENCE");?>&nbsp;&nbsp;&nbsp;</td>
							<td class="tdheader">&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("SU_QTY");?>&nbsp;&nbsp;&nbsp;</td>
							<td class="tdheader">&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("COST_PRICE");?>&nbsp;&nbsp;&nbsp;</td>
							<td class="tdheader">&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("AMOUNT");?>&nbsp;&nbsp;&nbsp;</td>
							<!--<td class="tdheader">&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("DIFFERENT");?>&nbsp;&nbsp;&nbsp;</td>-->
							<td class="tdheader">&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("NET_WEIGHT_KG");?>&nbsp;&nbsp;&nbsp;</td>
							<td class="tdheader">&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("NET_WEIGHT_M3");?>&nbsp;&nbsp;&nbsp;</td>
							<td class="tdheader">&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("REFERENCE");?>&nbsp;&nbsp;&nbsp;</td>
							<td class="tdheader">&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("COST_PRICE");?>&nbsp;&nbsp;&nbsp;</td>
							<td class="tdheader">&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("AMOUNT");?>&nbsp;&nbsp;&nbsp;</td>
							<td class="tdheader">&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("LOCATION");?>&nbsp;&nbsp;&nbsp;</td>
							<!--<td class="tdheader">&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("DATE");?>&nbsp;&nbsp;&nbsp;</td>
							<td class="tdheader">&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("SUPPLIER");?>&nbsp;&nbsp;&nbsp;</td>
							<td class="tdheader">&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("QTY");?>&nbsp;&nbsp;&nbsp;</td>
							<td class="tdheader">&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("AMOUNT");?>&nbsp;&nbsp;&nbsp;</td>-->
							<td class="tdheader">&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("DIFFER_QTY");?>&nbsp;&nbsp;&nbsp;</td>
							<td class="tdheader">&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("DIFFER_AMOUNT");?>&nbsp;&nbsp;&nbsp;</td>
							<td class="tdheader">&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("REMARK");?>&nbsp;&nbsp;&nbsp;</td>
		                </tr> 
		                <?php 
							$totl_com_amount=0;
							$totl_su_amount =0;
							$totl_com_qty=0;
							if(!empty($this->stockin))foreach ($this->stockin AS $index => $rs){
								$totl_su_qty = $totl_su_qty+number_format($rs["su_scale_qty"]/$rs["convertor_measure"],2);
								//$totl_com_qty = $totl_com_qty+number_format($rs["com_scale_qty"]/$rs["convertor_measure"],2);
								$totl_com_qty = $totl_com_qty+number_format($rs["qty_receive"],2);
								
								$totl_com_amount = $totl_com_amount+number_format(($rs["qty_receive"]*$rs["price"]),2);
								$totl_su_amount = $totl_su_amount+number_format(($rs["su_scale_qty"]/$rs["convertor_measure"]*$rs["price"]),2);
								
						?>
						<tr class='tdborder row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
						   
						   <td style="white-space: nowrap;">&nbsp;&nbsp;&nbsp;<?php echo $rs["date_in"];?>&nbsp;&nbsp;&nbsp;</td>
						   <td align="center" style="white-space: nowrap;">&nbsp;&nbsp;&nbsp;<?php echo $index+1;?>&nbsp;&nbsp;&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;&nbsp;&nbsp;<?php echo $rs["item_code"]."-".$rs["item_name"];?>&nbsp;&nbsp;&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;&nbsp;&nbsp;<?php echo $rs["supplier"];?>&nbsp;&nbsp;&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;&nbsp;&nbsp;<?php echo $rs["plat_no"];?>&nbsp;&nbsp;&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;&nbsp;&nbsp;<?php echo $rs["su_scale_refer"];?>&nbsp;&nbsp;&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;&nbsp;&nbsp;<?php echo number_format($rs["su_scale_qty"]/$rs["convertor_measure"],2);?><span style="float:right;">m<sup>3</sup></span>&nbsp;&nbsp;&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;&nbsp;&nbsp;$<span style="float:right;"><?php echo $rs["price"];?></span>&nbsp;&nbsp;&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;&nbsp;&nbsp;$<span style="float:right;"><?php echo number_format(($rs["su_scale_qty"]/$rs["convertor_measure"])*$rs["price"],2);?></span>&nbsp;&nbsp;&nbsp;</td>
						   <!--<td style="white-space: nowrap;">&nbsp;&nbsp;&nbsp;<?php //echo $rs["su_scale_qty"];?>&nbsp;&nbsp;&nbsp;</td>-->
						   <td style="white-space: nowrap;">&nbsp;&nbsp;&nbsp;<?php echo number_format($rs["com_scale_qty"],2);?><span style="float:right;">kg</span>&nbsp;&nbsp;&nbsp;</td>
							<td style="white-space: nowrap;">&nbsp;&nbsp;&nbsp;<?php echo number_format($rs["qty_receive"]);//echo number_format($rs["com_scale_qty"]/$rs["convertor_measure"],2);?><span style="float:right;">m<sup>3</sup></span>&nbsp;&nbsp;&nbsp;</td>
						   <td style="white-space: nowrap;"><?php echo $rs["com_scale_refer"];?></td>
						   <td style="white-space: nowrap !important;">&nbsp;&nbsp;&nbsp;$<span style="float:right;"><?php echo $rs["price"];?>&nbsp;&nbsp;&nbsp;</span></td>
						    <td style="white-space: nowrap !important;">&nbsp;&nbsp;&nbsp;$<span style="float:right;"><?php echo number_format(($rs["qty_receive"])*$rs["price"],2);?></span>&nbsp;&nbsp;&nbsp;</td>
						    <td style="white-space: nowrap;">&nbsp;&nbsp;&nbsp;<?php echo $rs["branch_name"];?>&nbsp;&nbsp;&nbsp;</td>
							 <!--<td style="white-space: nowrap;">&nbsp;&nbsp;&nbsp;<?php echo $rs["date_in"];?>&nbsp;&nbsp;&nbsp;</td>
							<td style="white-space: nowrap;">&nbsp;&nbsp;&nbsp;<?php echo $rs["supplier"];?>&nbsp;&nbsp;&nbsp;</td>
						    <td style="white-space: nowrap;">&nbsp;&nbsp;&nbsp;<?php echo $rs["com_scale_qty"];?><span style="float:right;">kg</span>&nbsp;&nbsp;&nbsp;</td>
							 <td style="white-space: nowrap;">&nbsp;&nbsp;&nbsp;$<span style="float:right;"><?php echo number_format(($rs["qty_receive"])*$rs["price"],2);?></span>&nbsp;&nbsp;&nbsp;</td>-->
							  <td style="white-space: nowrap;">&nbsp;&nbsp;&nbsp;<?php echo number_format(($rs["qty_receive"])-($rs["su_scale_qty"]/$rs["convertor_measure"]),2);?><span style="float:right;">m<sup>3</sup></span>&nbsp;&nbsp;&nbsp;</td>
							   <td style="white-space: nowrap;">&nbsp;&nbsp;&nbsp;$<span style="float:right;"><?php echo number_format((($rs["qty_receive"])*$rs["price"])-(($rs["su_scale_qty"]/$rs["convertor_measure"])*$rs["price"]),2);?></span>&nbsp;&nbsp;&nbsp;</td>
							 <td style="white-space: nowrap;">&nbsp;&nbsp;&nbsp;<?php echo $rs["remark"];?>&nbsp;&nbsp;&nbsp;</td>
						</tr>
						<?php 
							 
						}?>
						
		                </tbody>
		           </table>
				   <br />
				   <table style="border-collapse:collapse;border:1px solid #000; font-size:12px;padding:10px;" width="50%" cellspacing="0">
									<tr>
										<td>Cost Sheet</td>
										<td></td>
										<td class="center" style="border-bottom:1px solid #000">QTY</td>
										<td>&nbsp;&nbsp;&nbsp;</td>
										<td class="center" style="border-bottom:1px solid #000"> Amount </td>
										<td>&nbsp;&nbsp;&nbsp;</td>
										<td class="center" style="border-bottom:1px solid #000">QTY</td>
										<td>&nbsp;&nbsp;&nbsp;</td>
										<td class="center" style="border-bottom:1px solid #000"> Amount </td>
									</tr>
									<tr>
										<td>Total daily received</td>
										<td></td>
										<td class="center"><?php echo $totl_su_qty;?></td>
										<td></td>
										<td class="center"><?php echo $totl_su_amount;?></td>
										<td></td>
										<td class="center"><?php echo $totl_com_qty;?></td>
										<td></td>
										<td class="center"><?php echo $totl_com_amount;?></td>
									</tr>
									<tr>
										<td>Average cost per M3</td>
										<td></td>
										<td class="center"><?php //echo $totl_su_qty;?></td>
										<td></td>
										<td class="center"><?php //echo $totl_su_amount;?></td>
										<td></td>
										<td class="center"><?php //echo $totl_com_qty;?></td>
										<td></td>
										<td class="center"><?php //echo $totl_com_amount;?></td>
									</tr>
									<tr>
										<td>Total average cost per M3</td>
										<td></td>
										<td class="center"><?php //echo $totl_su_qty;?></td>
										<td></td>
										<td class="center"><?php //echo $totl_su_amount;?></td>
										<td></td>
										<td class="center"><?php //echo $totl_com_qty;?></td>
										<td></td>
										<td class="center"><?php //echo $totl_com_amount;?></td>
									</tr>
									
									
								</table>
		              <br>
		              <table align="center" width="100%">
						   <tbody><tr style="font-size: 11px;">
						        <td style="width:20%;text-align:center;font-size:13px; font-family:'Khmer OS Muol Light'">អនុម័តដោយ</td>
						        <td></td>
								<td style="width:20%;text-align:center;font-size:13px; font-family:'Khmer OS Muol Light'">ត្រួតពិនិត្យដោយ</td>
								<td></td>
								<td style="width:20%;text-align:center;font-size:13px; font-family:'Khmer OS Muol Light'">រៀបចំដោយ</td>
						   </tr>
						</tbody>
					</table>	
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=document.getElementById('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
}
</script>
