<?php 
	$url_new = $this->url(array('module'=>'sales','controller'=>'plan','action'=>'add',));
	$url_edit = $this->url(array('module'=>'sales','controller'=>'plan','action'=>'edit',));
	$url_delete = $this->url(array('module'=>'sales','controller'=>'plan','action'=>'delete',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->formFilter;
	$formFilter = $this->formFilter;
	$rs = $this->product;
?>
<title><?php echo $tr->translate("PRODUCT_LIST");?></title>

	<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("PLAN");?>
			</div>
			
			<div class="caption pull-right">
				<a href="<?php echo $url_new;?>"><button id="sample_editable_1_new" class="btn green">Add New <i class="fa fa-plus"></i></button></a>
			</div>
			<div class="caption" style="float:right">
					<?php $formList = new Application_Form_Frmlist(); //echo $formList->showAddBuntton($url_new);?>
			</div>
		</div>
		<div class="portlet-body form">
			<form class="form-horizontal" method="post" action="" >
				<div class="form-body">
					<div class="form-group">
						<div class="col-md-2">
							<input  class="form-control" id="adv_search" name="adv_search" value="<?php echo $this->row['adv_search']?>" placeholder="<?php echo $this->translate("Search");?>" type="text" >
						</div>
						
						<div class="col-md-2">
							<?php echo $form->getElement('typecate');?>
						</div>
						<div class="col-md-2">
							<?php echo $form->getElement('customer_id');?>
						</div>
						<div class="col-md-2">
							<?php echo $form->getElement("status");?>
						</div>
						<div class="col-md-2">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("Search");?></button>
						</div>						
					</div>
				</div>
				
			</form>
			<div class="contain_form" style="clear: both;">
					<form name="list"><div style="overflow:scroll; max-height: 450px; overflow-x:hidden;" >
					<table class="collape tablesorter" id="table" width="100%">
						<thead>
							<tr>
								<th class="tdheader"><?php echo  $tr->translate("NUM");?></th>
								<th class="tdheader"><?php echo  $tr->translate("PLAN_CODE");?></th>
								<th class="tdheader"><?php echo  $tr->translate("PLAN_NAME");?></th>
								<th class="tdheader"><?php echo  $tr->translate("PLAN_TYPE");?></th>
								<th class="tdheader"><?php echo  $tr->translate("PLAN_GAOL");?></th>
								<th class="tdheader"><?php echo  $tr->translate("CUSTOMER");?></th>
								<th class="tdheader"><?php echo  $tr->translate("PLAN_ADDRESS");?></th>
								<th class="tdheader"><?php echo  $tr->translate("DATE_LINE_PLAN");?></th>
								<th class="tdheader"><?php echo  $tr->translate("DATE_LINE_QO");?></th>
								<th class="tdheader"><?php echo  $tr->translate("APPROVED_STATUS");?></th>
								<th class="tdheader"><?php echo  $tr->translate("PENDING_STATUS");?></th>
								<th class="tdheader"><?php echo  $tr->translate("USER");?></th>
								<th class="tdheader"><?php echo  $tr->translate("ACTION");?></th>
							</tr>
						</thead>
						<tbody>
							<?php 
							$id = "table";
							$stringPagination = '<script type="text/javascript">
										$(document).ready(function(){
											$("#'.$id.'").tablesorter();
											$("#'.$id.'").tablesorter().tablesorterPager({container: $("#pagination_'.$id.'"),size:15});
											$("#pagedisplay").focus(function(){ this.blur(); 
										   });
										});
								</script>
								<div id="pagination_'.$id.'" class="pager" >
											<form >
												<table  style="width: 200px;"><tr>
												<td><img src="'.BASE_URL.'/images/first.gif" class="first"/></td>
												<td><img src="'.BASE_URL.'/images/previous.gif" class="prev"/></td>
												<td><input type="text" class="pagedisplay"/></td>
												<td><img src="'.BASE_URL.'/images/next.gif" class="next"/></td>
												<td><img src="'.BASE_URL.'/images/last.gif" class="last"/></td>
												<td><select class="pagesize" >
													<option selected="selected"  value="10">10</option>
													<option value="20">20</option>
													<option value="30">30</option>
													<option value="40">40</option>
													<option value="50">50</option>
													<option value="60">60</option>
													<option value="70">70</option>
													<option value="80">80</option>
													<option value="90">90</option>
													<option value="100">100</option>
													</select>
												</td>
												</tr>
												</table>
											</form>
									</div>	';
							$footer="";
							if(!empty($this->rows)){
								foreach ($this->rows as $key=>$rs){
									$pedding_action = '';
									if($rs["pedding"]>1){
										$pedding_action="color:#ccc;pointer-events: none;";
									}
									
									
							?>
								<tr class="normal">
									<td class="items-no"><?php echo $key+1;?></td>
									<td class="items"><?php echo $rs["code"];?></td>
									<td class="items"><?php echo $rs["name"];?></td>
									<td class="items"><?php echo $rs["type"];?></td>
									<td class="items"><?php echo $rs["plan_goald"];?></td>
									<td class="items"><?php echo $rs["customer"];?></td>
									<td class="items"><?php echo $rs["address"];?></td>
									<td class="items"><?php echo date("Y-m-d",strtotime($rs["date_line_plan"]));?></td>
									<td class="items"><?php echo date("Y-m-d",strtotime($rs["date_line_qo"]));?></td>
									<td class="items"><?php echo $rs["appr_status"];?></td>
									<td class="items"><?php echo $rs["peddings"];?></td>
									<td class="items"><?php echo $rs["user_name"];?></td>
									<td class="items-no" style="white-space: nowrap;">
										<a target="_blank" style="<?php echo $pedding_action; ?>" href="<?php echo $this->baseUrl();?>/sales/plan/edit/id/<?php echo $rs["id"]?>"><?php echo  $tr->translate("EDIT");?></a>​ | 
										<a target="_blank" <?php  ?> href="<?php echo $this->baseUrl();?>/sales/plan/planprint/id/<?php echo $rs["id"]?>"><?php echo  $tr->translate("PRINT");?></a>​ 
									</td>
								</tr>
							<?php $counter='<strong style="float:right;padding:5px">Number of record(s): '.count($this->rs).'</strong>'; 
								$footer = '<div class="footer_list">'.$stringPagination.$counter.'</div>';
							}}?>
						</tbody>
					</table></div></form><?php echo $footer?>
						<?php //echo $this->list; ?>
			    </div>
		</div>
		<?PHP //echo $this->list ?>
		
</div>