<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form_purchase;
	$url_submit = $this->url(array('module'=>'purchase','controller'=>'compareprice','action'=>'add'));
	$url_cancel = $this->url(array('module'=>'purchase','controller'=>'compareprice','action'=>'addcompare'),null,true);
	$db = new Purchase_Model_DbTable_DbPriceCompare();
	//echo $this->id;
?>
<style>
      table.table-bordered tbody th, table.table-bordered tbody td{width:2px;}
	  .style{
			line-height: 20px;font-size: 9px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px;}
		th{padding: 5px;}
		ul.pur_info li{line-height:18px; 
				font-weight: normal !important;}
		ul.pur_info li strong{font-weight: bold;}
       .hover:hover{background: #ccc;}
</style>
<title><?php echo $tr->translate("ADD_PURCAHSE_ORDER");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("ADD_PURCAHSE_ORDER")?>
				</div>
				<div class="tools" >
					<a href="<?php echo $url_cancel;?>" class="btn btn-sm pull-right" style="color:white;">
					<i class="fa fa-undo"></i>	&nbsp;<?php echo $tr->translate("GO_BACK");?>
					</a>
				</div>
			</div>
			<div class="portlet-body">
				<!-- BEGIN FORM-->
				<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody>
						<tr>
								<td width="20%" valign="middle"><img src="<?php echo $this->baseUrl();?>/images/logo/<?php echo $this->title_reprot["logo"]?>"></td>
								<td width="60%" valign="top" style="line-height:30px">
									<ul>
										<li style="text-align:center; font-size:20px; font-family:'Khmer OS Muol Light'"><?php echo $this->title_reprot["title_report_kh"]?></li>
										<li style="text-align:center; font-size:18px; font-family:serif,header-font; font-weight:600;"><?php echo $this->title_reprot["title_report_en"]?></li>
										<li style="text-align:center; font-size:18px; margin-top:25px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("PRICE_COMPARE");?></li>
									</ul>
								</td>
								<td width="20%"></td>
							</tr> 
		                <tr>
		                	<td colspan="3" valign="top">
		                		<table width="100%" cellpadding="0" cellspacing="0" >
		                			<tbody>
		                			<tr>
		                				<td style="font-size: 11px;">
		                				    <span style="white-space: nowrap;"><?php //echo $tr->translate("ADDRESS_COMPANY");?></span>
		                					<br><?php //echo $tr->translate("TEL_COMPANY");?> 
		                				</td>
		                				<td ></td>
		                				<td width="65%"></td>
		                			</tr>
		                			<tr>
								<td width="20%" valign="bottom">
									<table width="100%" style="font-size: 12px; !important">
										<tr>
											<td style="text-align: left; white-space:nowrap;"><?php echo $tr->translate("PLAN");?> </td>
											<td style="text-align: right; white-space:nowrap;">:</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo $this->product[0]['plan'];?></td>
										</tr>
										<tr>
											<td style="text-align: left; white-space:nowrap;"><?php echo $tr->translate("NUMBER_REQUEST");?> </td>
											<td style="text-align: right; white-space:nowrap;">:</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo $this->product[0]['number_request'];?></td>
										</tr>
										
										<tr>
											<td style="text-align: left;white-space:nowrap;"><?php echo $tr->translate("DATE_REQUEST_WORK_SPACE");?> </td>
											<td style="text-align: right; white-space:nowrap;">:</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo date("d-M-Y",strtotime($this->product[0]['date_from_work_space']));?></td>
										</tr>
									</table>
								</td>
								<td width="60%" valign="top">
									
								</td>
								<td width="20%" style="text-align: right;font-size: 12px;">
									<table width="100%" style="font-size: 12px; !important">
										<tr>
											<td style="text-align: right; white-space:nowrap;"><?php echo $tr->translate("DATE_COMPARE");?> :</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo date("d-M-Y",strtotime($this->product[0]['com_date']));?> </td>
										</tr>
										<tr>
											<td style="text-align: right; white-space:nowrap;"><?php echo $tr->translate("COMPARE_PRICE_CODE");?> :</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo $this->product[0]['c_code'];?> </td>
										</tr>
										<tr>
											<td style="text-align: right; white-space:nowrap;"><?php echo $tr->translate("BRANCH_NAME");?> :</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo $this->product[0]['branch'];?></td>
										</tr>
										<tr>
											<td style="text-align: right; white-space:nowrap;"><?php echo $tr->translate("REQUEST_NO");?> :</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo $this->product[0]['re_code'];?></td>
										</tr>
										<tr>
											<td style="text-align: right;white-space:nowrap;"><?php echo $tr->translate("REQUEST_DATE");?> :</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo date("d-M-Y",strtotime($this->product[0]['date_request']));?></td>
										</tr>
									</table>
									<!--<ul class='pur_info'>
			                					<li style="text-align: left;"><strong><?php echo $tr->translate("BRANCH_NAME");?> : </strong><?php echo $this->product[0]['branch'];?></li>
			                					<li style="text-align: right;"><strong><?php echo $tr->translate("REQUEST_NO");?> : </strong><?php echo $this->product[0]['re_code'];?></li>
			                					<li style="text-align: right;"><strong><?php echo $tr->translate("REQUEST_DATE");?> : </strong><?php echo date("d-M-Y",strtotime($this->product[0]['date_request']));?></li>
												<li style="text-align: left;"><strong><?php echo $tr->translate("PEDDING");?> : </strong><?php echo $this->product[0]['pedding'];?></li>
		                						<li style="text-align: left;"><strong><?php echo $tr->translate("PURCHASE_STATUS");?> : </strong><?php echo $this->product[0]['status'];?></li>
		                			</ul>-->
								</td>
							</tr> 
				                </tbody></table>
				              </td>
				           </tr>   
		            </tbody></table>
					<br />
				<form id="frm" action="<?php //echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post">
					<input type="hidden" name="c_code" value="<?php echo $this->product[0]['c_code'];?>" />
				<div class="table-responsive ">
					<table class="table table-striped table-bordered table-hover" id="table_order" style="font-size:12px;">
						<tr>
							<th rowspan="2" align="center" style="vertical-align: middle;" class="center"><?php echo $tr->translate("NUM");?></th>
							<th rowspan="2" align="center" style="vertical-align: middle;" class="center"><?php echo $tr->translate("ITEM_NAME");?></th>
							<th rowspan="2" class="center" style="vertical-align: middle;"><?php echo $tr->translate("QTY");?></th>
							<?php foreach($this->su_id as $key => $rss){ $i = $key+1; ?>
							<th class="center">Quaotation <?php echo $db->integerToRoman($i);?> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;VAT :<input type="checkbox" value="1" <?php if($rss["is_vat"]==1){ echo "checked='checked'";}?> name="vat_<?php echo $i;?>" /></th>
							<?php }?>
							<!--<th class="center">Quaotation I &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;VAT :<input type="checkbox" value="1" name="vat_1" /></th>
							<th class="center">Quaotation II &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;VAT :<input type="checkbox" value="1" name="vat_2" /></th>
							<th class="center">Quaotation III &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;VAT :<input type="checkbox" value="1" name="vat_3" /></th>
							<th class="center">Quaotation IV &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;VAT :<input type="checkbox" value="1" name="vat_4" /></th>
							-->
						</tr>
						<tr>
							<?php foreach($this->su_id as $key => $rss){ $i = $key+1; ?>
								<td style="white-space:nowrap;">
									<select style="width:199px;" name="su_id_<?php echo $i;?>" class="form-control select2me" >
										<?php foreach($this->vendor as $rs){?>
											<option value="<?php echo $rs["vendor_id"];?>" <?php if($rs["vendor_id"]==$rss["su_id"]){echo 'selected="selected"';}?> > <?php echo $rs["v_name"]?></option>
										<?php }?>
									</select>
								</td>
							<?php }?>
						</tr>
						<?php 
							foreach($this->product as $key => $rs){ $i= $key+1;
						?>
						<tr>
							<td style="white-space:nowrap;text-align:center;vertical-align: middle;"><?php echo $i;?></td>
							<td style="white-space:nowrap;vertical-align: middle;"><?php echo $rs["item_name"];?><input type="hidden" name="pro_id_<?php echo $i;?>" value="<?php echo $rs["id"];?>" /></td>
							<td style="white-space:nowrap;vertical-align: middle;"><?php echo $rs["qty"]."&nbsp;&nbsp;". $rs["measure"];?>
								<input type="hidden" name="pro_qty_<?php echo $i;?>" value="<?php echo $rs["qty"];?>" />
								
							</td>

							<?php 
								$product = $db->getProCompare($this->id,$rs["id"]);
								foreach( $product as $key => $rss){ 
									if($rss["is_check"]==1){
										$check = 'checked="checked"';
									}else{
										$check = '';
									}
									$j = $key+1;
							?>
								<td style="white-space:nowrap;">
									<table class="table table-striped table-bordered table-hover" style="font-size:12px !important;margin-bottom: 3px !important;" >
										<tr>
											<th style="width: 50%;"><?php echo $tr->translate("BRAND");?></th>
											<th><?php echo $tr->translate("PRODUCT_FROM");?></th>
										</tr>
										<tr>
											<td><input type="text" style="width: 100%; "name="brand_<?php echo $i?>_<?php echo $j;?>" id="brand_<?php echo $i?>_<?php echo $j;?>" value="<?php echo $rss["pro_brand"]?>" /></td>
											<td><input type="text" style="width: 100%;"name="pro_from_<?php echo $i?>_<?php echo $j;?>" id="pro_from_<?php echo $i?>_<?php echo $j;?>" value="<?php echo $rss["pro_from"] ?>"/></td>
										</tr>
									</table>
									<div class="input-icon left"><i class="fa">$</i><input style="text-align:right;width: 80%;" name="su_price_<?php echo $i?>_<?php echo $j;?>" value="<?php echo $rss["price"]?>" /><input type="checkbox" value="1" <?php echo $check;?> name="checkbox_<?php echo $i?>_<?php echo $j;?>"/></div>
									
									<!--<input type="hidden" style="width: 50%;"name="brand_<?php //echo $i?>_<?php //echo $j;?>" id="brand_<?php //echo $i?>_<?php //echo $j;?>" value="<?php //echo $rss["pro_brand"] ?>" />
									<input type="hidden" style="width: 50%;"name="pro_from_<?php //echo $i?>_<?php //echo $j;?>" id="pro_from_<?php //echo $i?>_<?php //echo $j;?>" value="<?php //echo $rss["pro_from"] ?>"/>-->
								</td>
							<?php 
							} ?>
						</tr>
						<?php 
							if($i>1){
								$index = $index.",".$i;
							}else{
								$index = 1;
							} 
						} ?>
					</table>
				</div>
					<input type="hidden" name="identity" value="<?php echo $index;?>" />
					<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("REJECT_FROM_CHECK");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<textarea name="remark" id="notefrom_accountingk" style="width:100%;height: 50px;" ><?php echo $this->product[0]["reject_check"]?></textarea>
								</div>
							</div>
							
							<label class="control-label col-md-2"><?php echo $tr->translate("REASON");?> : <span class="required">
								</span>
							</label>
							<div  class="col-md-4">
								<textarea name="note" class="form-control"><?php echo $this->su_id[0]["remark"]?></textarea>
							</div>
					</div>
					<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("REJECT_FROM_APPROVE");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<textarea name="reject_approve" id="notefrom_accountingk" style="width:100%;height: 50px;" ><?php echo $this->product[0]["reject_approve"]?></textarea>
								</div>
							</div>
							
							<label class="control-label col-md-2"><?php //echo $tr->translate("REJECT_FROM_APPROVE");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<!--<textarea name="reject_approve" id="notefrom_accountingk" style="width:100%;height: 50px;" ><?php //echo $this->product[0]["reject_approve"]?></textarea>-->
								</div>
							</div>
					</div>
					<div class="form-group">
							<div  class="col-md-12 col-md-offset-4 col-md-8">
								<a href="<?php echo $this->baseUrl();?>/purchase/compareprice/addcompare"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
								<button type="submit" name="save_close" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<!--<button type="submit" name="save_print" class="btn btn-primary"><i class="fa fa-print"></i> <?php echo $tr->translate("SAVE_PRINT")?></button>-->
							</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
	