<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("MAKE_INVOCIE");?></title>
<div class="row">
<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("ប័ណ្ណស្នើសុំទិញសម្ភារៈ");?>
				</div>
						<!--<div class="btn-group pull-right">
							 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
							   Actions <i class="fa fa-angle-down"></i>
							 </button>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a href="#" onclick="doPrint();">
											<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
										</a>
									</li>
								</ul>
					</div>-->
			</div>
            <div class="portlet-body form frmfilter">
					<div style="clear:both;"></div>	
	<div style=" min-height:25cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	 <?php $url_submit = $this->url(array('module'=>'purchase','controller'=>'auditapprove','action'=>'approved'));?>
	<form id="form_sample_2" action="<?php //echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post">		   
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 20px;font-size: 9px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px;}
		th{padding: 5px;}
		ul.pur_info li{line-height:18px; 
				font-weight: normal !important;}
		ul.pur_info li strong{font-weight: bold;}
       .hover:hover{background: #ccc;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody>
						<tr>
								<td width="20%" valign="middle"><img src="<?php echo $this->baseUrl();?>/images/logo/<?php echo $this->title_reprot["logo"]?>"></td>
								<td width="60%" valign="top" style="line-height:30px">
									<ul>
										<li style="text-align:center; font-size:20px; font-family:'Khmer OS Muol Light'"><?php echo $this->title_reprot["title_report_kh"]?></li>
										<li style="text-align:center; font-size:18px; font-family:serif,header-font; font-weight:600;"><?php echo $this->title_reprot["title_report_en"]?></li>
										<li style="text-align:center; font-size:18px; margin-top:25px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("MR_CHECK");?></li>
									</ul>
								</td>
								<td width="20%"></td>
							</tr> 
		                <tr>
		                	<td colspan="3" valign="top">
		                		<table width="100%" cellpadding="0" cellspacing="0" >
		                			<tbody>
		                			<tr>
		                				<td style="font-size: 11px;">
		                				    <span style="white-space: nowrap;"><?php //echo $tr->translate("ADDRESS_COMPANY");?></span>
		                					<br><?php //echo $tr->translate("TEL_COMPANY");?> 
		                				</td>
		                				<td ></td>
		                				<td width="65%"></td>
		                			</tr>
		                			<tr>
								<td width="20%" valign="top">
									<table width="100%" style="font-size: 12px; !important">
										<tr>
											<td style="text-align: left; white-space:nowrap;"><?php echo $tr->translate("PLAN");?> </td>
											<td style="text-align: right; white-space:nowrap;">:</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo $this->request['plan'];?><input type="hidden" name="check_reject_count" value="<?php echo $this->request['check_reject_count'];?>"/></td>
										</tr>
										<tr>
											<td style="text-align: left; white-space:nowrap;"><?php echo $tr->translate("NUMBER_REQUEST");?> </td>
											<td style="text-align: right; white-space:nowrap;">:</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo $this->request['number_request'];?></td>
										</tr>
										
										<tr>
											<td style="text-align: left;white-space:nowrap;"><?php echo $tr->translate("DATE_REQUEST_WORK_SPACE");?> </td>
											<td style="text-align: right; white-space:nowrap;">:</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo date("d-M-Y",strtotime($this->request['date_from_work_space']));?></td>
										</tr>
									</table>
								</td>
								<td width="60%" valign="top">
									
								</td>
								<td width="20%" style="text-align: right;font-size: 12px;">
									<table width="100%" style="font-size: 12px; !important">
										<tr>
											<td style="text-align: right; white-space:nowrap;"><?php echo $tr->translate("BRANCH_NAME");?> :</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo $this->request['branch'];?></td>
										</tr>
										<tr>
											<td style="text-align: right; white-space:nowrap;"><?php echo $tr->translate("REQUEST_NO");?> :</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo $this->request['re_code'];?></td>
										</tr>
										<tr>
											<td style="text-align: right;white-space:nowrap;"><?php echo $tr->translate("REQUEST_DATE");?> :</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo date("d-M-Y",strtotime($this->request['date_request']));?></td>
										</tr>
									</table>
									<!--<ul class='pur_info'>
			                					<li style="text-align: left;"><strong><?php echo $tr->translate("BRANCH_NAME");?> : </strong><?php echo $this->product[0]['branch'];?></li>
			                					<li style="text-align: right;"><strong><?php echo $tr->translate("REQUEST_NO");?> : </strong><?php echo $this->product[0]['re_code'];?></li>
			                					<li style="text-align: right;"><strong><?php echo $tr->translate("REQUEST_DATE");?> : </strong><?php echo date("d-M-Y",strtotime($this->product[0]['date_request']));?></li>
												<li style="text-align: left;"><strong><?php echo $tr->translate("PEDDING");?> : </strong><?php echo $this->product[0]['pedding'];?></li>
		                						<li style="text-align: left;"><strong><?php echo $tr->translate("PURCHASE_STATUS");?> : </strong><?php echo $this->product[0]['status'];?></li>
		                			</ul>-->
								</td>
							</tr> 
				                </tbody></table>
				              </td>
				           </tr>   
		            </tbody></table>
		        </td>
		    </tr>
		    <tr>
		    	<td id="exportExcel"><br />
		            <table  border="1" class="collape tablesorter" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0" border="1">
		                 <tbody>
		                 <tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; line-height: 20px; font-size:13px !important; padding:1px 0px; white-space: nowrap; ">
		                    <th class="tdheader" width="5%"><?php echo $tr->translate("NUM");?></th>
							<th class="tdheader" width="15%"><?php echo $tr->translate("ITEM_CODE");?></th>
							<th class="tdheader" width="15%"><?php echo $tr->translate("ITEM_NAME");?></th>
							<th class="tdheader" width="10%"><?php echo $tr->translate("TYPE");?></th>
							<!--<th width="5%"><?php //echo $tr->translate("SIZE");?></th>
							<th width="5%"><?php //echo $tr->translate("LENGHT");?></th>-->
							<th class="tdheader" width="10%"><?php echo $tr->translate("TOTAL_QTY");?></th>
							<th class="tdheader" width="5%"><?php echo $tr->translate("MEASURE");?></th>
							<!--<th width="10%"><?php //echo $tr->translate("SUPPLIER");?></th>-->
							<th class="tdheader" width="10%"><?php echo $tr->translate("REQ_DATE_IN");?></th>
							<th class="tdheader" width="25%"><?php echo $tr->translate("REMARK");?></th>
		                </tr>
		                <?php $num=1; 
		                if(!empty($this->product))foreach ($this->product AS $index => $rs){?>
						<tr class="odd gradeX" class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
						   <td align="center">&nbsp;<?php echo $index+1?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_code"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_name"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["type"];?></td>
						   <!--<td style="white-space: nowrap;">&nbsp;<?php //echo $rs["size"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php​ //echo $rs["size"];?></td>-->
						   <td style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["qty"],2);?></td>
						   <td style="white-space: nowrap;" align="center">&nbsp;<?php echo $rs["measure"];?></td>
						   <td style="white-space: nowrap;" align="center">&nbsp;<?php echo date("d-M-Y",strtotime($rs["date_in"]));?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["remark"];?></td>
						</tr>
						   <?php 
                    }?>
                    
					<!--<tr>
						<td colspan="4" style="border:1px solid #fff;border-top:1px solid #000;border-right:1px solid #fff;">
						<strong  style="font-size: 13px;"><u>ខសន្យា និងលក្ខណ៏ទូទៅ / General Term & Conditions</u></strong>
							<style>
								ul.termcodition li{ line-height: 20px;list-style-type: none; font-size: 12px;}
							</style>
							<ul class="termcodition">
							<?php //if(!empty($this->rscondition))foreach ($this->rscondition as $key =>$rst){ ?>
								<li style="text-align: left;"><?php //echo $key+1;echo "-".$rst['con_khmer'];?></li>
								<li style="text-align: left;"><?php //echo $rst['con_english'];?></li>
							<?php //}?>
							</ul>
						</td>
						
					</tr>-->
		            </tbody>
		           </table>
		              <br>
		            
					
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div><!-- end print -->
		<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("REASON");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<textarea name="remark" id="notefrom_accountingk" style="width:100%;height: 50px;" ><?php echo $this->request["reject_check"]?></textarea>
								</div>
							</div>
							
							<label class="control-label col-md-1"><?php //echo $tr->translate("REJECT_FROM_APPROVE");?><span class="required">
								</span>
							</label>
							<div class="col-md-5">
								<div class="input-icon right">
									<i class="fa"></i>
									<!--<textarea name="reject_approve" id="notefrom_accountingk" style="width:100%;height: 50px;" ><?php echo $this->request["reject_approve"]?></textarea>-->
									<select name="approve" id="approved_name" class="form-control select2me">
							        	<option value="1"><?php echo $tr->translate("CHECKED");?></option>
							        	<option value="2"><?php echo $tr->translate("REJECT");?></option>
							        </select>
								</div>
							</div>
						</div>
		<!-- <table align="center" width="100%" >
							   <tbody>
							   <tr style="font-size: 12px;height:40px">
							       <td style="text-align:right; white-space: nowrap;"></td>
							        <td></td>
									<td width="10%"></td>
							        <td style="width:40%;white-space: nowrap;">
							        <select name="approve" id="approved_name" class="form-control select2me">
							        	<option value="1"><?php echo $tr->translate("CHECKED");?></option>
							        	<option value="2"><?php echo $tr->translate("REJECT");?></option>
							        </select>
									
							        </td>
							   </tr>
							   
							  <tr style="font-size: 11px; height: 75px;">
							        <td valign="bottom" style="text-align:center;  font-family:'Khmer MEF2'; white-space: nowrap;"><span  class="form-control" style="border: 2px dotted #ddd; height: 100px;width:100%;"><textarea name="notefrom_accountingk" id="notefrom_accountingk" style="width:100%;height:100%;" ></textarea></span></td>
							        <td></td>
							        <td valign="bottom" style="text-align:center; font-family:'Khmer MEF2';white-space: nowrap;"><textarea name="app_remark" id="app_remark" class="form-control" rows="3" cols="80" placeHolder="Approval Comment Here"></textarea></td>
							   </tr>
							   <tr style="font-size: 11px;">
							        <td style="text-align:center;white-space: nowrap;"><strong></strong><div class="input-icon right"></div></td>
							        <td></td>
							        <td style="text-align:center;white-space: nowrap;"><strong>ថ្ងៃខែយល់ព្រម /Approved Date</strong><div class="input-icon right"><i class="fa fa-calendar"></i><input name="app_date" id="app_date" value="<?php echo date("d-M-Y");?>" class="form-control form-control-inline date-picker" /></div></td>
							   </tr>
							  
							</tbody>
						</table>-->
		<br />
		<div class="form-group">
			<div  class="col-md-12 col-md-offset-4 col-md-8">
				<a href="<?php echo $this->baseUrl();?>/purchase/mrcheck/"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
				<button type="submit" name="save_close" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
			</div>
		</div>
		</form>	
		
		
		
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>

$(document).ready(function() { 
   
  calculateBalance();
 }); 

 
function calculateBalance(){
	deposit= $("#deposit").val();
	net_total = $('#net_total').val();
	balance = parseFloat(net_total)-parseFloat(deposit);
	if(balance<0){
		balance=0;
		$("#deposit").val(net_total);
	}
	$("#balance").val(balance);
}
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=document.getElementById('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    //hideDialog();
}

</script>
