<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form;
	$url_submit = $this->url(array('module'=>'purchase','controller'=>'purchaserequest','action'=>'add'));
	$url_cancel = $this->url(array('module'=>'purchase','controller'=>'purchaserequest','action'=>'index'));
	$date_now = date("m/d/Y");
	//echo $date_now;
?>
<style>
      table.table-bordered tbody th, table.table-bordered tbody td{width:2px;}
</style>
<title><?php echo $tr->translate("ADD_PURCAHSE_ORDER");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("ADD_PURCAHSE_ORDER")?>
				</div>
				<div class="tools" >
					<a href="<?php echo $url_cancel;?>" class="btn btn-sm pull-right" style="color:white;">
					<i class="fa fa-undo"></i>	&nbsp;<?php echo $tr->translate("GO_BACK");?>
					</a>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="frm" action="<?php //echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post">
					<div class="form-body">
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("REQUEST_CODE");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("request_no");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("DATE_REQUEST");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('date_request');?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("PLAN");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("plan");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("LOCATION_NAME");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('branch');?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("NUMBER_WORK_SPACE");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("number_work_space");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("DATE_REQUEST_WORK_PLACE");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('date_request_work_space');?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("REASON");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("remark");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("STATUS");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('status');?>
								</div>
							</div>
						</div>
						<div class="form-group">
						<div class="col-md-12">
							<label class="control-label col-md-2 col-lg-2">
								<button type="button" class="btn red delete col-md-12">
									<i class="fa fa-barcode"></i>
									<span>Scan </span>	
								</button>
							</label>
							<label class="control-label col-md-8">
								<!--<select data-placeholder="Select..." class="form-control select2me" id="add_item" name="add_item" Onchange="getItemOrder();"  style="width:100% ;margin:0 auto;">
											<?php //echo $this->items; ?>
								</select>-->
								
								<input type="hidden" class="form-control" id="add_item" name="add_item" Onchange="getItemOrder();" style="width:100%;" placeholder="<?php echo $tr->translate("SELECT_PRODUCT");?>"/>
							</label>
							<label class="control-label col-md-2 col-lg-2 col-sm-12">
								<button type="button" class="btn red delete col-md-12">
								<!-- 	<input type="checkbox" Onclick="Confirmmessage()" id="free" name="free" />
									<span>&nbsp;&nbsp;Free</span>
									-->
								</button> 
							</label>
						</div>
						</div>
						<div class="portlet-body">
							<table class="table table-striped table-bordered table-hover" id="table_order" style="font-size:12px;">
								<tr height="33px">
									<td style="width:4%;" class="center"><?php echo $tr->translate("DEL");?></td>
									<td style=" width:4%;" class="center"><?php echo $tr->translate("NUM");?></td>
									<td style="white-space:nowrap;" class="center"><?php echo $tr->translate("ITEM_CODE");?></td>
									<td style="white-space:nowrap;" class="center"><?php echo $tr->translate("ITEM_NAME_CAP");?></td>
									<td style="white-space:nowrap;" class="center"><?php echo $tr->translate("QTY_UNIT");?></td>
									<td style="white-space:nowrap;" class="center"><?php echo $tr->translate("MEASURE");?></td>
									<td style="white-space:nowrap;" class="center"><?php echo $tr->translate("REQ_DATE_IN");?></td>
									<td style="white-space:nowrap;" class="center"><?php echo $tr->translate("REMARK");?></td>
								</tr>
							</table>
							<input type="hidden" id="identity" name="identity" />
							
						</div>
						
						<div class="form-group">
							<div  class="col-md-12 col-md-offset-4 col-md-8">
								<a href="<?php echo $this->baseUrl();?>/purchase/purchaserequest/"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
								<button type="submit" name="save_close" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<button type="submit" name="btnsavenew" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
								<!--<button type="submit" name="save_print" class="btn btn-primary"><i class="fa fa-print"></i> <?php //echo $tr->translate("SAVE_PRINT")?></button>-->
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>


<script>

itemss = <?php echo Zend_Json::encode($this->product)?>;
$( document ).ready(function() {
	select2Speed('add_item');
	//alert("ready loaded");
});
function select2Speed(name){
	 $('#add_item').select2({
            data : _.map(_.range(0, itemss.length), function (i) {
				//alert(itemss);
                  return {
                      id  : itemss[i].id,
                      text: itemss[i].item_code+"-"+itemss[i].item_name
                  };
            }),
            dropdownCssClass : 'capitalize',
            containerCssClass: 'capitalize',
            // configure as multiple select
            //multiple         : true,
            // text for loading more results
            formatLoadMore   : 'Loading more...',
            query            : function (q) {
            // pageSize is number of results to show in dropdown
                var pageSize,
                    results;
                    pageSize = 20;
                    results  = _.filter(this.data, function (e) {
                        return (q.term === "" || e.text.toUpperCase().indexOf(q.term.toUpperCase()) >= 0);
                 });
                q.callback({
                    results: results.slice((q.page - 1) * pageSize, q.page * pageSize),
                    // retrieve more when user hits bottom
                    more   : results.length >= q.page * pageSize
                });
            }
        });
}

var index5 = 0;num=0;
var option5 = '<?php echo $this->items; ?>';
var baseUrl = '<?php echo BASE_URL; ?>';
var template = '';
var value = '';
pqty = 1;
var index=0;

<?php $url_product =  $this->url(array('module'=>'','controller'=>'ajax','action'=>'get-product-name')); ?>
function addRow(item_id) {
	 index5++;//var first = index5;
	 var identity = $('#identity').val();
	var arrays = identity.split(',');
	if(arrays!=""){
		a = arrays.length;
		//alert(a);
		index= parseInt(a)+1;
	}else{
		index=1;
	}
	$.ajax({
		url:"<?php echo $url_product;?>",
		type:"post",
		data:{'item_id':item_id},
		success: function(data){
			//alert(data);
			rs = $.parseJSON(data);	
			for(i=1; i<index5; i++){
				new_item=parseInt(item_id);
				items = parseInt($("#item_id_"+i).val());
				if(new_item==items){		
					newqty = parseFloat($("#qty_"+i).val());
					newqty = parseFloat(newqty)+1;
					
					$("#qty_"+i).val(newqty);
					return false;
				}else{
					//index++;
				}
				
			}
			template='<tr id="row_order_'+index5+'" style="height:33px;">';
			var inp = '';
			
			template+='<td width="2%" class="center"><img onClick="deleteRecord('+index5+');" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
			template+='<td width="2%" class="center"><label id="lbno_'+index5+'">'+index+'<label></td>';
			template+='<td width="2%" class="center">'+rs.item_code+'<input type="hidden" name="item_id_'+index5+'" id="item_id_'+index5+'" value="'+rs.item_id+'" /></td>';
			//template+='<td><select class="form-control select2me" Onchange="ShowPopupProduct('+ index5 + ');" id="item_id_'+index5+'" name="item_id_'+index5+'" >'+option5+'<option></option></select>'+inp+'</td>';
			template+='<td width="2%" class="center">'+rs.item_name+'</td>';
			template+='<td><input type="text" class="form-control" required="1" id="qty_'+index5+'" name="qty_'+index5+'" value="1"></td>';
			template+='<td width="2%" class="center">'+rs.measure+'</td>';
			template+='<td width="2%" class="center"><input type="text" name="date_in_'+index5+'" id="date_in_'+index5+'" class="validate[required] form-control date-picker" /></td>';
			template+='<td><input type="text" class="form-control" id="remark_'+index5+'" name="remark_'+index5+'" /></span></td>';
			template+="</tr>";
			$('#table_order').append(template);
			//$('#item_id_'index5).select2me();
			if($('#identity').val()!="") {
				var identity = $('#identity').val();
				$('#identity').val(identity+','+index5);
			} else {$('#identity').val(index5);}
			$("#item_id_"+index5).val(item_id);
			$('#date_in_'+index5).datepicker();
			date = '<?php echo $date_now;?>';
			$('#date_in_'+index5).val(date);
			$("#row_order_0").remove();
			//newNo();
		},
		error:function(e){
							//alert(e);
		}
	});
	
}
<?php $url_code =  $this->url(array('module'=>'','controller'=>'ajax','action'=>'get-request-code')); ?>
function getRequestCode(){
	branch_id = $('#branch').val();
	$.ajax({
		url:"<?php echo $url_code;?>",
		type:"post",
		data:{'branch_id':branch_id},
		success: function(data){
			//alert(data);
			rs = $.parseJSON(data);	
			$('#request_no').val(rs);
		},
		error:function(e){
							//alert(e);
		}
	});
}
function getItemOrder(){
	item_ids=$("#add_item").val();
	$('#add_item').val('').trigger("liszt:updated");
	if(item_ids==-1){
		return false;
	}
	addRow(item_ids);
	$("#add_item").val("");
}
function deleteRecord(index) {
	
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	$("#row_order_"+index).remove();
	newNo()
}
function newNo(){
	a=0;
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) { a++;
		$('#lbno_'+arrays[i]).text(a);
		//$('#lbno'+arrays[i]).append(a);
	}
}
</script>