<?php 
	$url_new = $this->url(array('module'=>'product','controller'=>'location','action'=>'add',));
	$url_edit = $this->url(array('module'=>'product','controller'=>'location','action'=>'edit',));
	$url_delete = $this->url(array('module'=>'product','controller'=>'location','action'=>'delete',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
	
	$rs = $this->resulr;
?>
<title><?php echo $tr->translate("LOCAT_LIST");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("LOCAT_LIST");?>
				</div>
				<a href="<?php echo $url_new;?>" class="btn btn-sm green  pull-right">
					<i class="fa fa-plus"></i>&nbsp;<?php echo $tr->translate("ADD_NEW");?>
				</a>
			</div>
			
			<div class="portlet-body form">
				<form method="post" action="" >
				<div class="form-group" style="padding-top: 6px;">
					<label class="control-label col-md-4"><?php echo $formFilter->getElement('branch_name');?></label>
					<label class="control-label col-md-4"><?php echo $formFilter->getElement('status');?></label>
					<label class="control-label col-md-4">
						<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
					</label>
				</div>
				
				</form>
					<div class="contain_form" style="clear: both;">
						<?php echo $this->list; ?>
					</div>
		   </div>
		</div>
	</div>
</div>
