<?php 
	$user_info = new Application_Model_DbTable_DbGetUserInfo();
	$result = $user_info->getUserInfo();
	$tr = Application_Form_FrmLanguages::getCurrentlanguage(); 
	$session_user=new Zend_Session_Namespace('auth');
	$request=Zend_Controller_Front::getInstance()->getRequest();
	 $level = $result["level"];
	//must add edit it
	$url_pro_add =  array($this->url(array('module'=>'product','controller'=>'index','action'=>'add'),null, true), "MENU_PRODUCT_INDEX_ADD");
	$url_pro_list =  array($this->url(array('module'=>'product','controller'=>'index','action'=>'index'),null, true), "MENU_PRODUCT_INDEX_INDEX");
	$url_category =  array($this->url(array('module'=>'product','controller'=>'category','action'=>'index'),null, true), "MENU_PRODUCT_INDEX_CATEGORY");
	$url_brand = array($this->url(array('module'=>'product','controller'=>'brand','action'=>'index'),null, true), "MENU_PRODUCT_INDEX_BRAND");
	$url_curr =  array($this->url(array('module'=>'product','controller'=>'current-stock','action'=>'index'),null, true), "MENU_PRODUCT_CURRENT_STOCK_INDEX");
	$url_adj =  array($this->url(array('module'=>'product','controller'=>'adjust','action'=>'add'),null, true), "MENU_PRODUCT_ADJUST_STOCK_ADJUST");
	//$url_adj_price =  array($this->url(array('module'=>'product','controller'=>'adjust-stock','action'=>'price')), "MENU_PRODUCT_ADJUST_STOCK_ADJUST_PRICE");
	$url_transfer = array($this->url(array('module'=>'product','controller'=>'transfer','action'=>'index'),null, true), "MENU_PRODUCT_ADJUST_STOCK_TRANSFER_STOCK");
	$url_location = array($this->url(array('module'=>'product','controller'=>'branch','action'=>'index'),null, true), "MENU_PRODUCT_INDEX_INDEX_LOCATION");
	$url_other = array($this->url(array('module'=>'product','controller'=>'other','action'=>'index')), "MENU_OTHER");
	//$url_alert = array($this->url(array('module'=>'product','controller'=>'index','action'=>'itemalert')), "MENU_PRODUCT_INDEX_ITEMALERT");
	$url_deliver = array($this->url(array('module'=>'sales','controller'=>'delivery','action'=>'index')), "MENU_DELIVERY");
	
	$url_damagedstock = array($this->url(array('module'=>'product','controller'=>'damagedstock','action'=>'index')), "MENU_DAMAGED_STOCK");
	
	$request_transfer = array($this->url(array('module'=>'product','controller'=>'transfer','action'=>'requestlist'),null, true), "MENU_REQUEST_TRANSFER_LIST");
	$request_transfer_appr = array($this->url(array('module'=>'product','controller'=>'transfer','action'=>'requestappr'),null, true), "MENU_REQUEST_TRANSFER_APPROVE");
	$make_transfer_list = array($this->url(array('module'=>'product','controller'=>'transfer','action'=>'transferlist'),null, true), "MENU_MAKE_TRANSFER_LIST");
	$receive_transfer_list = array($this->url(array('module'=>'product','controller'=>'transfer','action'=>'receiverequest'),null, true), "MENU_RECEIVE_TRANSFER_LIST");
	
	//module purchase
	$url_purchase =  array($this->url(array('module'=>'purchase','controller'=>'index','action'=>'index'),null, true), "MENU_PURCHASE_INDEX_INDEX");
	$url_add_purchase = array($this->url(array('module'=>'purchase','controller'=>'index','action'=>'add'),null, true), "MENU_PURCHASE_INDEX_ADD_PURCHASE");
	$url_vendor = array($this->url(array('module'=>'purchase','controller'=>'vendor','action'=>'index'),null, true), "MENU_PURCHASE_VENDOR_INDEX");
	$url_vendor_add = array($this->url(array('module'=>'purchase','controller'=>'vendor','action'=>'add'),null, true), "MENU_PURCHASE_VENDOR_ADD");
	$url_return = array($this->url(array('module'=>'purchase','controller'=>'return','action'=>'index'),null, true), "MENU_PURCHASE_RETURN");
	$url_return_vendor_in = array($this->url(array('module'=>'purchase','controller'=>'return','action'=>'return-in')), "MENU_PURCHASE_RETURN_IN");
	$url_recieved  = array($this->url(array('module'=>'purchase','controller'=>'receive','action'=>'index'),null, true), "RECEIVE_STOCK");
	$url_purchase_approval = array($this->url(array('module'=>'purchase','controller'=>'purchaseapprove','action'=>'index')), "MENU_PURCHASE_APPROVAL");
	$url_audit_approval  = array($this->url(array('module'=>'purchase','controller'=>'auditapprove','action'=>'index'),null, true), "MENU_AUDIT_APPROVAL");
	
	$url_mr_request = array($this->url(array('module'=>'purchase','controller'=>'purchaserequest','action'=>'index'),null, true), "MENU_MR_REQUEST");
	$url_mr_check = array($this->url(array('module'=>'purchase','controller'=>'mrcheck','action'=>'index'),null, true), "MENU_MR_CHECK");
	$url_mr_app = array($this->url(array('module'=>'purchase','controller'=>'mrapprove','action'=>'index'),null, true), "MENU_MR_APPROVE");
	$url_make_price_compare= array($this->url(array('module'=>'purchase','controller'=>'compareprice','action'=>'addcompare'),null, true), "MENU_MR_MAKE_PRICE_COMPARE");
	$url_price_compare = array($this->url(array('module'=>'purchase','controller'=>'comparepricecheck','action'=>'index'),null, true), "MENU_MR_PRICE_COMPARE");
	$url_price_compare_app = array($this->url(array('module'=>'purchase','controller'=>'comparepriceapprove','action'=>'index'),null, true), "MENU_MR_PRICE_COMPARE_APPROVE");
	$url_make_purchase = array($this->url(array('module'=>'purchase','controller'=>'makepurchase','action'=>'index'),null, true), "MENU_MAKE_PURCHASE");
	$url_invoice_controling = array($this->url(array('module'=>'purchase','controller'=>'invoicecontrolling','action'=>'index'),null, true), "MENU_INVOICE_CONTROLLING");
	$url_pol = array($this->url(array('module'=>'purchase','controller'=>'payment','action'=>'index'),null, true), "MENU_PAYMENT_ORDER_LETTER");
	$url_pol_pay = array($this->url(array('module'=>'purchase','controller'=>'payment','action'=>'polpay'),null, true), "MENU_RECEIVE_POL");
	$url_pur_invoice = array($this->url(array('module'=>'purchase','controller'=>'receive','action'=>'makeinvoice'),null, true), "MENU_MAKE_PURCHASE_INVOICE");
	$url_party_cash = array($this->url(array('module'=>'purchase','controller'=>'partycash','action'=>'index'),null, true), "MENU_MAKE_PURCHASE_PARTY_CASH");
	$url_party_cash_purchase = array($this->url(array('module'=>'purchase','controller'=>'partycash','action'=>'partypurchase'),null, true), "MENU_PARTY_CASH_PURCHASE");
	
	// module sales
	$url_sales_list = array($this->url(array('module'=>'sales','controller'=>'index','action'=>'index'),null, true), "MENU_SALES_SALES_ORDER_INDEX");
	$url_sales_approved = array($this->url(array('module'=>'sales','controller'=>'salesapprove','action'=>'index'),null, true), "MENU_APPROVED");
	$url_invocie_approved = array($this->url(array('module'=>'sales','controller'=>'invoiceapprove','action'=>'index'),null, true), "MENU_APPROVED");
	$url_qoute_approved = array($this->url(array('module'=>'sales','controller'=>'quoteapprove','action'=>'index'),null, true), "MENU_QOUTEAPPROVED");
	
	$url_sales_add = array($this->url(array('module'=>'sales','controller'=>'index','action'=>'add'),null, true), "MENU_SALES_SALES_ORDER_ADD_CUSTOMER_ORDER");
	$url_quotelist = array($this->url(array('module'=>'sales','controller'=>'index','action'=>'index'),null, true), "QUOTATION_LIST");
	$url_sales_quote = array($this->url(array('module'=>'sales','controller'=>'index','action'=>'add'),null, true), "MENU_SALES_SALES_ORDER_ADD_CUSTOMER_QUOTE");
	$url_cust_list = array($this->url(array('module'=>'sales','controller'=>'customer','action'=>'index'),null, true), "MENU_SALES_CUSTOMER_INDEX");
	$url_add_cust = array($this->url(array('module'=>'sales','controller'=>'customer','action'=>'add'),null, true), "MENU_SALES_CUSTOMER_ADD");
	$url_sals_agent = array($this->url(array('module'=>'sales','controller'=>'saleagent','action'=>'index')), "MENU_SALES_AGENT");
	$url_return_in = array($this->url(array('module'=>'sales','controller'=>'return','action'=>'index'),null, true), "MENU_SALES_RETURN_INT");
	$url_return_out = array($this->url(array('module'=>'sales','controller'=>'return','action'=>'return-out'),null, true), "MENU_SALES_RETURN_OUT");
	$url_termcondiction= array($this->url(array('module'=>'sales','controller'=>'termcondiction','action'=>'index'),null, true), "MENU_SALES_TERMCONDICTION");
	$url_customer_type= array($this->url(array('module'=>'sales','controller'=>'customer','action'=>'customertypelist'),null, true), "MENU_CUSTOMER_TYPE");
	//module user 
	$url_user_list = array($this->url(array('module'=>'rsvacl','controller'=>'user','action'=>'index'),null, true), "MENU_RSVACL_USER_INDEX");
	$url_user_add = array($this->url(array('module'=>'rsvacl','controller'=>'user','action'=>'add'),null, true), "MENU_RSVACL_USER_ADD_USER");
	$url_add_user_access = array($this->url(array('module'=>'rsvacl','controller'=>'useraccess','action'=>'index'),null, true), "MENU_RSVACL_USER_ACCESS_ADD");
	$url_user_acl_list = array($this->url(array('module'=>'rsvacl','controller'=>'acl','action'=>'index'),null, true), "MENU_RSVACL_USER_ACL_LIST");
	$url_user_type = array($this->url(array('module'=>'rsvacl','controller'=>'usertype','action'=>'index'),null, true), "MENU_RSVACL_USER_TYPE_LIST");
	
	//module report$url_report_summary
	$url_report_user = array($this->url(array('module'=>'report','controller'=>'user','action'=>'index'),null, true), "MENU_REPORT_USER_INDEX");
	$url_report_list = array($this->url(array('module'=>'report','controller'=>'index','action'=>'index'),null, true), "MENU_REPORT_INDEX_INDEX");
	$url_report_product = array($this->url(array('module'=>'report','controller'=>'product','action'=>'index'),null, true), "MENU_REPORT_PRODUCT");
	$url_report_sale = array($this->url(array('module'=>'report','controller'=>'index','action'=>'index')), "MENU_REPORT_SALES_INDEX");
	$url_report_summary = array($this->url(array('module'=>'report','controller'=>'stock','action'=>'index')), "MENU_REPORT_INDEX_RPT_SUMMARY");
	$url_report_pro = array($this->url(array('module'=>'report','controller'=>'product','action'=>'index'),null, true), "MENU_REPORT_PRODUCT_INDEX");
	$url_report_purchase = array($this->url(array('module'=>'report','controller'=>'index','action'=>'rptpurchase'),null, true), "MENU_REPORT_PURCHASE_INDEX");
	$url_report_proches = array($this->url(array('module'=>'report','controller'=>'proches','action'=>'index'),null, true), "MENU_REPORT_PURCHASE_INDEX");
	$url_report_transfer = array($this->url(array('module'=>'report','controller'=>'index','action'=>'rpt-transfer'),null, true), "MENU_REPORT_INDEX_RPT-TRANSFER");
	$url_report_all_in_one = array($this->url(array('module'=>'report','controller'=>'index','action'=>'index'),null, true), "MENU_REPORT");
	$url_report_product = array($this->url(array('module'=>'report','controller'=>'product','action'=>'index'),null, true), "MENU_REPORT_PRODUCT");
	$url_chart_po =  array($this->url(array('module'=>'report','controller'=>'index','action'=>'pochart'),null, true), "MENU_REPORT_INDEX_POCHART");
	$url_chart_so =  array($this->url(array('module'=>'report','controller'=>'index','action'=>'sochart'),null, true), "MENU_REPORT_INDEX_SOCHART");
	$url_measure  = array($this->url(array('module'=>'product','controller'=>'measure','action'=>'index'),null, true), "Measure");
	$url_other  = array($this->url(array('module'=>'product','controller'=>'other','action'=>'index'),null, true), "Other");
	$url_pricelevel = array($this->url(array('module'=>'product','controller'=>'pricelevel','action'=>'index'),null, true), "Price Level");
	$module=$request->getModuleName();
	$class_active='start active open';
	
	$url_request = array($this->url(array('module'=>'purchase','controller'=>'siterequest','action'=>'index'),null, true), "SITE_ITEM_REQUEST");
	$url_request_check = array($this->url(array('module'=>'purchase','controller'=>'siterequest','action'=>'checklist'),null, true), "CHECK_SITE_ITEM_REQUEST");
	$url_request_deliver = array($this->url(array('module'=>'purchase','controller'=>'siterequest','action'=>'requestdelivery'),null, true), "DELIVER_SITE_ITEM_REQUEST");
	
	$url_plan_type = array($this->url(array('module'=>'sales','controller'=>'plantype','action'=>'index'),null, true), "PLAN_TYPE");
	$url_plan = array($this->url(array('module'=>'sales','controller'=>'plan','action'=>'index'),null, true), "PLAN");
	$url_plan_add = array($this->url(array('module'=>'sales','controller'=>'plan','action'=>'add'),null, true), "ADD_PLAN");
	$url_plan_edit = array($this->url(array('module'=>'sales','controller'=>'plan','action'=>'edit'),null, true), "EDIT_PLAN");
	
	$url_plan_print = array($this->url(array('module'=>'sales','controller'=>'plan','action'=>'printplan'),null, true), "PRINT_PLAN");
	$url_plan_check_list = array($this->url(array('module'=>'sales','controller'=>'plan','action'=>'planchecklist'),null, true), "CHECK_PLAN_LIST");
	$url_plan_check_ = array($this->url(array('module'=>'sales','controller'=>'plan','action'=>'plancheck'),null, true), "CHECK_PLAN");
	?>
<!-- BEGIN SIDEBAR -->
	<div class="page-sidebar-wrapper">
		<!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
		<!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
		<div class="page-sidebar navbar-collapse collapse">
			
			<ul class="page-sidebar-menu" data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
				<!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->
				<li class="sidebar-toggler-wrapper">
					<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
					<div class="sidebar-toggler">
					</div>
					<!-- END SIDEBAR TOGGLER BUTTON -->
				</li>
				<!-- DOC: To remove the search box from the sidebar you just need to completely remove the below "sidebar-search-wrapper" LI element -->
				<?php if($level==1 OR $level==4  OR $level==9 ){?>
				<li class="<?php if($module=='product'){echo $class_active;}?>">
					<a href="javascript:;">
					<i class="icon-home"></i>
					<span class="title"><?php echo $tr->translate("INVENTORY")?></span>
					<span class="arrow "></span>
					</a>
					<ul class="sub-menu">
						<li>
							<a href="<?php echo $url_pro_add[0]; ?>">
							<i class="icon-bar-chart"></i><?php echo $tr->translate($url_pro_add[1])?></a>
						</li>
						<li>
							<a href="<?php echo $url_pro_list[0]; ?>">
							<i class="icon-bulb"></i><?php echo $tr->translate($url_pro_list[1])?></a>
						</li>
						<li>
							<a href="<?php echo $url_damagedstock[0]; ?>">
							<i class="icon-bulb"></i><?php echo $tr->translate($url_damagedstock[1])?></a>
						</li>
						<!-- <li>
							<a href="<?php //echo $url_curr[0]; ?>">
							<i class="icon-graph"></i><?php //echo $tr->translate($url_curr[1])?></a>
						</li> -->
						<?php //if($result["level"]==3 ){ ?>
	            		<!--<li>
	            			<a href="<?php //echo $url_adj[0]; ?>">
							      <i class="icon-bulb"></i>  <?php //echo $tr->translate($url_adj[1])?>
		            		</a>
	            		</li>
	            		<li>
	            			<a href="<?php echo $url_transfer[0]; ?>">
							      <i class="icon-bulb"></i><?php echo $tr->translate($url_transfer[1])?>
		            		</a>
	            		</li>-->
	            		<?php if($result["level"]==1 OR $result["level"]==2 ){ ?>
	            		<li>
	            			<a href="<?php echo $url_adj[0]; ?>">
							    <i class="icon-bulb"></i><?php echo $tr->translate($url_adj[1])?>
		            		</a>
	            		</li>
						<?php }?>
						<!-- 
	            		<li>
	            			<a href="<?php //echo $url_transfer[0]; ?>">
							    <i class="icon-bulb"></i><?php //echo $tr->translate($url_transfer[1])?>
		            		</a>
	            		</li> -->
	            		<li>
	            			<a href="<?php echo $url_category[0]; ?>">
							      <i class="icon-bulb"></i><?php echo $tr->translate($url_category[1]);?>
		            		</a>
	            		</li>
	            		<li>
	            			<a href="<?php echo $url_brand[0]; ?>">
							   <i class="icon-bulb"></i> <?php echo $tr->translate($url_brand[1]);?>
		            		</a>
	            		</li>
	            		 <li>
	            			<a href="<?php echo $url_pricelevel[0]; ?>">
							    <i class="icon-bulb"></i><?php echo $tr->translate($url_pricelevel[1]);?></a>
	            		<li> 
	            		<li>
	            			<a href="<?php echo $url_other[0]; ?>">
							    <i class="icon-bulb"></i> <?php echo $tr->translate($url_other[1]);?>
		            		</a>
	            		</li>
						<!--<li>
	            			<a href="<?php echo $url_deliver[0]; ?>">
							 <i class="icon-bulb"></i><?php echo $tr->translate($url_deliver[1])?></a>
	            		</li>-->
						<li>
	            			<a href="<?php echo $url_recieved[0]; ?>">
		            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_recieved[1]);?>
		            		</a>
	            		</li>
	            		<!--<li>
	            			<a href="<?php //echo $url_alert[0]; ?>">
							 <i class="icon-bulb"></i><?php //echo $tr->translate($url_alert[1])?>
	            		<li>
	            			<a href="<?php echo $url_measure[0]; ?>">
							 <i class="icon-bulb"></i><?php echo $tr->translate($url_measure[1])?></a>
	            		<li>
	            		<li>
	            			<a href="<?php echo $url_other[0]; ?>">
							 <i class="icon-bulb"></i><?php echo $tr->translate($url_other[1])?></a>
	            		<li>
            		<?php //}?>   
            		<?php //}?>-->
            		<li>
	            			<a href="<?php echo $url_measure[0]; ?>">
							 <i class="icon-bulb"></i><?php echo $tr->translate($url_measure[1])?></a>
	            		<li>
						
						<hr />
					<li>
	            			<a href="<?php echo $request_transfer[0]; ?>">
							      <i class="icon-bulb"></i><?php echo $tr->translate($request_transfer[1])?>
		            		</a>
	            		</li>
						<?php if($level==1 or $level==2){?>
					<li>
	            			<a href="<?php echo $request_transfer_appr[0]; ?>">
							      <i class="icon-bulb"></i><?php echo $tr->translate($request_transfer_appr[1])?>
		            		</a>
	            		</li>
						<?php }?>
					<li>
	            			<a href="<?php echo $make_transfer_list[0]; ?>">
							      <i class="icon-bulb"></i><?php echo $tr->translate($make_transfer_list[1])?>
		            		</a>
	            		</li>
						<li>
	            			<a href="<?php echo $receive_transfer_list[0]; ?>">
							      <i class="icon-bulb"></i><?php echo $tr->translate($receive_transfer_list[1])?>
		            		</a>
	            		</li>
					</ul>
				</li>
				<?php }?>
				<?php if($level==1 OR $level==8){?>
				<li class="<?php if($module=='purchase'){echo $class_active;}?>">
					<a href="javascript:;">
					<i class="icon-screen-desktop"></i>
					<span class="title"><?php echo $tr->translate("PURCHASING")?></span>
					<span class="arrow "></span>
					</a>
					<ul class="sub-menu">
						<li>
            				<a href="<?php echo $url_mr_request[0]; ?>">
						        <i class="icon-arrow-right"></i><?php echo $tr->translate($url_mr_request[1]);?>
	            			</a>
	            		</li>
						<li>
            				<a href="<?php echo $url_mr_check[0]; ?>">
						        <i class="icon-arrow-right"></i><?php echo $tr->translate($url_mr_check[1]);?>
	            			</a>
	            		</li>
						<!--<li>
            				<a href="<?php echo $url_mr_app[0]; ?>">
						        <i class="icon-arrow-right"></i><?php echo $tr->translate($url_mr_app[1]);?>
	            			</a>
	            		</li>-->
						<li>
            				<a href="<?php echo $url_make_price_compare[0]; ?>">
						        <i class="icon-arrow-right"></i><?php echo $tr->translate($url_make_price_compare[1]);?>
	            			</a>
	            		</li>
						<li>
            				<a href="<?php echo $url_price_compare[0]; ?>">
						        <i class="icon-arrow-right"></i><?php echo $tr->translate($url_price_compare[1]);?>
	            			</a>
	            		</li>
						<li>
            				<a href="<?php echo $url_price_compare_app[0]; ?>">
						        <i class="icon-arrow-right"></i><?php echo $tr->translate($url_price_compare_app[1]);?>
	            			</a>
	            		</li>
						<li>
            				<a href="<?php echo $url_make_purchase[0]; ?>">
						        <i class="icon-arrow-right"></i><?php echo $tr->translate($url_make_purchase[1]);?>
	            			</a>
	            		</li> 
						<li>
            				<a href="<?php echo $url_purchase[0]; ?>">
						        <i class="icon-arrow-right"></i><?php echo $tr->translate($url_purchase[1]);?>
	            			</a>
	            		</li> 
	            		<!--<li>
	            			<a href="<?php echo $url_add_purchase[0]; ?>">
							         <i class="icon-arrow-right"></i><?php echo $tr->translate($url_add_purchase[1]);?>
		            		</a>
	            		</li> -->
	            		<?php if($result["level"]==1 OR $result["level"]==2){?>
	            		<!-- 
	            		
	            		<li>
	            			<a href="<?php echo $url_return[0]; ?>">
							         <i class="icon-arrow-right"></i><?php echo $tr->translate($url_return[1]);?>
		            		</a>
	            		</li> 
	            		<li>
	            			<a href="<?php echo $url_return_vendor_in[0]; ?>">
		            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_return_vendor_in[1]);?>
		            		</a>
	            		</li> -->
	            		<li>
	            			<a href="<?php echo $url_recieved[0]; ?>">
		            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_recieved[1]);?>
		            		</a>
	            		</li> 
						<li>
	            			<a href="<?php echo $url_pur_invoice[0]; ?>">
		            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_pur_invoice[1]);?>
		            		</a>
	            		</li> 
						<li>
	            			<a href="<?php echo $url_invoice_controling[0]; ?>">
		            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_invoice_controling[1]);?>
		            		</a>
	            		</li> 	
						<li>
	            			<a href="<?php echo $url_pol[0]; ?>">
		            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_pol[1]);?>
		            		</a>
	            		</li>
						
						<li>
	            			<a href="<?php echo $url_pol_pay[0]; ?>">
		            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_pol_pay[1]);?>
		            		</a>
	            		</li>

						<li>
	            			<a href="<?php echo $url_party_cash[0]; ?>">
		            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_party_cash[1]);?>
		            		</a>
	            		</li>	
						<li>
	            			<a href="<?php echo $url_party_cash_purchase[0]; ?>">
		            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_party_cash_purchase[1]);?>
		            		</a>
	            		</li>	
	            		
	            		<li>
	            			<a href="<?php echo $url_vendor[0]; ?>">
		            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_vendor[1])?>
		            		</a>
	            		</li> 
	            		<!--<li>
	            			<a href="<?php echo $url_vendor_add[0]; ?>">
		            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_vendor_add[1]);?>
		            		</a>
	            		</li>-->
						
						<!--<li>
	            			<a href="<?php echo $url_purchase_approval[0]; ?>">
		            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_purchase_approval[1])?>
		            		</a>
	            		</li> 
	            		<li>
	            			<a href="<?php echo $url_audit_approval[0]; ?>">
		            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_audit_approval[1]);?>
		            		</a>
	            		</li> -->
	            		
	            		<?php }?>

	            		</li> 
						
						
							<li>
	            			<a href="<?php echo $this->url(array('module'=>'purchase','controller'=>'expensetitle','action'=>'index'),null, true); ?>">
		            			<i class="icon-arrow-right"></i><?php echo $tr->translate("EXPENSE_TITLE");?>
		            		</a>
	            		</li> 
	            		<?php //}?>

					</ul>
				</li>
				<?php }?>
				<?php if($level==1 OR $level==3 OR $level==10 OR $level==5 OR $level==2 OR $level==6){?>
				<li  class="<?php if($module=='sales'){echo $class_active;}?>">
					<a href="javascript:;">
					<i class="icon-screen-desktop"></i>
					<span class="title"><?php echo strtoupper($tr->translate("SALES")); ?></span>
					<span class="arrow "></span>
					</a>
					<ul class="sub-menu">
					<li>
							<a href="<?php echo $url_plan_type[0]; ?>">
								<i class="icon-arrow-right"></i><?php echo $tr->translate($url_plan_type[1]);?>
							</a>
						</li>
						<li>
							<a href="<?php echo $url_plan[0]; ?>">
								<i class="icon-arrow-right"></i><?php echo $tr->translate($url_plan[1]);?>
							</a>
						</li>
						<li>
							<a href="<?php echo $url_plan_check_list[0]; ?>">
								<i class="icon-arrow-right"></i><?php echo $tr->translate($url_plan_check_list[1]);?>
							</a>
						</li> 
						<li>
            			<a href="<?php echo $url_sales_list[0]; ?>">
						    <i class="icon-arrow-right"></i><?php echo $tr->translate($url_sales_list[1]);?>
	            		</a>
            		</li> 
            		<li>
            			<a href="<?php echo $this->url(array('module'=>'sales','controller'=>'costprice','action'=>'index'),null, true);?>">
						    <i class="icon-arrow-right"></i>Build of Selling Price
						</a>
            		</li> 
            		<li>
            			<a href="<?php echo $this->url(array('module'=>'sales','controller'=>'selling','action'=>'index'),null, true);?>">
						    <i class="icon-arrow-right"></i>Build of Quote List(BOQ)
						</a>
            		</li> 
            		<li>
            			<a href="<?php echo $this->url(array('module'=>'sales','controller'=>'invoiceapprove','action'=>'index'),null, true);?>">
						    <i class="icon-arrow-right"></i>BOQ Aproval
						</a>
            		</li> 
	            	<li>
            			<a href="<?php echo $url_cust_list[0]; ?>">
						    <i class="icon-arrow-right"></i><?php echo $tr->translate($url_cust_list[1]);?>
	            		</a>
            		</li> 
            		<li>
            			<a href="<?php echo $url_add_cust[0]; ?>">
	            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_add_cust[1])?>
	            		</a>
            		</li>
					<!--
					<li>
            			<a href="<?php echo $url_quotelist[0]; ?>">
	            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_quotelist[1])?>
	            	    </a>
            		</li> 
            		<li>
            			<a href="<?php echo $url_sales_quote[0]; ?>">
	            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_sales_quote[1])?>
	            		</a>
            		</li>
					<li>
            			<a href="<?php echo $url_qoute_approved[0]; ?>">
	            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_qoute_approved[1])?>
	            	</a>
	            	</li>
					<li>
            			<a href="<?php echo $this->url(array('module'=>'sales','controller'=>'comment','action'=>'index'),null, true); ?>">
	            			<i class="icon-arrow-right"></i><?php echo $tr->translate("CUSTOMER_COMMENT");?>
	            		</a>
            		</li>
					<?php if($level==1  OR $level==2){?>
					 <li>
            			<a href="<?php echo $url_customer_type[0]; ?>">
	            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_customer_type[1])?>
	            		</a>
            		</li> -->
					<?php }?>
					</ul>
				</li>
				<?php }?>
				<?php if($level==1 OR $level==3 OR $level==10){?>
				<li>
					<a href="javascript:;">
					<i class="icon-screen-desktop"></i>
					<span class="title"><?php echo strtoupper($tr->translate("Acct Payable/Payment")); ?></span>
					<span class="arrow "></span>
					</a>
					<ul class="sub-menu">
						<li>
            			<a href="<?php echo $url_sales_list[0]; ?>">
						    <i class="icon-arrow-right"></i><?php echo $tr->translate($url_sales_list[1]);?>
	            		</a>
            		</li> 
					
            		<?php //};?>
            		<li>
            			<a href="<?php echo $url_invocie_approved[0]; ?>">
	            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_invocie_approved[1])?>
	            		</a>
            		</li>
            		<!-- <li>
            			<a href="<?php //echo $url_sales_approved[0]; ?>">
	            			<i class="icon-arrow-right"></i><?php //echo $tr->translate($url_sales_approved[1])?>
	            		</a>
            		</li> -->
            		<li>
            			<a href="<?php echo $this->url(array('module'=>'sales','controller'=>'payment','action'=>'index'),null, true); ?>">
	            			<i class="icon-arrow-right"></i><?php echo $tr->translate("CUSTOMER_PAYMENT");?>
	            		</a>
            		</li>
					<li>
            			<a href="<?php echo $this->url(array('module'=>'sales','controller'=>'comment','action'=>'index'),null, true); ?>">
	            			<i class="icon-arrow-right"></i><?php echo $tr->translate("CUSTOMER_COMMENT");?>
	            		</a>
            		</li>
            		<li>
            			<a href="<?php echo $url_termcondiction[0]; ?>">
	            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_termcondiction[1]);?>
	            		</a>
            		</li>
					</ul>
				</li>
				<?php }?> 
				
				<?php 
				if($level==1 OR $level==2 OR $level==5 OR $level==6){?>
				<li class="<?php if($module=='dailywork'){echo $class_active;}?>">
					<a href="javascript:;">
					<i class="icon-screen-desktop"></i>
					<span class="title">DAILY ACTIVITIES</span>
					<span class="arrow "></span>
					</a>
					<ul class="sub-menu">
						<li>
	            			<a href="<?php echo $this->url(array('module'=>'dailywork','controller'=>'index','action'=>'index'),null, true); ?>">
							    <i class="icon-arrow-right"></i>Daily Planning
		            		</a>
            			</li> 
						<?php if($level==1){?>
						<li>
	            			<a href="<?php echo $this->url(array('module'=>'dailywork','controller'=>'project','action'=>'index'),null, true); ?>">
							    <i class="icon-arrow-right"></i>Work Category
		            		</a>
            			</li>
						<?php } ?>
						<li>
	            			<a href="<?php echo $this->url(array('module'=>'dailywork','controller'=>'workprocess','action'=>'index'),null, true); ?>">
							    <i class="icon-arrow-right"></i>Daily Aativities
		            		</a>
            			</li> 
            			<li>
	            			<a href="<?php echo $this->url(array('module'=>'dailywork','controller'=>'workcomplete','action'=>'index'),null, true); ?>">
							    <i class="icon-arrow-right"></i>Work Completed
		            		</a>
            			</li>	
            			<!--<li>
	            			<a href="<?php //echo $this->url(array('module'=>'dailywork','controller'=>'category','action'=>'index'),null, true); ?>">
							    <i class="icon-arrow-right"></i>Category
		            		</a>
            			</li> 
            			<li>
	            			<a href="<?php //echo $this->url(array('module'=>'dailywork','controller'=>'address','action'=>'index'),null, true); ?>">
							    <i class="icon-arrow-right"></i>Address
		            		</a>
            			</li>-->
            			<li>
	            			<a href="<?php echo $this->url(array('module'=>'dailywork','controller'=>'contact','action'=>'index'),null, true); ?>">
							    <i class="icon-arrow-right"></i>Contact Person
		            		</a>
            			</li>  
            			<li>
	            			<a href="<?php echo $this->url(array('module'=>'dailywork','controller'=>'result','action'=>'index'),null, true); ?>">
							    <i class="icon-arrow-right"></i>Daily Send Email
		            		</a>
            			</li> 
            		 </ul>
            	</li>
				<?php }?>
				<li class="<?php if($module=='report'){echo $class_active;}?>">
					<a href="javascript:;">
					<i class="icon-screen-desktop"></i>
					<span class="title"><?php echo strtoupper($tr->translate("REPORT"));?></span>
					<span class="arrow "></span>
					</a>
					<ul class="sub-menu">
					<?php //if($level==1 OR $level==4 OR $level==5 OR $level==2 OR $level==6){//admin and stock mg?> 
            		<li>
            			<a href="<?php echo $url_report_product[0];?>">
	            			<i class="icon-arrow-right"></i><?php echo $tr->translate( $url_report_product[1]);?>
	            		</a>
            		</li>
            		<?php //}?>
            		<?php if($level!=4 AND $level!=9){//admin and stock mg?> 
            		<li>
            			<a href="<?php echo $url_report_all_in_one[0];?>">
	            			<i class="icon-arrow-right"></i><?php echo $tr->translate( $url_report_all_in_one[1]);?>
	            		</a>
            		</li>
					<li>
	            			<a href="<?php echo $url_report_proches[0]; ?>">
		            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_report_proches[1]);?>
		            		</a>
	            		</li>
	            		<li>
	            			<a href="<?php echo $url_report_summary[0]; ?>">
		            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_report_summary[1]);?>
		            		</a>
	            		</li> 
	            		<li>
	            			<a href="<?php echo $url_report_transfer[0]; ?>">
		            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_report_transfer[1]);?>
		            		</a>
	            		</li> 
	            		
            		<?php }?>
				</li>
				</ul>
				<?php if($level==1){?>
				<li>
					<a href="javascript:;">
					<i class="icon-screen-desktop"></i>
					<span class="title"><?php echo strtoupper($tr->translate("Admin&User Access"));?></span>
					<span class="arrow "></span>
					</a>
					<ul class="sub-menu">
						<li>
	            			<a href="<?php echo $url_user_list[0]; ?>">
		            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_user_list[1]);?>
		            		</a>
	            		</li> 
	            		<li>
            			<a href="<?php echo $url_sals_agent[0]; ?>">
	            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_sals_agent[1]);?>
	            		</a>
            		    </li>
            		    <li>
	            			<a href="<?php echo $url_location[0]; ?>">
							    <i class="icon-bulb"></i> <?php echo $tr->translate($url_location[1]);?>
		            		</a>
	            		</li>
	            		<li>
	            			<a href="<?php echo $url_user_add[0]; ?>">
		            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_user_add[1]);?>
		            		</a>
	            		</li> 
	            		<li>
	            			<a href="<?php echo $url_add_user_access[0]; ?>">
		            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_add_user_access[1]);?>
		            		</a>
	            		</li>
	            		<li>
	            			<a href="<?php echo $url_user_acl_list[0]; ?>">
		            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_user_acl_list[1]);?>
		            		</a>
	            		</li> 
	            		<li>
	            			<a href="<?php echo $url_user_type[0]; ?>">
		            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_user_type[1]);?>
		            		</a>
	            		</li> 
					</ul>
				</li>
				<?php }?>
				
				<li>
					<a href="javascript:;">
					<i class="icon-screen-desktop"></i>
					<span class="title"><?php echo strtoupper($tr->translate("SITE_ITEM_REQUEST"));?></span>
					<span class="arrow "></span>
					</a>
					<ul class="sub-menu">
						<li>
	            			<a href="<?php echo $url_request[0]; ?>">
		            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_request[1]);?>
		            		</a>
	            		</li> 
	            		<li>
            			<a href="<?php echo $url_request_check[0]; ?>">
	            			<i class="icon-arrow-right"></i><?php echo $tr->translate($url_request_check[1]);?>
	            		</a>
            		    </li>
            		    <li>
	            			<a href="<?php echo $url_request_deliver[0]; ?>">
							    <i class="icon-bulb"></i> <?php echo $tr->translate($url_request_deliver[1]);?>
		            		</a>
	            		</li>
	            		
					</ul>
				</li>
			</ul>
		</div>
	</div>