<?php 
defined('BASE_URL')	|| define('BASE_URL', Zend_Controller_Front::getInstance()->getBaseUrl());
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$form=$this->form;
	$url_submit =  $this->url(array('module'=>'product','controller'=>'plantype','action'=>'add'));
    $url_cencel =  $this->url(array('module'=>'product','controller'=>'index','action'=>'index'));
    $url_check =  $this->url(array('module'=>'product','controller'=>'index','action'=>'check'));
    $url_new = $this->url(array('module'=>'product','controller'=>'index','action'=>'add'));
?>						 
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>  -->
<title><?php echo $tr->translate("ADD_NEW_ITEM");?></title>
<body>
	<form class="form-horizontal" method="post" id="a" action="<?php echo $url_submit;?>" >				
					<div class="portlet box blue">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-gift"></i><?php echo $tr->translate("ADD_NEW_PRODUCT");?>
							</div>
							<div class="tools">
									<label><a href="<?php echo $url_cencel;?>"><button type="button" name="calcel" class="btn red"><i class="fa fa-times"></i><?php echo $tr->translate("GO_BACK");?></button></a></label>
							</div>
						</div>
						<div class="portlet-body">
							<div class="tabbable-custom ">
								
								<div class="tab-content">
									<div class="tab-pane active" id="tab_5_1">
									<!--<div class="portlet box blue">
								<div class="portlet-title">
									<div class="caption">
											<i class="fa fa-globe"></i><?php echo $tr->translate("PRODUCT_INFO");?>
									</div>
									
								</div>-->
								<div class="portlet-body form">
									 
										<div class="form-body">
													
													 
													<div class="form-group">
															<label class="col-md-2 control-label"><?php echo $tr->translate("Name");?></label>
														<div class="col-md-4">
															<?php echo $form->getElement('nametype');?>
														</div>
															
															<label class="col-md-2 control-label"><?php echo $tr->translate("STATUS");?></label>
														<div class="col-md-4">
															<?php echo $form->getElement('status');?>
														</div>
														
													</div>
														
										<div class="form-group">
											<label  class="col-md-12 col-md-offset-4 col-md-8">
												<a href="<?php echo $this->baseUrl();?>/sales/saleagent"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
												<button type="submit" name="save_close" id="save_close" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
												<button type="submit" name="btnsavenew" id="save_close" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
												
											</label>
										</div>
							<!--</div>-->
									</div>
									
								</div>
							</div>
							
						</div>
					</div>
							
			</form>	



			      
<script>
$( document ).ready(function() {
	addProLocation();
	//addPriceType();
	addNewPriceType();
	
});

	function getMeasureLabel(){
		var sel = $("#measure");
		var text = $("option:selected",sel).text();
		document.getElementById('lb_measure').innerHTML = text; 
	}
	index = 0;
	function addProLocation(){
		<?php if(!empty($this->branch)){foreach ($this->branch as $key=> $rs){?>
		index++;
		id = '<?php echo $rs["id"];?>';
		inx = '<?php echo $key+1;?>';
			template='<tr id="row_location_<?php echo $key+1;?>">';
			template+='<td><?php echo $key+1;?></td>';
			template+='<td><?php echo $rs["name"];?><input type="hidden" id="branch_id_<?php echo $key+1;?>" name="branch_id_<?php echo $key+1;?>" value="'+id+'"</td>';
			template+='<td><input type="text" id="current_qty_<?php echo $key+1;?>" name="current_qty_<?php echo $key+1;?>" value="0" class="form-control"></td>'; 
			template+='<td><input type="text" id="qty_warning_<?php echo $key+1;?>" name="qty_warnning_<?php echo $key+1;?>" value="0" class="form-control"></td>';
			template+='<td><button type="button" onClick="deleteRecord(<?php echo $key+1;?>,1)" name="save_close" class="btn default"><?php echo $tr->translate("DELETE");?></button></td>';
			template+='</tr>';
			$('#tr_location').append(template);
			if($('#identity').val()!="") {
				var identity = $('#identity').val();
				$('#identity').val(identity+','+inx);
			} else {$('#identity').val(inx);}
		<?php }}?>
	}
	
	function addNewProLocation(){
			index++;
			var branch_text = $("#branch");
			var txt_br = $("option:selected",branch_text).text();
			var branch_id = $("#branch").val();
			template='<tr id="row_location_'+index+'">';
			template+='<td>'+index+'</td>';
			template+='<td>'+txt_br+'<input type="hidden" id="branch_id_'+index+'" name="branch_id_'+index+'" value="'+branch_id+'" </td>';
			template+='<td><input type="text" id="current_qty_'+index+'" name="current_qty_'+index+'" value="0" class="form-control"></td>'; 
			template+='<td><input type="text" id="qty_warning_'+index+'" name="qty_warnning_'+index+'" value="0" class="form-control"></td>';
			template+='<td><button type="button" onClick="deleteRecord('+index+',1)" name="save_close" class="btn default"><?php echo $tr->translate("DELETE");?></button></td>';
			template+='</tr>';
			$('#tr_location').append(template);
			if($('#identity').val()!="") {
				var identity = $('#identity').val();
				$('#identity').val(identity+','+index);
			} else {$('#identity').val(index);}
			
	}
	
	function addPriceType(){
		<?php if(!empty($this->price_type)){foreach ($this->price_type as $key=> $rs){?>
		indexs++;
		id_price = '<?php echo $rs["id"];?>';
		inx_price = '<?php echo $key+1;?>';
			template='<tr id="row_price_<?php echo $key+1;?>">';
			template+='<td><?php echo $key+1;?></td>';
			template+='<td><?php echo $rs["name"];?><input type="hidden" id="price_type_<?php echo $key+1;?>" name="price_type_<?php echo $key+1;?>" value="'+id_price+'"</td>';
			template+='<td><input type="text" id="price_<?php echo $key+1;?>" name="price_<?php echo $key+1;?>" value="0" class="form-control"></td>'; 
			template+='<td><input type="text" id="price_remark_<?php echo $key+1;?>" name="price_remark_<?php echo $key+1;?>" class="form-control"></td>'; 
			template+='<td><button type="button" onClick="deleteRecord(<?php echo $key+1;?>,2)" name="save_close" class="btn default"><?php echo $tr->translate("DELETE");?></button></td>';
			template+='</tr>';
			$('#tr_price_type').append(template);
			if($('#identity_price').val()!="") {
				var identity_price = $('#identity_price').val();
				$('#identity_price').val(identity_price+','+inx_price);
			} else {$('#identity_price').val(inx_price);}
		<?php }}?>
	}
	
	indexs=0;
	function addNewPriceType(){
			indexs++;
			var price_text = $("#price_type");
			var txt_pr = $("option:selected",price_text).text();
			var price_id = $("#price_type").val();
			template='<tr id="row_price_'+indexs+'">';
			template+='<td>'+indexs+'</td>';
			template+='<td>'+txt_pr+'<input type="hidden" id="price_type_'+indexs+'" name="price_type_'+indexs+'" value="'+price_id+'" </td>';
			template+='<td><input type="text" id="price_'+indexs+'" name="price_'+indexs+'" value="0" class="form-control"></td>'; 
			template+='<td><input type="text" id="price_remark_'+indexs+'" name="price_remark_'+indexs+'" class="form-control"></td>'; 
			template+='<td><button type="button" onClick="deleteRecord('+indexs+',2)" name="save_close" class="btn default"><?php echo $tr->translate("DELETE");?></button></td>';
			template+='</tr>';
			$('#tr_price_type').append(template);
			if($('#identity_price').val()!="") {
				var identity_price = $('#identity_price').val();
				$('#identity_price').val(identity_price+','+indexs);
			} else {$('#identity_price').val(indexs);}
			
	}
	function deleteRecord(index,type) {
		if(type==1){
			var identity = $('#identity').val();
			var arrays = identity.split(',');
		}else{
			var identity = $('#identity_price').val();
			var arrays = identity.split(',');
		}
		
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		
		if(type==1){
			$('#identity').val(strings);
			$("#row_location_"+index).remove();
		}else{
			$('#identity_price').val(strings);
			$("#row_price_"+index).remove();
		}
		

		// total price
	}
	
	function getPopupBrand(){
		val = $('#brand').val();
		if(val==-1){
			$('#brandpopup').modal('show');
		}
	}
	
	function getPopupCategory(){
		val = $('#category').val();
		if(val==-1){
			$('#categorypopup').modal('show');
		}
	}
	
	function getPopupMeasure(){
		val = $('#measure').val();
		if(val==-1){
			$('#measurepopup').modal('show');
		}
	}
	
	function getPopupColor(){
		val = $('#color').val();
		if(val==-1){
			$('#otherpopup').modal('show');
			$('#type').val(4);
			$('#type').attr('readOnly',true);
			$('#savemodel').hide();
			$('#savesize').hide();
			$('#savecolor').show();
		}
	}
	
	function getPopupModel(){
		val = $('#model').val();
		if(val==-1){
			$('#otherpopup').modal('show');
			$('#type').val(2);
			$('#type').attr('readOnly',true);
			$('#savecolor').hide();
			$('#savesize').hide();
			$('#savemodel').show();
		}
	}
	
	function getPopupSize(){
		val = $('#size').val();
		if(val==-1){
			$('#otherpopup').modal('show');
			$('#type').val(3);
			$('#type').attr('readOnly',true);
			$('#savemodel').hide();
			$('#savecolor').hide();
			$('#savesize').show();
		}
	}
	
	<?php $url_add_brand =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-brand')); ?>
	function addNewBrand(){
		//alert(1);
		var brand_name  = $("#brand_name").val();
		$.ajax({
			url: "<?php echo $url_add_brand;?>",
			type: "post",
			data: $('#frmbrand').serialize(),
			success: function(data){
				rs = $.parseJSON(data);
				 $('#brand').append($("<option></option>").attr("value",rs['brand_id']).attr("selected",true).text(brand_name));                       
				 $("#brand").select2();
				$('#brandpopup').modal('hide');
			},
			error:function(err){
				alert("faile insert");
			   
			}
		});
	}
	
	<?php $url_add_category =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-category')); ?>
	function addNewCategory(){
		//alert(1);
		var cat_name  = $("#cat_name").val();
		$.ajax({
			url: "<?php echo $url_add_category;?>",
			type: "post",
			data: $('#frmCat').serialize(),
			success: function(data){
				rs = $.parseJSON(data);
				 $('#category').append($("<option></option>").attr("value",rs['cat_id']).attr("selected",true).text(cat_name));                       
				 $("#category").select2();
				$('#categorypopup').modal('hide');
			},
			error:function(err){
				alert("faile insert");
			   
			}
		});
	}
	
	<?php $url_add_measure =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-measure')); ?>
	function addNewMeasure(){
		//alert(1);
		var measure_name  = $("#measure_name").val();
		$.ajax({
			url: "<?php echo $url_add_measure;?>",
			type: "post",
			data: $('#frmMesure').serialize(),
			success: function(data){
				rs = $.parseJSON(data);
				 $('#measure').append($("<option></option>").attr("value",rs['measure_id']).attr("selected",true).text(measure_name));                       
				 $("#measure").select2();
				$('#measurepopup').modal('hide');
			},
			error:function(err){
				alert("faile insert");
			   
			}
		});
	}
	
	<?php $url_add_color =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-other')); ?>
	function addNewColor(){
		//alert(1);
		var title  = $("#title_en").val();
		$.ajax({
			url: "<?php echo $url_add_color;?>",
			type: "post",
			data: $('#frmOther').serialize(),
			success: function(data){
				rs = $.parseJSON(data);
				 $('#color').append($("<option></option>").attr("value",rs['other_id']).attr("selected",true).text(title));                       
				 $("#color").select2();
				$('#otherpopup').modal('hide');
			},
			error:function(err){
				alert("faile insert");
			   
			}
		});
	}
	
	function addNewModel(){
		//alert(1);
		var title  = $("#title_en").val();
		$.ajax({
			url: "<?php echo $url_add_color;?>",
			type: "post",
			data: $('#frmOther').serialize(),
			success: function(data){
				rs = $.parseJSON(data);
				 $('#model').append($("<option></option>").attr("value",rs['other_id']).attr("selected",true).text(title));                       
				 $("#model").select2();
				$('#otherpopup').modal('hide');
			},
			error:function(err){
				alert("faile insert");
			   
			}
		});
	}
	
	function addNewSize(){
		//alert(1);
		var title  = $("#title_en").val();
		$.ajax({
			url: "<?php echo $url_add_color;?>",
			type: "post",
			data: $('#frmOther').serialize(),
			success: function(data){
				rs = $.parseJSON(data);
				 $('#size').append($("<option></option>").attr("value",rs['other_id']).attr("selected",true).text(title));                       
				 $("#size").select2();
				$('#otherpopup').modal('hide');
			},
			error:function(err){
				alert("faile insert");
			   
			}
		});
	}
<?php $url_code =  $this->url(array('module'=>'product','controller'=>'index','action'=>'get-product-prefix')); ?>
function getProductPrefix(){
				id=$("#category").val();
				
				$.ajax({
						url:"<?php echo $url_code;?>",
						type:"post",
						data:{'id':id},
						success: function(data){
							value = $.parseJSON(data);
								$("#pro_code").val(value);
						},
						error:function(e){
							alert(e);
						}
					});
}
</script>
			
</body>
</html>

