<?php 
	$url_new = $this->url(array('module'=>'product','controller'=>'plan','action'=>'add',));
	$url_edit = $this->url(array('module'=>'product','controller'=>'plan','action'=>'edit',));
	$url_delete = $this->url(array('module'=>'product','controller'=>'plan','action'=>'delete',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->formFilter;
	$formFilter = $this->formFilter;
	$rs = $this->product;
?>
<title><?php echo $tr->translate("PRODUCT_LIST");?></title>

	<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("PRODUCT_LIST");?>
			</div>
			
			<div class="caption pull-right">
				<a href="<?php echo $url_new;?>"><button id="sample_editable_1_new" class="btn green">Add New <i class="fa fa-plus"></i></button></a>
			</div>
			<div class="caption" style="float:right">
					<?php $formList = new Application_Form_Frmlist(); //echo $formList->showAddBuntton($url_new);?>
			</div>
		</div>
		<div class="portlet-body form">
			<form class="form-horizontal" method="post" action="" >
				<div class="form-body">
					<div class="form-group">
						<div class="col-md-3">
							<input  class="form-control" id="adv_search" name="adv_search" value="<?php echo $this->row['adv_search']?>" placeholder="<?php echo $this->translate("Search");?>" type="text" >
						</div>
						
						<div class="col-md-3">
							<?php echo $form->getElement('typecate');?>
						</div>
						
						<div class="col-md-3">
							<?php echo $form->getElement("status");?>
						</div>
						<div class="col-md-3">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("Search");?></button>
						</div>						
					</div>
				</div>
				
			</form>
			
		</div>
		
		<!-- Result List -->
					<!-- BEGIN EXAMPLE TABLE PORTLET-->
						<div class="portlet-body">
							<table class="table table-striped table-bordered table-hover" id="sample_2" style="font-size:11px">
							<thead style="font-size:11px">
								<tr>
									<th><?php echo $tr->translate("NO");?></th>
									 <th><?php echo $tr->translate("TYPE");?></th>
									<th><?php echo $tr->translate("NAME");?></th>
									<th><?php echo $tr->translate("ADDRESS");?></th>
									<th><?php echo $tr->translate("STATUS");?></th>
								</tr>
							</thead>
							<tbody>
								<?php if(!empty($rs)){ foreach ($rs as $key => $row){?>
								<tr class="odd gradeX">
									<td><?php echo $key+1;?></td>
									<!-- <td class="center"><?php echo $row["branch"]?></td> -->
									<td><?php echo $row["type"]?></td>
									<td><?php echo $row["name"]?></td>
									<td><?php echo $row["address"]?></td>
									<td><?php echo $row["status"]?></td>
									
									<td>
										<a href="<?php echo $url_edit;?>/id/<?php echo $row["id"]?>"><?php echo $tr->translate("EDIT");?></a>
									</td>
								</tr>
								<?php }}?>
							</tbody>
							</table>
						</div>
					<!-- END EXAMPLE TABLE PORTLET-->
			<!-- End Result list -->

</div>