<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
//print_r($this->title_reprot);
?>
<title><?php echo $tr->translate("MENU_PRINT_PURCHASE_REQUEST");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("MENU_PRINT_PURCHASE_REQUEST");?>
				</div>
						<div class="btn-group pull-right">
							 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
							   Actions <i class="fa fa-angle-down"></i>
							 </button>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a href="#" onclick="doPrint();">
											<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
										</a>
									</li>
									<!--<li>
										<a href="javascript:;"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
									</li>-->
									
								</ul>
					</div>
			</div>
            <div class="portlet-body form frmfilter">
					<div style="clear:both;"></div>	
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%; margin-top:10px;" >
	<style>
		.style{
			line-height: 20px;font-size: 9px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
		th{padding: 0px;}
		ul.pur_info li{line-height:18px; 
				font-weight: normal !important;}
		ul.pur_info li strong{font-weight: bold;}
       .hover:hover{background: #ccc;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody>
							<tr>
								<td width="20%" valign="middle"><img src="<?php echo $this->baseUrl();?>/images/logo/<?php echo $this->title_reprot["logo"]?>"></td>
								<td width="60%" valign="top" style="line-height:30px">
									<ul>
										<li style="text-align:center; font-size:20px; font-family:'Khmer OS Muol Light'"><?php echo $this->title_reprot["title_report_kh"]?></li>
										<li style="text-align:center; font-size:18px; font-family:serif,header-font; font-weight:600;"><?php echo $this->title_reprot["title_report_en"]?></li>
										<li style="text-align:center; font-size:18px; margin-top:25px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate('PURCHASE_REQUEST'); ?></li>
									</ul>
								</td>
								<td width="20%"></td>
							</tr> 
							
							<tr>
								<td width="20%" valign="top">
									<table width="100%" style="font-size: 12px; !important">
										<tr>
											<td style="text-align: left; white-space:nowrap;"><?php echo $tr->translate("PLAN");?> </td>
											<td style="text-align: right; white-space:nowrap;">:</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo $this->product[0]['plan'];?></td>
										</tr>
										<tr>
											<td style="text-align: left; white-space:nowrap;"><?php echo $tr->translate("NUMBER_REQUEST");?> </td>
											<td style="text-align: right; white-space:nowrap;">:</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo $this->product[0]['number_request'];?></td>
										</tr>
										<tr>
											<td style="text-align: left;white-space:nowrap;"><?php echo $tr->translate("DATE_REQUEST_WORK_SPACE");?> </td>
											<td style="text-align: right; white-space:nowrap;">:</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo date("d/m/Y",strtotime($this->product[0]['date_from_work_space']));?></td>
										</tr>
									</table>
								</td>
								<td width="60%" valign="top">
									
								</td>
								<td width="20%" style="text-align: right;font-size: 12px;">
									<table width="100%" style="font-size: 12px; !important">
										<tr>
											<td style="text-align: right; white-space:nowrap;"><?php echo $tr->translate("BRANCH_NAME");?> :</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo $this->product[0]['branch'];?></td>
										</tr>
										<tr>
											<td style="text-align: right; white-space:nowrap;"><?php echo $tr->translate("REQUEST_NO");?> :</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo $this->product[0]['re_code'];?></td>
										</tr>
										<tr>
											<td style="text-align: right;white-space:nowrap;"><?php echo $tr->translate("REQUEST_DATE");?> :</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo date("d/m/Y",strtotime($this->product[0]['date_request']));?></td>
										</tr>
									</table>
									<!--<ul class='pur_info'>
			                					<li style="text-align: left;"><strong><?php echo $tr->translate("BRANCH_NAME");?> : </strong><?php echo $this->product[0]['branch'];?></li>
			                					<li style="text-align: right;"><strong><?php echo $tr->translate("REQUEST_NO");?> : </strong><?php echo $this->product[0]['re_code'];?></li>
			                					<li style="text-align: right;"><strong><?php echo $tr->translate("REQUEST_DATE");?> : </strong><?php echo date("d/m/Y",strtotime($this->product[0]['date_request']));?></li>
												<li style="text-align: left;"><strong><?php echo $tr->translate("PEDDING");?> : </strong><?php echo $this->product[0]['pedding'];?></li>
		                						<li style="text-align: left;"><strong><?php echo $tr->translate("PURCHASE_STATUS");?> : </strong><?php echo $this->product[0]['status'];?></li>
		                			</ul>-->
								</td>
							</tr> 							
		                 
		            </tbody></table>
		        </td>
		    </tr>
		    <tr>
		    	<td id="exportExcel">
		            <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
		                 <tbody>
						 <tr bgcolor="#ccc" class="style" align="center" style="font-weight:800 !important; line-height: 40px; font-size:14px !important; padding:1px 0px; white-space: nowrap; ">
		                    <th width="5%"><?php echo $tr->translate("NUM");?></th>
							<th width="15%"><?php echo $tr->translate("ITEM_CODE");?></th>
							<th width="15%"><?php echo $tr->translate("ITEM_NAME");?></th>
							<th width="10%"><?php echo $tr->translate("TYPE");?></th>
							<!--<th width="5%"><?php //echo $tr->translate("SIZE");?></th>
							<th width="5%"><?php //echo $tr->translate("LENGHT");?></th>-->
							<th width="10%"><?php echo $tr->translate("TOTAL_QTY");?></th>
							<th width="5%"><?php echo $tr->translate("MEASURE");?></th>
							<!--<th width="10%"><?php //echo $tr->translate("SUPPLIER");?></th>-->
							<th width="10%"><?php echo $tr->translate("REQ_DATE_IN");?></th>
							<th width="25%"><?php echo $tr->translate("REMARK");?></th>
		                </tr>
		                <?php $num=1; 
		                $r_netotal = 0;$r_paid = 0; $r_balance = 0;
		                $d_netotal = 0;$d_paid = 0; $d_balance = 0;
		                $b_netotal = 0;$b_paid = 0; $b_balance = 0;
						$count = count($this->product);
		                if(!empty($this->product))foreach ($this->product AS $index => $rs){?>
						<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
						   <td align="center">&nbsp;<?php echo $index+1?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_code"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_name"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["type"];?></td>
						   <!--<td style="white-space: nowrap;">&nbsp;<?php //echo $rs["size"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php​ //echo $rs["size"];?></td>-->
						   <td style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["qty"],2);?></td>
						   <td style="white-space: nowrap;" align="center">&nbsp;<?php echo $rs["measure"];?></td>
						   <td style="white-space: nowrap;" align="center">&nbsp;<?php echo date("d-M-Y",strtotime($rs["date_in"]));?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["remark"];?></td>
						</tr>
						   <?php 
                    }?>
					<?php 
						$length = 8 - $count;
						if($length>0){
							for($i=1;$i<=$length;$i++){ $no = $count+$i;
					?>
							<tr class='row-format<?php //echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
						   <td align="center">&nbsp;<?php echo $no?></td>
						   <td style="white-space: nowrap;">&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;</td>
						</tr>
					<?php 
							}
						}
					?>
                    
		                </tbody>
		           </table>
		              <table align="center" width="100%" >
						   <tbody>
						   <tr>
							<td colspan="7">
								<table style="font-size:12px; width:100%">
									<tr>
										<td style="width:2%">បញ្ជាក់ៈ </td>
										<td style="border-bottom:1px dotted #000;"><?php echo $this->product[0]["p_remark"]?></td>
									</tr>
									<tr>
										<td colspan="2"> សូមលោកប្រធានផ្នែកផ្គត់ផ្គង់ផ្តល់ពត៌មាន  នូវរយៈពេលដែលសម្ភារៈមកដល់ក្រុមហ៊ុន ឬ អ្នកស្នើសម្ភារៈ។</td>
									</tr>
								</table>
							</td>
						   </tr>
						   <tr style="font-size: 12px;">
						        <td style="width:20%;text-align:center; font-family:'Khmer OS Muol Light'">អនុម័ត<br /> អគ្គនាយក</td>
						        <td></td>
								 <td style="width:20%;text-align:center; font-family:'Khmer OS Muol Light'">ឯកភាព</td>
						        <td></td>
						        <td style="width:20%;text-align:center; font-family:'Khmer OS Muol Light'">ត្រួតពិនិត្យដោយ</td>
						        <td></td>
						        <td style="width:20%;text-align:center; font-family:'Khmer OS Muol Light'">អ្នកស្នើ</td>
						   </tr>
						    <tr style="font-size: 12px; height: 75px;">
						        <td valign="bottom" style="width:20%;text-align:center;  font-family:'Khmer OS Muol Light'; white-space: nowrap; border-bottom:1px solid #000;"></td>
						        <td></td>
								<td valign="bottom" style="width:20%;text-align:center;  font-family:'Khmer OS Muol Light'; white-space: nowrap;border-bottom:1px solid #000;"></td>
						        <td></td>
						        <td valign="bottom" style="width:20%;text-align:center; font-family:'Khmer OS Muol Light';white-space: nowrap;border-bottom:1px solid #000;"></td>
						        <td></td>
						        <td valign="bottom" style="width:20%;text-align:center;font-family:'Khmer OS Muol Light';white-space: nowrap;border-bottom:1px solid #000;"></td>
						   </tr>
						   <tr>
								<td style="text-align:center;font-family:'Khmer OS Muol Light';">ឃុត  មករា</td>
						   </tr>
						</tbody>
					</table>	
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=document.getElementById('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    //hideDialog();
}

/*var currentTime = new Date();
var month = currentTime.getMonth() + 1;
var day = currentTime.getDate();
var year = currentTime.getFullYear();
	var date =(year + "-" + month + "-" + day );

var start_date = $('#start_date').val();
var end_date =$('#end_date').val();

if(end_date!="" | start_date!=""){
    start_date = $('#start_date').val();
	end_date =$('#end_date').val();
	
}else{
	start_date = $('#start_date').val(date);
	end_date = $('#end_date').val(date);
}*/

<?php //$url_item_filter =  $this->url(array('module'=>'report','controller'=>'index','action'=>'get-item-filter')); ?>
/*function getProductFilter(){
	var location_id=$("#LocationId").val();
	var branch_id = $('#branch_id').val();
	var category_id = $('#category_id').val();
		$.ajax({
			url:"<?php //echo $url_item_filter;?>",
			type:"post",
			data:{'category_id':category_id,'branch_id':branch_id,'location_id':location_id},
			success: function(data){
				items = $.parseJSON(data);
				if(items){
					 $('#item').empty();
					 $('#item').val('').trigger("liszt:updated");
					 $('#item').append($("<option></option>").attr("value","").text("Please Select Item"));
					 for (var index = 1 ; index <= items.length; index++) {
							$('#item').append($("<option></option>").attr("value",items[index-1]['pro_id']).text(items[index-1]['item_code'] + items[index-1]['item_name'])); 
							$("select#item").find("option#items[index-1]['pro_id']").attr("selected", true);
					 }           
					$('#item').val('').trigger("liszt:updated");
				}else{
					 $('#item').empty();
					 $('#item').val('').trigger("liszt:updated");
						 $('#item').append($("<option></option>").attr("value","").text("No Items Result!"));
						 $('#item').val('').trigger("liszt:updated");
				}
			},
			error:function(){
			}
		});
	}*/
</script>
