<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form_purchase;
	$url_submit = $this->url(array('module'=>'purchase','controller'=>'index','action'=>'add'));
	$url_cancel = $this->url(array('module'=>'purchase','controller'=>'index','action'=>'index'));
?>
<style>
      table.table-bordered tbody th, table.table-bordered tbody td{width:2px;}
</style>
<title><?php echo $tr->translate("ADD_PURCAHSE_ORDER");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("ADD_PURCAHSE_ORDER")?>
				</div>
				<div class="tools" >
					<a href="<?php echo $url_cancel;?>" class="btn btn-sm pull-right" style="color:white;">
					<i class="fa fa-undo"></i>	&nbsp;<?php echo $tr->translate("GO_BACK");?>
					</a>
				</div>
			</div>
			<div class="portlet-body">
				<!-- BEGIN FORM-->
				<form id="frm a" action="<?php //echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post">
					<table class="table table-striped table-bordered table-hover" id="table_order" style="font-size:12px;">
						<tr>
							<td rowspan="2" align="center" class="center">Item Desription</td>
							<td rowspan="2" class="center">Qty</td>
							<td class="center">Quaotation I</td>
							<td class="center">Quaotation II</td>
							<td class="center">Quaotation III</td>
							<td class="center">Quaotation IV</td>
						</tr>
						<tr>
							<?php for($i=1;$i<=4;$i++){ ?>
								<td style="white-space:nowrap;">
									<select name="su_id_<?php echo $i;?>" class="form-control select2me" >
										<?php foreach($this->vendor as $rs){?>
											<option value="<?php echo $rs["vendor_id"];?>"> <?php echo $rs["v_name"]?></option>
										<?php }?>
									</select>
								</td>
							<?php }?>
						</tr>
						<?php foreach($this->product as $key => $rs){ $i= $key+1;?>
						<tr>
							<td style="white-space:nowrap;"><?php echo $rs["item_name"];?><input type="hidden" name="pro_id_<?php echo $i;?>" value="<?php echo $rs["pro_id"];?>" /></td>
							<td style="white-space:nowrap;"><?php echo $rs["qty"]."&nbsp;&nbsp;". $rs["measure"];?><input type="hidden" name="pro_qty_<?php echo $i;?>" value="<?php echo $rs["qty"];?>" /></td>
							<?php for($j=1;$j<=4;$j++){ ?>
								<td style="white-space:nowrap;"><input type="text" style="width: 80%;" name="su_price_<?php echo $i?>_<?php echo $j;?>" value="0" /><input type="checkbox" value="1" name="checkbox_<?php echo $i?>_<?php echo $j;?>"/></td>
							<?php 
								
							} ?>
							
						</tr>
						<?php 
							if($i>1){
								$index = $index.",".$i;
							}else{
								$index = 1;
							} 
						} ?>
					</table>
					<input type="hidden" name="identity" value="<?php echo $index;?>" />
					<div class="form-group">
							<label  class="col-md-12 col-md-offset-4 col-md-8">
								<a href="<?php echo $this->baseUrl();?>/purchase/compareprice/"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
								<button type="submit" name="save_close" id="save_close" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<button type="submit" name="save_print" class="btn btn-primary"><i class="fa fa-print"></i> <?php echo $tr->translate("SAVE_PRINT")?></button>
							</label>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<script>
$(document).ready(function () {
    
});
</script>
	