<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form_sale;
	$url_submit = $this->url(array('module'=>'purchase','controller'=>'payment','action'=>'add'));
	$url_cancel = $this->url(array('module'=>'purchase','controller'=>'payment','action'=>'index'));
	$url_new = $this->url(array('module'=>'purchase','controller'=>'payment','action'=>'add'));
?>
<title><?php echo $tr->translate("MENU_MAKE_PURCHASE_INVOICE");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("MENU_MAKE_PURCHASE_INVOICE")?>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="frm" action="<?php //echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post">
					<div class="form-body" style="background:#fbf9f9;">
						<div class="form-group">
							
							<label class="control-label col-md-2"> <?php echo $tr->translate("INVOICE_NO");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("payment_number");?>
								</div>
							</div>
							
							<label class="control-label col-md-2"><?php echo $tr->translate("INVOICE_DATE");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("invoice_date");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("INVOICE_METHOD");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<select name="payment_method" id="payment_method" onchange="checkControll();" class="form-control select2me">
										<option value="1">	<?php echo $tr->translate("PAYMENT_BY_SUPPLIER")?></option>
										<option value="2"><?php echo $tr->translate("PAYMENT_BY_DN")?></option>
									</select>
								</div>
							</div>
							
							<label class="control-label col-md-2"><?php echo $tr->translate("RECEIVE_INVOICE_DATE");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("invoice_date_from_stock");?>
								</div>
							</div>
							
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("DN_NO");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('invoice_id');?>
								</div>
							</div>
							<label class="control-label col-md-2"> <?php echo $tr->translate("VENDOR_NAME");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("customer_id");?>
								</div>
							</div>
							
						
							
					    </div>
						
						<div class="form-group">
							
							<label class="control-label col-md-2"><?php echo $tr->translate("BRANCH");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right" style="pointer-events: none;cursor: default;">
									<?php echo $form->getElement("branch");?>
								</div>
							</div>
						
							<label class="control-label col-md-2"><?php echo $tr->translate("REMARK");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("remark");?>
								</div>
							</div>
					    </div>
						
						<div class="portlet-body">
							<table class="table table-striped table-bordered table-hover" id="table_order" style="font-size:12px;">
								<tr height="33px">
									<th><?php echo $tr->translate("DEL");?></th>
									<th><?php echo $tr->translate("NUM");?></th>
									<th style="white-space:nowrap;"><?php echo $tr->translate("ថ្ងៃ/ខែ/ឆ្នាំ");?></th>
									<th><?php echo $tr->translate("វិក័យបត្រ");?></th>
									<th><?php echo $tr->translate("ចំនួនទឹកប្រាក់");?></th>
									<th><?php echo $tr->translate("បញ្ចុះតម្លៃ");?></th>
									<th><?php echo $tr->translate("ទឹកប្រាក់បានបង់");?></th>
									<th><?php echo $tr->translate("ទឹកប្រាក់នៅខ្វះ");?></th>
							</tr>
						 </table>
						 <input type="hidden" id="identity" name="identity" />
					</div>
					<?php //echo $form->getElement("all_total");?>
					<?php echo $form->getElement("paid");?>
					<?php echo $form->getElement("balance");?>
					<input type="hidden" name="vat" id="vat" />
						<div class="form-group">
							<label class="control-label col-md-2"><?php //echo $tr->translate("SUB_TOTAL");?><span class="required">
								 </span>
							</label>
							<label class="control-label col-md-2">
							</label>
							<div class="col-md-2">
								<div class="input-icon right">
								</div>
							</div>
								<label class="control-label col-md-2"><?php echo $tr->translate("TOTAL");?>:<span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon left"><i class="fa">$</i>
								<input type="text" style="text-align:right;" class="form-control" readOnly="readOnly" name="total" id="total" />
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right"></div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("TAX");?>:<span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon left"><i class="fa">$</i>
									<input type="text" style="text-align:right;" readOnly="readOnly" class="form-control" name="total_vat" id="total_vat" />
								</div>
							</div>	
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php //echo $tr->translate("ពន្ធ");?><span class="required">
							</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<?php //echo $form->getElement("total_tax");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("GRAND_TOTAL");?>:<span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon left"><i class="fa">$</i>
								<?php echo $form->getElement("all_total");?>
								</div>
							</div>
						</div>
						
						<div class="form-group">
							<div  class="col-md-12 col-md-offset-4 col-md-8">
								<a href="<?php echo $this->baseUrl();?>/purchase/receive/"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
								<button type="submit" name="save_close" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<!--<button type="submit" name="save_print" class="btn btn-primary"><i class="fa fa-print"></i> <?php echo $tr->translate("SAVE_PRINT")?></button>-->
							</div>
							
						</div>
						
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<!-- end new product -->
<script>
function paidtotal(type){//1=dollar,2=riel
	doRemain();
}
function checkpayment(){
	payment_id = $("#payment_name").val();
	//alert(payment_id);
	if(payment_id==2){
		$( "#bank_name" ).attr( "readOnly", false );
		$( "#cheque" ).attr( "readOnly", false );
	}else{
		$( "#bank_name" ).attr( "readOnly", true );
		$( "#cheque" ).attr( "readOnly", true );
	}
}
function checkControll(){
	$("#table_order").html("");
	$('#balance').val(0);$('#all_total').val(0);//$('#paid').val(0);
	payment_method = $("#payment_method").val();
	if(payment_method==1){
		$( "#invoice_id" ).attr( "readOnly", true );
		
		$( "#customer_id" ).attr( "readOnly", false );
	}else{
		$( "#customer_id" ).attr( "readOnly", true );
		$( "#invoice_id" ).attr( "readOnly", false );
    }
}
<?php $urlgetinvoice =  $this->url(array('module'=>'','controller'=>'ajax','action'=>'getreceive')); ?>
function getInvoice(type){
	if(type==1){
		id=$("#customer_id").val();
		$( "#invoice_id" ).attr( "readonly", true );
		$( "#customer_id" ).attr( "readOnly", false );
	}else{
		id=$("#invoice_id").val();
		$( "#customer_id" ).attr( "readonly", true );
		$( "#invoice_id" ).attr( "readOnly", false );
	}
	$.ajax({
			url:"<?php echo $urlgetinvoice;?>",
			type:"post",
			data:{'id':id,'type':type},
			success: function(data){
				//alert(data);
				$("#table_order").html("");
				template='<tr height="33px">';
					template+='<th><?php echo $tr->translate("DEL");?></th>';
					template+='<th><?php echo $tr->translate("NUM");?></th>';
					template+='<th><?php echo $tr->translate("DN_NO");?></th>';
					template+='<th style="white-space:nowrap;"><?php echo $tr->translate("DN_DATE");?></th>';
					template+='<th><?php echo $tr->translate("RECEIVE_NO");?></th>';
					template+='<th><?php echo $tr->translate("TOTAL");?></th>';
					//template+='<th><?php echo $tr->translate("បញ្ចុះតម្លៃ");?></th>';
					template+='<th><?php echo $tr->translate("TAX");?></th>';
					template+='<th><?php echo $tr->translate("GRAND_TOTAL");?></th>';
				template+='</tr>';
				
				$('#identity').val("");
				//salert(data);
				data = $.parseJSON(data);
				
				
				for(i=0;i<data.length;i++){
					if(i==0){
						$("#customer_id").val(data[i].vendor_id);
						$("#customer_id").select2();
						$("#vat").val(data[i].tax);
					}
					index=i+1;
					template+='<tr style="height:30px;">';
			           // template+='<td ><img onClick="deleteRecord('+index+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
					   template+='<td style="vertical-align: middle;text-align: center;"><input type="checkbox" onClick="checkedRow('+index+')" name="checkbox_'+index+'" id="checkbox_'+index+'" /></td>';
						template+='<td >'+index+'</td>';
						template+='<td >'+data[i].dn_number+'</td>';
						template+='<td >'+data[i].date_in+'<input type="hidden" value='+data[i].order_id+' id="dn_id'+index+'" name="dn_id'+index+'"/></td>';
						template+='<td >'+data[i].recieve_number+'</td>';
						
						template+='<td ><span style="margin-right:5px;" > $</span>'+data[i].net_total_after+'<input type="hidden" value='+data[i].net_total_after+' id="subtotal'+index+'" name="subtotal'+index+'"/><input type="hidden" value='+data[i].all_total+' id="grand_total'+index+'" name="grand_total'+index+'"/></td>';
						template+='<td >'+data[i].tax+'<span style="margin-right:5px;" >%</span><input type="hidden" value="0" id="paid_amount'+index+'" name="paid_amount'+index+'"/><input type="hidden" value='+data[i].discount_after+' id="discount'+index+'" name="discount'+index+'"/></td>';
						template+='<td ><span style="margin-right:5px;" >$</span>'+data[i].all_total+'<input type="hidden" value='+data[i].balance_after+' id="balance_after'+index+'" name="balance_after'+index+'"/></td>';
				    template+="</tr>";
					
					/*if($('#identity').val()!="") {
						var identity = $('#identity').val();
						$('#identity').val(identity+','+index);
					} else {$('#identity').val(index);}*/
				}
				$('#table_order').append(template);
				if(data.length>0){netTotal();}else{$('#balance').val(0);$('#all_total').val(0);$('#paid').val(0); alert("No invoice to make payment");}
				
			},
			error:function(e){
				alert("error"+e);
			}
		});	
}
function checkedRow(index){
	var ids =$('#identity').val();
		var arrays = ids.split(',');
		for(var i=0;i<arrays.length;i++) {//calculate record row
			if(arrays[i] == index) arrays.splice(i,1);
			if($('#checkbox_'+index).attr('checked')){
				if($("#identity").val()!="") {
					$("#identity").val(ids+','+index);
				}else { 
					$("#identity").val(index);
				}
				
			 }else{
				var strings = arrays.join(',');
				$('#identity').val(strings);
			}
		}
		
		netTotal();
}
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	$("#row_order_"+index).remove();
	netTotal();
}
function netTotal() {//use
	var subtotal=0;
	total=0;
	total_vat =0;
	var paid = 0;
	discount=0;
	vat = parseFloat($("#vat").val());
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	for(var n = 0; n < rowIDArray.length; n++) {
		//subtotal += Number($('#subtotal'+rowIDArray[n]).val());
		//paid +=Number($('#paid_amount'+rowIDArray[n]).val());
		//discount +=Number($('#discount'+rowIDArray[n]).val());
		subtotal += Number($('#balance_after'+rowIDArray[n]).val());
		total += Number($('#subtotal'+rowIDArray[n]).val());
		total_vat += Number((parseFloat($('#subtotal'+rowIDArray[n]).val())*vat)/100);
		
		
	}
	//var alltotal = Number(subtotal - discount).toFixed(2);
	$('#all_total').val(subtotal.toFixed(2));
	$('#total').val(total.toFixed(2));
	$('#total_vat').val(total_vat.toFixed(2));
	//$('#paid').val(0);
	doRemain();
}
function doRemain() {
	var all_total = Number($('#all_total').val());
	var paid = Number($('#paid').val());
	if(paid > all_total){
		var paid = $('#paid').val(all_total);
		 $('#remain').val(0);
   }else{
	   remain = all_total-paid;
	   $('#balance').val(remain.toFixed(2));
	}	
}
function getCustomerInfo(){
	v_id = $("#v_name").val();
	if(v_id==-1){
		$('#dialogvendor').modal('show');
	}
}

</script>	