<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form_sale;
	$url_submit = $this->url(array('module'=>'purchase','controller'=>'index','action'=>'add'));
	$url_cancel = $this->url(array('module'=>'purchase','controller'=>'index','action'=>'index'));
	$url_new = $this->url(array('module'=>'purchase','controller'=>'index','action'=>'add'));
	//print_r($this->product);
?>
<title><?php echo $tr->translate("ADD_SALESORDER");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("ADD_REQUEST")?>
				</div>
				<div class="col-md-2 pull-right">
								<a href="<?php echo $this->baseUrl();?>/sales/index/requestlist"><button type="button" class="btn red btn-block btn-lg"><i class="fa fa-times"></i> <?php echo $tr->translate("GO_BACK")?></button></a>
							</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="a" action="<?php //echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post">
					<div class="form-body">
						<div class="form-group">
							<label class="control-label col-md-2"><?php //echo $tr->translate("BRANCH_NAME");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php //echo $form->getElement('branch_id');?>
								</div>
							</div>
							
							<label class="control-label col-md-2"><?php echo $tr->translate("BRANCH_NAME");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('branch_id');?>
								</div>
							</div>
							
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("REQUEST_NO");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("apno");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("DATE_REQUEST");?><span class="required">
							*</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<?php echo $form->getElement("order_date");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("NUMBER_WORK_SPACE");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("request_no");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("DATE_REQUEST_WORK_SPACE");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('request_date');?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("REQUEST_NAME");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("request_by");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("POSITION");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('requstman_pos');?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php  echo $tr->translate("PLAN");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("plan");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("DEPARTMENT");?><span class="required">
							*</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<?php echo $form->getElement("work_plan");?>
								</div>
							</div>
						</div>
						
						<div class="form-group">
							
							<label class="control-label col-md-2"><?php echo $tr->translate("REQUEST_TYPE");?><span class="required">
							</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<?php echo $form->getElement("request_type");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php  echo $tr->translate("REMARK");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("remark");?>
								</div>
							</div>
						</div>
						
						<!--<div class="form-group">
							<label class="control-label col-md-2"><?php  //echo $tr->translate("REMARK");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php //echo $form->getElement("remark");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php  echo $tr->translate("REMARK");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("remark");?>
								</div>
							</div>
						</div>-->
						<div class="form-group">
							<div class="col-md-2">
								<button type="button" class="btn red delete" style="width:100%;">
								<i class="fa fa-barcode"></i>
								<span><?php echo $tr->translate("SCAN");?></span>
								</button>
							</div>
							<div class="col-md-8">
								<!--<select data-placeholder="Select..." class="form-control select2me" id="add_item" name="add_item" Onchange="getItemOrder();"  style="width:100% ;margin:0 auto;">
											<?php //echo $this->items; ?>
								</select>-->
								
								<input type="hidden" class="form-control" id="add_item" name="add_item" Onchange="getItemOrder();" style="width:100%;" placeholder="<?php echo $tr->translate("SELECT_PRODUCT");?>"/>
							</div>
							<div class="col-md-2">
								<button type="button" class="btn red delete" style="width:100%;">
								<i class="fa fa-barcode"></i>
								<span><?php echo $tr->translate("SCAN");?></span>
								</button>
							</div>
						</div>
						<div class="portlet-body">
							<table class="table table-striped table-bordered table-hover" id="table_order" style="font-size:12px;">
								<tr height="33px">
									<th><?php echo $tr->translate("DEL");?></th>
									<th><?php echo $tr->translate("NUM");?></th>
									<th style="white-space:nowrap;"><?php echo $tr->translate("ITEM_NAME");?></th>
									<th style="white-space:nowrap;"><?php echo $tr->translate("CURRENT_QTY");?></th>
									<th style="white-space:nowrap;"><?php echo $tr->translate("QTY_REQUEST");?></th>
									<th style="white-space:nowrap;"><?php echo $tr->translate("MEASURE");?></th>
									<th style="white-space:nowrap;"><?php echo $tr->translate("UNIT_PRICE_CAP");?></th>
									<th style="white-space:nowrap;"><?php echo $tr->translate("SUB_TOTAL_CAP");?></th>
									<th style="white-space:nowrap;"><?php echo $tr->translate("WORK_TYPE");?></th>
									<th style="white-space:nowrap;"><?php echo $tr->translate("WORK_REMARK");?></th>
									<th style="white-space:nowrap;"><?php echo $tr->translate("NUM_REMARK");?></th>
									<th style="white-space:nowrap;"><?php echo $tr->translate("QTY_ORDER");?></th>
									<th style="white-space:nowrap;"><?php echo $tr->translate("REQ_DATE_IN");?></th>
									<th style="white-space:nowrap;"><?php echo $tr->translate("NOTE");?></th>
							</tr>
						 </table>
						 <input type="text" id="identity" name="identity" />
						 <input type="hidden" id="identity_term" name="identity_term" />
								
					</div>
						<!-- blog bottom -->
						<div class="form-group">
							<label class="control-label col-md-2"><?php //echo $tr->translate("PAYMENT_METHOD");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php //echo $form->getElement("payment_name");?>
								</div>
							</div>
								<label class="control-label col-md-2"><?php echo $tr->translate("តម្លៃសរុប​ :");?><span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon left">
									<i>$</i>
								<?php echo $form->getElement("totalAmoun");?>
								<?php echo $form->getElement("dis_value");?>
								<?php echo $form->getElement("all_total");?>
								<input type="hidden" name="global_disc" id="global_disc"/>
								</div>
							</div>
						</div>
						<!--<div class="form-group">
							<label class="control-label col-md-2"><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right"></div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("DISCOUNT");?>
							</label>
							<div class="col-md-4">
								<div class="input-icon left">
									<i>$</i>
									<?php //echo $form->getElement("dis_value");?>
								       <input type="hidden" name="global_disc" id="global_disc"/>
								</div>
							</div>	
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php //echo $tr->translate("ពន្ធ");?><span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<?php //echo $form->getElement("total_tax");?>
								</div>
							</div>
							<label class="control-label col-md-2">សាច់ប្រាក់សរុប​ :<span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon left">
									<i>$</i>
								<?php //echo $form->getElement("all_total");?>
								</div>
							</div>
						</div>-->
						
						
						<div class="form-group">
							
							<div  class="col-md-12 col-md-offset-4 col-md-8">
								<a href="<?php echo $this->baseUrl();?>/sales/index/requestlist"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
								<button type="submit" id="save_close" name="save_close" value="save_close" class=" submit btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<button type="submit" id="save_new" name="btnsavenew" class="btn btn-primary"><i class="submit1 fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
								<!--<button type="submit" name="save_print" class="btn btn-primary"><i class="fa fa-print"></i> <?php echo $tr->translate("SAVE_PRINT")?></button>-->
												
							</div>
						</div>
						
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<?php $form = $this->form_customer; ?>
<div id="customerpopup" class="modal fade" tabindex="-1" data-width="1200">
       <div class="modal-dialog">
      <div class="modal-content">
      <div class="modal-header">   
		<div class="row">
		<div class="col-md-12">
			<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("ADD_NEW_CUSTOMER");?>
				</div>
				<div class="caption pull-right">
					<a href="<?php echo $url_new;?>" >
						 <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
					</a>
				</div>
			</div>
			<div class="portlet-body form">
				<form id="frmcustomer" name="frmcustomer" class="form-horizontal" enctype="multipart/form-data" method="post">
				<div class="form-body">
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("Branch Name");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("branch_id");?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("COMPANY_NUMBER");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('cu_code'); ?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("COMPANY_NAME");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('txt_name'); ?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("COMPANY_NUMBER");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('txt_phone'); ?>
								</div>
							</div>
						</div>
					<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("CON_NAME");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('txt_contact_name'); ?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("CON_NUMBER");?><span class="required"></span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i><?php echo $form->getElement('contact_phone'); ?>
								</div>
							</div>
					</div>
					<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("CUSTOMER_TYPE");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
									<div class="input-icon right">
										<i class="fa"></i>
										<?php echo $form->getElement('customer_type'); ?>
									</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("Customer Level");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('customer_level'); ?>
								</div>
							</div>
					</div>
					<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("VENDOR_ADD");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("txt_address");?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("EMAIL");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('txt_mail'); ?>
								</div>
							</div>
					</div>
					
					<div class="form-group">
						<label class="control-label col-md-2"><?php echo $tr->translate("CREDIT_LIMIT");?> <span class="required">
								</span>
						</label>
						<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('credit_limit'); ?>
								</div>
						</div>
						<label class="control-label col-md-2">
							<?php echo $tr->translate("CREDIT_TEARM");?><span class="required">
								</span>
						</label>
						<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("credit_tearm");?>
								</div>
						</div>
						
					</div>
					
					<div class="form-group">
						<label  class="col-md-12 col-md-offset-4 col-md-8">
							<button type="button" name="btnsavenew" onclick="addNewCustomer();" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_CUSTOMER")?> </button>
						</label>
					</div>
				</div>
				</form>
			</div>
		</div>
	</div>
</div>
          </div>
        </div>
    </div>
 </div>
<!-- end new product -->

<script>
<?php $url_item_plan =  $this->url(array('module'=>'','controller'=>'ajax','action'=>'getplanitem')); ?>
function getItem(){
	//$('#table_order').append('');
	document.getElementById('table_order').innerHTML = "";
	$('#identity').val('');
	tbheader()
	var request_type = $("#request_type").val();
	if(request_type==1){
		
		itemss = <?php echo Zend_Json::encode($this->product)?>;
		select2Speed('add_item');
	}else{
		var id = $('#plan').val();
		if(id==""){
			itemss='';
			alert('Please Select Plan');
		}else{
			$.ajax({
				url:"<?php echo $url_item_plan;?>",
				type:"post",
				data:{'id':id},
				success: function(data){
					//alert(data);
					//$('#table_order').append('');
					itemss = $.parseJSON(data);
					select2Speed('add_item');
					
				}
			});
		}
	}
	
	
}

function tbheader(){
	template='<tr id="row_order_'+index5+'" style="height:33px;">';
	template+='<th><?php echo $tr->translate("DEL");?></th>';
	template+='<th><?php echo $tr->translate("NUM");?></th>';
	template+='<th style="white-space:nowrap;"><?php echo $tr->translate("ITEM_NAME");?></th>';
	template+='<th style="white-space:nowrap;"><?php echo $tr->translate("CURRENT_QTY");?></th>';
	template+='<th style="white-space:nowrap;"><?php echo $tr->translate("MEASURE");?></th>';
	template+='<th style="white-space:nowrap;"><?php echo $tr->translate("QTY_REQUEST");?></th>';
	template+='<th style="white-space:nowrap;"><?php echo $tr->translate("UNIT_PRICE_CAP");?></th>';
	template+='<th style="white-space:nowrap;"><?php echo $tr->translate("SUB_TOTAL_CAP");?></th>';
	// template+='<td width="10%" style="vertical-align: middle;text-align:center;"><select class="form-control select2me" name="work_type_'+index5+'" id="work_type_'+index5+'">'+worktype+'<option></option></select></td>';
	// template+='<td width="4%" style="vertical-align: middle;text-align:center;"><input type="text" name="remark_'+index5+'" id="remark_'+index5+'" value=""/></td>';
	// template+='<td><input type="text" class="form-control" id="note_'+index5+'" name="note_'+index5+'" /></span></td>';
	// template+='<td><input type="text" onkeypress="return isNumberKey(event)" class="form-control" id="qty_order_'+index5+'" name="qty_order_'+index5+'" /></span></td>';
	// template+='<td><input type="text" class="form-control date-picker" id="re_date_in_'+index5+'" name="re_date_in_'+index5+'" /></span></td>';
	// template+='<td><input type="text"  class="form-control" id="re_note_'+index5+'" name="re_note_'+index5+'" /></span></td>';
	template+="</tr>";
	$('#table_order').append(template);
	
}
//itemss = <?php echo Zend_Json::encode($this->product)?>;
$( document ).ready(function() {
	getItem();
	//alert("ready loaded");
	/*$("#a").submit(function () {
		$('[name="save_close"]').val(1);
        $("#save_close").attr("disabled", true);
        return true;
    });*/
	
	/*$('#save_close').click(function(){
        $("#orderFrm").submit(function () {
			window.location ="<?php echo $this->baseUrl();?>/sales/index/requestlist";
		$(this).find(':input[type=submit]').prop('disabled', true);
		window.location.href ="<?php echo $this->baseUrl();?>/sales/index/requestlist";
		});
        
    });*/

});
function select2Speed(name){
	 $('#add_item').select2({
            data : _.map(_.range(0, itemss.length), function (i) {
				//alert(itemss);
                  return {
                      id  : itemss[i].id,
                      text: itemss[i].item_code+"-"+itemss[i].item_name
                  };
            }),
            dropdownCssClass : 'capitalize',
            containerCssClass: 'capitalize',
            // configure as multiple select
            //multiple         : true,
            // text for loading more results
            formatLoadMore   : 'Loading more...',
            query            : function (q) {
            // pageSize is number of results to show in dropdown
                var pageSize,
                    results;
                    pageSize = 20;
                    results  = _.filter(this.data, function (e) {
                        return (q.term === "" || e.text.toUpperCase().indexOf(q.term.toUpperCase()) >= 0);
                 });
                q.callback({
                    results: results.slice((q.page - 1) * pageSize, q.page * pageSize),
                    // retrieve more when user hits bottom
                    more   : results.length >= q.page * pageSize
                });
            }
        });
}

<?php $url_staff =  $this->url(array('module'=>'','controller'=>'ajax','action'=>'getstaff')); ?>
function getStaff(){
	id = $("#request_by").val();
	$.ajax({
		url:"<?php echo $url_staff;?>",
		type:"post",
		data:{'id':id},
		success: function(data){
			data = $.parseJSON(data);
			$("#requstman_pos").val(data);
		}
	});
}

<?php $url_work_plan =  $this->url(array('module'=>'','controller'=>'ajax','action'=>'getworkplan')); ?>
function getWork(){
	id = $("#plan").val();
	$.ajax({
		url:"<?php echo $url_work_plan;?>",
		type:"post",
		data:{'id':id},
		success: function(data){
			data = $.parseJSON(data);
			//alert(data);
			document.getElementById('work_plan').innerHTML=data;
			//$("#work_plan").append(data);
		}
	});
}

var index5 = 0;num=0;
var option5 = '<?php echo $this->items; ?>';
var worktype = '<?php echo $this->worktype; ?>';
var baseUrl = '<?php echo BASE_URL; ?>';
var template = '';
var value = '';
pqty = 1;
var index=1;
<?php $url_qty =  $this->url(array('module'=>'','controller'=>'ajax','action'=>'getqtybyid')); ?>
function addRow(item_id) {
	//item_id=$("#item_id_"+index).val();
				//qty_unit=$("#qty_unit_"+index).val();
				//qty_per_unit=$("#qty_per_unit_"+index).val();
				var identity = $('#identity').val();
	var arrays = identity.split(',');
	if(arrays!=""){
		a = arrays.length;
		//alert(a);
		index= parseInt(a)+1;
	}else{
		index=1;
	}
				branch_id = $("#branch_id").val();
				if(branch_id=='' || branch_id==-1){alert("Please Select Branch First ");}
				
					$.ajax({
						url:"<?php echo $url_qty;?>",
						type:"post",
						data:{'item_id':item_id,'branch_id':branch_id},
						success: function(data){
							//alert(data);
							item_qty = $.parseJSON(data);
							//if(item_qty.qty >0){
								
								index5++; //var first = index5;
								//index=index+1;
								for(i=1; i<index5; i++){
									new_item=parseInt(item_id);
									items = parseInt($("#item_id_"+i).val());
									if(new_item==items){
										//qty = $("#qty"+i).val();
										qty = ($("#qty"+i).val()=='')?0 : $("#qty"+i).val();
										new_qty = parseFloat(qty)+1;
										$("#qty"+i).val(new_qty);
										//alert(i);
										//calculatePrice(i);
										//calculatePrice(index)
										return false;
									}
								}
								template='<tr id="row_order_'+index5+'" style="height:33px;">';
								var inp = '';
								
								template+='<td ><img onClick="deleteRecord('+index5+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
								template+='<td  width="2%"><label id="lbno_'+index5+'">'+index+'<label></td>';
								template+='<td width="40%"><input type="hidden" class="form-control" id="item_id_'+index5+'" name="item_id_'+index5+'" value="'+item_qty.id+'" ><label id="item_name_'+index5+'">'+item_qty.item_code+"-"+item_qty.item_name+'</label></td>';
								template+='<td><input style="background:#f5e1e1;" readonly type="text" class="form-control" id="current_qty'+index5+'" name="current_qty'+index5+'" value="'+item_qty.qty+'"/></td>';
								template+='<td  width="2%"><label id="lb_measure_'+index5+'">'+item_qty.measure+'</label></td>';
								template+='<td ><input type="text" onkeypress="return isNumberKey(event)" required="required" onKeyup="calculatePrice('+index5+')" class="form-control" required="1" value="1" id="qty'+index5+'" name="qty'+index5+'"/></td>';
								
								template+='<td style="width: 10%;"><div class="input-icon left"><i class="fa">$</i><input style="text-align:right;" type="text" onkeypress="return isNumberKey(event)" required="required" onKeyup="calculatePrice('+index5+')" class="validate[required,custom[number]] input form-control" id="price'+index5+'" name="price'+index5+'" value="'+item_qty.price+'"/><input type="hidden" id="oldprice_'+index5+'" name="oldprice_'+index5+'"/></td>';
								template+='<td style="width: 12%;"><div class="input-icon left"><i class="fa">$</i><input style="text-align:right;" type="text" onkeypress="return isNumberKey(event)" required="required" class="form-control" readonly="readonly" id="total'+index5+'" name="total'+index5+'" /></span></td>';
								// template+='<td width="10%" style="vertical-align: middle;text-align:center;"><select class="form-control select2me" name="work_type_'+index5+'" id="work_type_'+index5+'">'+worktype+'<option></option></select></td>';
								// template+='<td width="4%" style="vertical-align: middle;text-align:center;"><input type="text" name="remark_'+index5+'" id="remark_'+index5+'" value=""/></td>';
								// template+='<td><input type="text" class="form-control" id="note_'+index5+'" name="note_'+index5+'" /></span></td>';
								// template+='<td><input type="text" onkeypress="return isNumberKey(event)" class="form-control" id="qty_order_'+index5+'" name="qty_order_'+index5+'" /></span></td>';
								// template+='<td><input type="text" class="form-control date-picker" id="re_date_in_'+index5+'" name="re_date_in_'+index5+'" /></span></td>';
								// template+='<td><input type="text"  class="form-control" id="re_note_'+index5+'" name="re_note_'+index5+'" /></span></td>';
								template+="</tr>";
								$('#table_order').append(template);
								if($('#identity').val()!="") {
									var identity = $('#identity').val();
									$('#identity').val(identity+','+index5);
								} else {$('#identity').val(index5);}
								$("#item_id_"+index5).val(item_id);
								$("#item_id_"+index5).select2();
								$("#current_qty"+index).val(item_qty.qty);
								$("#price"+index).val(item_qty.price);
								$("#re_date_in_"+index5).datepicker();
								document.getElementById('lb_measure_'+index5).innerHTML=item_qty.measure;
								calculatePrice(index5);
								//getQtyById(index5);
								
								$("#row_order_0").remove();
								$("#orderFrm").validationEngine();
							//}else{
							//	alert("Product is not available in Stock now!");
							//}
						},
						error:function(e){
							//alert(e);
						}
				});
								calculatePrice(index5);

}
term_option = '<?php echo $this->term_opt; ?>';
index1 = 0;
function addtermcondition(t_id){
	index1++; 
	template='<tr id="row_term_'+index1+'" style="height:33px;">';
    template+='<td width="20px" ><img onClick="deleteTermRecord('+index1+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
	template+='<td  width="2%">'+index1+'</td>';
	template+='<td><select class="form-control select2me" id="termid_'+index1+'" name="termid_'+index1+'" >'+term_option+'<option></option></select></td>';
	template+="</tr>";
	$('#table_termcondition').append(template);
	if($('#identity_term').val()!="") {
		var identity = $('#identity_term').val();
		$('#identity_term').val(identity+','+index1);
	} else {$('#identity_term').val(index1);}
	$("#termid"+index1).val(item_id);
	$("#row_term_0").remove();	
}
<?php $url_qty =  $this->url(array('module'=>'','controller'=>'ajax','action'=>'getqtybyid')); ?>
function getQtyById(index){//use
	
				item_id=$("#item_id_"+index).val();
				//qty_unit=$("#qty_unit_"+index).val();
				//qty_per_unit=$("#qty_per_unit_"+index).val();
				branch_id = $("#branch_id").val();
				if(branch_id=='' || branch_id==-1){alert("Please Select Branch First ");}
				
					$.ajax({
						url:"<?php echo $url_qty;?>",
						type:"post",
						data:{'item_id':item_id,'branch_id':branch_id},
						success: function(data){
							item_qty = $.parseJSON(data);			
							//main_qty =$("#qty_unit_"+index).val();
							//detail_qty =  $("#qty_per_unit_"+index).val();
							$("#current_qty"+index).val(item_qty.qty);
							//total_qty = parseFloat(main_qty) + parseFloat(detail_qty/(item_qty.qty_perunit));
							//$("#qty"+index).val(total_qty.toFixed(3));
							$("#price"+index).val(item_qty.price);
							calculatePrice(index);
							//getProductPrice(item_id,index);
						},
						error:function(e){
							//alert(e);
						}
				});
				
			
}
<?php $url_price =  $this->url(array('module'=>'','controller'=>'ajax','action'=>'getproductprice')); ?>
function getProductPrice(product_id,recordid){
	customer_id=$("#customer_id").val();
	if(customer_id==null || customer_id=="" || customer_id==-1){
		alert("Please Select Customer First !");
		return fale;
		$("#customer_id").focus();
	}else{
		$.ajax({
			url:"<?php echo $url_price;?>",
			type:"post",
			data:{'customer_id':customer_id,'product_id':product_id},
			success: function(data){
				data = $.parseJSON(data);			
				$("#price"+recordid).val(data.price);
				$("#oldprice_"+recordid).val(data.price);
				
				calculatePrice(recordid);
			},
			error:function(e){
				alert(e);
			}
	});
  }
}


function getItemOrder(){
	item_ids=$("#add_item").val();
	$('#add_item').val('').trigger("liszt:updated");
	if(item_ids==-1){
		return false;
	}
	addRow(item_ids);
	//getProductPrice(item_ids);
	$("#add_item").val("");
}
function getTermItem(){
	termid=$("#term_item").val();
	$('#term_item').val('').trigger("liszt:updated");
	if(termid==-1){
		return false;
	}
	addtermcondition(termid);
	$("#term_item").val("");
}
var record_index= 1;
function deleteRecord(index) {
	
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	$("#row_order_"+index).remove();
	newNo();
	netTotal();
}
function newNo(){
	a=0;
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) { a++;
		$('#lbno_'+arrays[i]).text(a);
		//$('#lbno'+arrays[i]).append(a);
	}
}
function deleteTermRecord(termid){
	var identity = $('#identity_term').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == termid) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity_term').val(strings);
	$("#row_term_"+termid).remove();
}
function netTotal() {//use
	var cur_type = $('#currency').val();
	var netTotal=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	var status = $('#status').val();
	for(var n = 0; n < rowIDArray.length; n++) {
		netTotal += Number($('#total'+rowIDArray[n]).val());
	}
	$('#totalAmoun').val(netTotal.toFixed(2));
	calculateDiscount();
}
function calculateDiscount(){//use
	var discountValue = ($('#dis_value').val());
	//if(discountValue==''){$('#dis_value').val(0);discountValue=0;}
	if(discountValue.length!=0){
		if(discountValue.indexOf("%")!==-1){
			var pds=discountValue.split("%");
			    alltotal = $("#totalAmoun").val();
				var discount=(alltotal*parseFloat(pds[0]))/100;
				totalpayment = alltotal - discount;
				$('#all_total').val(totalpayment);
		}else{
				alltotal = $("#totalAmoun").val();
				totalpayment = alltotal - discountValue;
				$('#all_total').val(totalpayment);
		}
		//doRemain();
	}else{
		alltotal = $("#totalAmoun").val();
		totalpayment = alltotal - 0;
		$('#all_total').val(totalpayment);
	}
}
function CalcualteTax() {
	$('#status').val();
}
function doRemain() {
	var all_total = $('#all_total').val();
	
	var paid = $('#paid').val();
	//alert("Paid"+paid);
	if(paid>all_total){
		alert("Paid Value can not biger then total amount test!");
		 $('#remain').val(all_total.toFixed(2));
   }else{
	   remain = all_total-paid;
	   $('#remain').val(remain.toFixed(2));
	}	
}
function totalQty(index){
	getQtyById(index);
}
function calculatePrice(index) {
	//alert(index);
	var cur_qty = parseFloat($('#current_qty'+index).val());
	var qty = parseFloat($('#qty'+index).val());
	if(qty>cur_qty){
		alert('<?php echo $tr->translate("CURRENT_QTY_IS_LESS_THEN_ORDER_QTY")?>');
		$('#qty'+index).val(cur_qty);
		qty=cur_qty;
	}
	//var qty = $('#qty'+index).val();
	var price = $('#price'+index).val();
	var total = price * qty;
	
	//alert("total then aftet discount"+total);
	/*var ds = $('#dis_value'+index).val();
	if(ds.length!=0){
		if(ds.indexOf("%")!==-1){//if have %
			var pds=ds.split("%");
			if(!isNaN(pds[0])){
				var discount=(total*parseFloat(pds[0]))/100;
				after_discount = total - discount;
				
			}else{
				after_discount = total - discount;
			}
			$('#total'+index).val(after_discount.toFixed(2));
		}else{
			after_discount=0;
			if(!isNaN(ds)&&ds!=0){
				discount = parseFloat(ds).toFixed(2);
				after_discount = total - discount;
			}else{
				discount=$('#dis_value'+index).val(0);
				after_discount = total;
			}
			$('#total'+index).val(parseFloat(after_discount).toFixed(2));
		}*/
		$('#total'+index).val(parseFloat(total).toFixed(2));
		
	/*}else{
		$('#total'+index).val(parseFloat(total).toFixed(2));
		}*/
		netTotal();
}
 var record_id = 1;
function ShowPopupProduct(product_id){
	item_id = $("#item_id_"+ product_id).val();
	record_id = product_id;
	if(item_id==-1){
		$('#productpopup').modal('show');
	}
	else{
		getQtyById(product_id);
		//getProductPrice(product_id);
	}
}
function AddLocation(){
	var location_id= $("#LocationId").val();
	if(location_id==-1){
		     AddNewLocation(true);
	  }	
}
<?php $url_code =  $this->url(array('module'=>'sales','controller'=>'index','action'=>'getsonumber')); ?>
function getsaleOrderNumber(){
	branch_id=$("#branch_id").val();
				if(branch_id=="" || branch_id ==null || branch_id==-1){
					return false;
				}
				else{
				$.ajax({
						url:"<?php echo $url_code;?>",
						type:"post",
						data:{'branch_id':branch_id},
						success: function(data){
							so = $.parseJSON(data);
							$("#txt_order").val(so);
						},
						error:function(){
						}
					});
				}	
}
function getCustomerInfo(){
	customer_id = $("#customer_id").val();
	if(customer_id==-1){
		$('#customerpopup').modal('show');
	}
}
<?php $url_add_customer =  $this->url(array('module'=>'sales','controller'=>'customer','action'=>'add-customer')); ?>
function addNewCustomer(){
	var customer_name  = $("#txt_name").val();
	$.ajax({
        url: "<?php echo $url_add_customer;?>",
        type: "post",
        data: $('#frmcustomer').serialize(),
        success: function(data){
            rs = $.parseJSON(data);
             $('#customer_id').append($("<option></option>").attr("value",rs['cus_id']).attr("selected",true).text(customer_name));                       
             $("#customer_id").select2();
			$('#customerpopup').modal('hide');
        },
        error:function(err){
            alert("faile insert");
           
        }
    });
}
<?php $url_plan =  $this->url(array('module'=>'sales','controller'=>'index','action'=>'get-plan-addr')); ?>
function addPlanAddr(){
	var id  = $("#plan").val();
	$.ajax({
        url: "<?php echo $url_plan;?>",
        type: "post",
        data:{ 'id':id},
        success: function(data){
            rs = $.parseJSON(data);
             $('#plan_addr').val(rs);                       
        },
        error:function(err){
            alert("faile insert");
           
        }
    });
}

<?php $url_request_code =  $this->url(array('module'=>'sales','controller'=>'index','action'=>'get-request-no')); ?>
function getQuotenumber(){
	$("#txt_order").val("");
				branch_id=$("#branch_id").val();
				if(branch_id=="" || branch_id ==null || branch_id==-1){
					return false;
				}
				else{
				$.ajax({
						url:"<?php echo $url_request_code;?>",
						type:"post",
						data:{'branch_id':branch_id},
						success: function(data){
							//alert(data);
							qo = $.parseJSON(data);
							$("#apno").val(qo);
						},
						error:function(){
						}
					});
				}	
}
</script>	